### ISSUE TITLE
[overlay] less verbose way to annotate that it's ok for overlay to create-or-update

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#1]
in example-overlay-files, ops2.yml adds multiple map items (under annotations key) [1]. it has to specify missing_ok=True for per key because to indicate that it's ok to create-or-update. need to come up with a way to allow skipping such annotation as it's pretty verbose.

few options:
- somehow annotate multiple nodes together
- annotate that children of a particular node are ok with missing_ok=True (probably an easier and better option)

[1] https://github.com/get-ytt/ytt/blob/master/examples/playground/example-overlay-files/ops2.yml#L7-L10

**Comment by cppforlife** [comment]
added `@overlay/match-child-defaults` annotation in https://github.com/k14s/ytt/commit/f3443fd34b1d593fe0d0e4af0df1064e05dc6548. will be available in v0.20.0.

example: https://gist.github.com/cppforlife/9a63a5ce714e2f72f5ded8c070efef4e

**Comment by cppforlife** [comment]
above released in https://github.com/k14s/ytt/releases/tag/v0.20.0

**Comment by cppforlife** [comment]
related: https://github.com/k14s/ytt/issues/53

**Comment by pivotaljohn** [comment]
Adding a comment to demonstrate that GitHub issues have history

This first version includes this: SUPER CONFIDENTIAL SECRET.
