### ISSUE TITLE
Errors on first line of .star files cause panics

### ISSUE THREAD

**Issue by ewrenn8** [k14s/ytt#101]
If a `.star` file has an error on the first line, it will cause `ytt` to panic. 

**Repo steps:**
1. `echo "bad-syntax" > test.star`
2. `ytt -f test.star`

**Result:**
`panic: Lines are 1 based`

**Notes:**
Because it occurs on line one of the file, [this line](https://github.com/k14s/ytt/blob/9f446e9c05f395f980c5cc9fbed53444aa2c76d2/pkg/template/compiled_template_error.go#L168) is attempting to create an invalid position, leading to a panic.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/commit/bc93b02168e26aa981c8d676b260605d7cd2af88

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.26.0
