### ISSUE TITLE
[data/values] support applying data values to pulled in libraries (via library module)

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#105]
it's necessary sometimes to customize data values for libraries that were pulled in. currently `@data/values` allows configuration of the "current" library but not its child libraries. of course one can always use overlays to change any aspect of configuration; however, it's better to provide a way to configure child libraries explicitly. 

let's introduce additional flag on `@data/values` annotation to indicate that values are for a particular library, like so (cannot use `for` kwarg since it's a keyword):

```yaml
#@data/values library="github.com/cloudfoundry/capi-k8s-release"
---
replicaCount: 2
```

in some cases one needs to configure nested library (db-config is included in capi-k8s-release), so we should be able to do something like this:

```yaml
#@data/values library=("github.com/cloudfoundry/capi-k8s-release", "github.com/cloudfoundry/db-config")
#! or 
#@data/values library="github.com/cloudfoundry/capi-k8s-release:github.com/cloudfoundry/db-config"
---
foo: blah
```

above data values should be overlayed before library module provided data values are merged. we should also support a way to overlay values after library module provided data values via `after_library_module=True` kwarg.

when same library is included multiple times, ytt should somehow identify a particular library instance (ideally by an additional given name).

we should also figure out how to pass in data value for a particular library over command line (may be something like that: `ytt -f config --data-value-yaml github.com/cloudfoundry/capi-k8s-release:replicaCount=2 --github.com/cloudfoundry/capi-k8s-release:github.com/cloudfoundry/db-config:foo=blah`)

TBD:
- should we use `:` for separating libraries
- better name for `after_library_module`?

**Comment by cppforlife** [comment]
for multiple copies of the same library, i'm thinking of 
```bash
--data-value-yaml github.com/cloudfoundry/capi-k8s-release~inst1:replicaCount=2 \
--data-value-yaml github.com/cloudfoundry/capi-k8s-release~inst2:replicaCount=2
```

and for data values file...

```yaml
#@data/values library="github.com/cloudfoundry/capi-k8s-release~inst1"
---
...
```

may be some other char to indicate named library?

**Comment by ewrenn8** [comment]
## Updated direction
We will introduce a new annotation `#@library "github.com/cloudfoundry/capi-k8s-release"` which will apply to yaml documents. The yaml document will then only be included if/when the library is evaluated through the library module.

The order of data value overlaying will be: 
1. library data value files 
1. library attached data value documents (ordered by [global ordering](https://github.com/k14s/ytt/blob/master/docs/lang-ref-ytt-overlay.md#overlay-order) from cmd line)
1. `.with_data_value(...)` args
1. library attached data value documents with kwarg after_library_module provided to #@data/values annotaion (ordered by [global ordering](https://github.com/k14s/ytt/blob/master/docs/lang-ref-ytt-overlay.md#overlay-order) from cmd line)

Library attached templates will be evaluated in global order *after* any library templates

Library attached overlay docs will be applied in their [global order](https://github.com/k14s/ytt/blob/master/docs/lang-ref-ytt-overlay.md#overlay-order) *after* any library contained overlays

**Comment by aaronshurley** [comment]
Remaining work:
- [ ] fix up library tagging issue
- [ ] figure out how to handle env vars
  - [ ] library identifier in the env var values
  - [ ] library identifier in the env var keys
- [ ] Add ability to inspect data values of other libraries

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.28.0. moving inspect related items to separate issue: https://github.com/k14s/ytt/issues/153.
