### ISSUE TITLE
Consider using the name kytt instead of ytt?

### ISSUE THREAD

**Issue by jessehu** [k14s/ytt#111]
Since the name of almost all tools in k14s starts with 'k', do we ever consider using the name kytt instead of ytt? kytt is also easy to pronounce comparing to the acronym ytt?

**Comment by cppforlife** [comment]
> Since the name of almost all tools in k14s starts with 'k'

that's mostly an artifact of those tools being specific to kubernetes. ytt, however, is a generic tool (doesnt even know what k8s is), and so it doesnt have a `k` in front.

**Comment by cppforlife** [comment]
>  do we ever consider using the name kytt instead of ytt

possibly, though probably not in the short term.

**Comment by cppforlife** [comment]
closing for now.
