### ISSUE TITLE
Would like support for named pipes and process substitution.

### ISSUE THREAD

**Issue by squeedee** [k14s/ytt#12]
I often use process substitution, especially if I'm bringing down secrets using a vault tool like lpass/credhub.

I want to use the command: ytt template -f pipeline.yml -f <(..cmd-that-gets-secrets..) but then I hit this:

https://github.com/k14s/ytt/blob/4b7b67ef6d88cc4777d38e9fbd310daa567961fa/pkg/files/file.go#L203

Eg:

```
$ ytt template -f <(echo "---")
Error: Expected file '/dev/fd/63' to be a regular file, but was not
```

Is this really just guarding against directories?

**Comment by cppforlife** [comment]
@squeedee fixed in https://github.com/k14s/ytt/commit/e2a5e3f6da3498bfad86716e19a32d45e2fe3477. will cut new version tomorrow.

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/releases/tag/v0.6.0

**Comment by samschlegel** [comment]
This appears to have regressed at some point

```bash
$ ytt version
Version: 0.16.0
$ ytt -f <(echo "---")                                                                                                                                                         
Error: Expected file '/proc/self/fd/11' to be a regular file, but was not
```
