### ISSUE TITLE
Allow normal YAML comments

### ISSUE THREAD

**Issue by drnic** [k14s/ytt#123]
Currently `ytt` hates normal YAML comments.

If it processes this file:
```yaml
hello: world # this is a normal comment
```

```
$ ytt -f sample.yml
ytt: Error: Unknown comment syntax at line sample.yml:1: ' this is a normal comment': Unknown metadata format (use '#@' or '#!')
```

This makes it impossible to apply `ytt` to YAML files that are maintained by 3rd parties who do not care about ytt, or simply oblivious to potential ytt use cases.

Could `#` be added as a valid comment in addition to `#!`?

I'm new to ytt, so I'm still trying to use it for stuff. Perhaps I'm going to use it for activities it can't do. For example, I was going to take a https://github.com/cloudfoundry/cf-for-k8s/blob/master/vendir.yml, rewrite the `includePaths` to get the entire repos (for `git` contents), and I'd have a `vendir.yml` that could fetch all the source code. Still trying to figure out how to get ytt to do this. The comments throwing errors might be a red herring.

**Comment by cppforlife** [comment]
you can use `--ignore-unknown-comments` flag to let ytt know it's safe to ignore regular comments. the reason why it's important for ytt to be strict is to catch any accidental missing @ to indicate that it's ytt template code.

**Comment by drnic** [comment]
Thanks.
