### ISSUE TITLE
create something like jb for ytt

### ISSUE THREAD

**Issue by fredwangwang** [k14s/ytt#126]
[jb](https://github.com/jsonnet-bundler/jsonnet-bundler) is a package manager for jsonnet. When the adoption of ytt get larger, something like jb (yb?) would probably be helpful to manage import of various std/custom libs

**Comment by cppforlife** [comment]
@fredwangwang have you seen https://github.com/k14s/vendir? we use in a few places to pull in configuration from various sources.

**Comment by fredwangwang** [comment]
@cppforlife thanks! Clearly I don't know where to find stuff. Is it possible to mention vendir on the readme/docs of ytt so vendir is better surfaced?
