### ISSUE TITLE
Override data values without defining default?

### ISSUE THREAD

**Issue by eroji** [k14s/ytt#127]
I am trying to leverage YTT to template the generation of overlay layer for Kustomization however it appears that you can only override data.values via CLI, and to override them, they must be defined in a values.yaml of some sort and make sure that file is read during generation?

For example, **kustomization.yaml**
```
#@ load("@ytt:data", "data")
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: #@ data.values.namespace
patchesStrategicMerge:
- service.yaml
resources:
- ../../base
images:
- name: test
  newTag: tag
```

**values.yaml**
```
#@data/values
---
namespace: test1
```

If I run `ytt -f .` or `ytt -f kustomization.yaml -f values.yaml`, which looks as I expect
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test1
patchesStrategicMerge:
- service.yaml
resources:
- ../../base
images:
- name: test
  newTag: tag
```

If I run `ytt -f kustomization.yaml`
```
ytt: Error:
- struct has no .namespace field or method
    in <toplevel>
      kustomization.yaml:5 | namespace: #@ data.values.namespace
```

If I run `ytt -f kustomization.yaml -v namespace=test123` it blows up, even though technically I supplied it with the k:v pair it needs to generate. This seems odd to me.
```
ytt: Error: Overlaying data values (in following order: additional data values): Overlaying additional data values on top of data values from files (marked as @data/values): Document on line key 'namespace' (kv arg):1: Map item (key 'namespace') on line key 'namespace' (kv arg):1: Expected number of matched nodes to be 1, but was 0
```

**Comment by pivotaljohn** [comment]
Yeah, this combination results in a bad UX:

- the error message should be much more clear: k14s/ytt#72
- the author should have the ability to expressly add data values from command-line args: k14s/ytt#81

Thank you for submitting this issue. It gives us more signal on how important this use-case is.

**Comment by pivotaljohn** [comment]
Closing this issue as we're tracking the work in those mentioned, above.

**Comment by cppforlife** [comment]
@eroji, separately from the issue itself you filed, im curious about your use case of templating kustomize files. anything you are not able to do with ytt overlays?

**Comment by eroji** [comment]
I looked at the examples for overlay but I don't think it quite fits my usecase. We have a gitops workflow where the manifest has a base set of files with the overlay layers separated via directories per namespace, respective to our environments. For example, app1 has a base layer and overlay layers for dev/stage/prod. Between these directories for each namespace/environment overlay, there may be some differences such as replica count, persistent volume, load balancer IP and image tags. However, they essentially share the same basic structure. What I am trying to achieve is to have a tool to quickly generate a new set of manifests for an namespace/environment, without having to do a lot of manual copy and paste. That includes having the ability to override certain values as needed. I couldn't find any tooling out there to do this, and it may just be that I have to write something myself, which is fine.

**Comment by cppforlife** [comment]
@eroji 

> I looked at the examples for overlay but I don't think it quite fits my usecase... I couldn't find any tooling out there to do this, and it may just be that I have to write something myself, which is fine.

hmm, interesting, reading thru your description this is exactly what ytt is typically used for. there are multiple approaches that ytt allows that range from pure templating to templating+overlays to just overlays. im happy to chat more may be on slack if your are interested.
