### ISSUE TITLE
Unrecognized command-line arguments should be treated as errors

### ISSUE THREAD

**Issue by ericpromislow** [k14s/ytt#131]
We ran into this while writing some tests that invoked `ytt` and found it was ignoring filenames that weren't heralded with `-f`:

```
$ ytt ./configs_test.go
<no output>
$ echo $?
0
```

We would have expected to see an error message pointing out the unprocessable command-line arguments.

**Comment by ewrenn8** [comment]
Fixed in 452b1b9d5b61cecb766d4ce69d23f944d5865c3f

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.28.0
