### ISSUE TITLE
Looking for a way to concatenate (merge) YAML sequences using ytt

### ISSUE THREAD

**Issue by leonidbelkind** [k14s/ytt#133]
I am looking for a way to merge/concatenate two or more YAML sequences (loaded from different files/libraries) into a single sequence.
This is something that is not supported by definition by current YAML format, so it makes perfect sense to do this with ytt.
Currently unable to do that - tried functions that return "yamlfragment" object of a "partial" sequence, but not managing to merge to a single sequence.
Will appreciate any suggestions.

**Comment by cppforlife** [comment]
hey @leonidbelkind, you can use overlay library to merge two arrays:

```yaml
#@ load("@ytt:overlay", "overlay")

#@ def first():
- 1
- 2
#@ end

#@ def second():
- 100
- 200
#@ end

#@ def append_seq_overlay(seq):
#@ for/end item in seq:
#@overlay/append
- #@ item
#@ end

---
combined: #@ overlay.apply(first(), append_seq_overlay(second()))
```

or if you can just add overlay annotations to second seq directly it gets even shorter:

```yaml
#@ load("@ytt:overlay", "overlay")

#@ def first():
- 1
- 2
#@ end

#@ def second():
#@overlay/append
- 100
#@overlay/append
- 200
#@ end

---
combined: #@ overlay.apply(first(), second())
```

**Comment by cppforlife** [comment]
closing. feel free to reach out on slack or here for additional info.
