### ISSUE TITLE
[data/values] how to access keys with dash

### ISSUE THREAD

**Issue by combor** [k14s/ytt#154]
Hi, 

I'm trying to find a way in the docs how to load values of a key with dash in the name.
Here's the playground example:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/163394/84672969-0885f600-af21-11ea-9424-0649aedb365e.png">

Do I need to escape/quote something?

**Comment by ewrenn8** [comment]
Hi @combor,

To use a key with a dash, you will need to use the `getattr` function, `getattr(data.values, key1-a)`, otherwise, ytt will interpret the dash in the key name as a subtraction in the code.

**Comment by combor** [comment]
Thanks, this works. Is this mentioned somewhere in the docs?

**Comment by cppforlife** [comment]
added to docs here: https://github.com/k14s/ytt/blob/5a9ad6050a5bc2d479faddcdc037ff43ba0d5e2b/docs/ytt-data-values.md#defining-data-values. in general though, i would recommend using snake case for data value names.

**Comment by combor** [comment]
👍 thanks for the docs update and the recommendation.

**Comment by abuechler** [comment]
@cppforlife Is this mentioned some where in the current docs? I couldn't find it and expected to find something here: https://carvel.dev/ytt/docs/v0.52.x/ytt-data-values/#--data-values-file

**Comment by prembhaskal** [comment]
@abuechler it is mentioned here https://carvel.dev/ytt/docs/v0.52.x/lang-ref-ytt-schema/#names  

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/2dff7754-6ab3-42e4-93f6-0859e10f0496" />
