### ISSUE TITLE
`go get` installation broken on 0.28

### ISSUE THREAD

**Issue by Naatan** [k14s/ytt#155]
Results in: 
```
# github.com/k14s/ytt/pkg/template
.go/pkg/mod/github.com/k14s/ytt@v0.28.0/pkg/template/compiled_template.go:145:51: undefined: syntax.BlockScanner
```

**Comment by cppforlife** [comment]
ive ran `go install github.com/k14s/ytt/cmd/ytt` in a new vm and it works (go get also worked). 

error above seems to starlark-go dependency is not correct; ive manually checked this line and it's correct: https://github.com/k14s/ytt/blob/v0.28.0/go.mod.

im guessing there is either some kind of a go mod caching bug or some other "out of sync" issue on your system.

**Comment by Naatan** [comment]
Bah, I was running it from my project dir rather than the global dir. My bad.
