### ISSUE TITLE
yaml line folding for long lines

### ISSUE THREAD

**Issue by zalyoung** [k14s/ytt#161]
When we use Text Template to render a notification message which will be sent to Slack, the rendered content will add a new breaking line if the content exceed a particular length and contains space. 

Please help to check the below sample.

- demo.yaml
```
#@ load("@ytt:data", "data")

#@ environment = data.values.environment
#@ replica = data.values.replica

subject1: #@ "{} - WARNING - The number of healthy Nginx Ingress Controller pods is not equal to {}".format(environment,replica)

#@yaml/text-templated-strings
subject2: "(@= environment @) - WARNING - The number of healthy Nginx Ingress Controller pods is not equal to (@= replica @)"
```

- values.yaml
```
#@data/values
---
environment: Development
replica: '2'
```

- Output
```
subject1: Development - WARNING - The number of healthy Nginx Ingress Controller pods
  is not equal to 2
subject2: Development - WARNING - The number of healthy Nginx Ingress Controller pods
  is not equal to 2
```

**Comment by cppforlife** [comment]
per our slack conversation: we use yaml library that wraps long lines which is valid behaviour according to 6.5 Line Folding in YAML spec (https://yaml.org/spec/1.2/spec.html#id2779048). this low level library behaviour is not something that is configurable.

on a side note, it seems that you are using ytt to produce a block of text and you want particular formatting. you may want to consider using text templating feature (files with .txt): https://get-ytt.io/#gist:https://gist.github.com/cppforlife/256be862b3624fdb6c3e0cbcf9f57907

**Comment by cppforlife** [comment]
@zalyoung i have pushed a change to ytt to disable line folding after noticing that upstream yaml library decided to do that as well: https://github.com/k14s/ytt/commit/7c8609d07116a1073345466d02016eed5b701474 (https://github.com/go-yaml/yaml/pull/571). should be available in next ytt release.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.30.0
