### ISSUE TITLE
Alternative to overlaying?

### ISSUE THREAD

**Issue by damzog** [k14s/ytt#164]
Hi,
given I have yml input and I want to select data dependant on the deployment target:

```
dns:
  us: 1.2.3.4
  de: 2.3.4.5
```
So I would like to see a way of selecting subtrees when addressing data.values like:
```
#@ region = "us"
...
dns: #@ data.values.dns.<put value of variable region here and select the values under the respective node>
```
I was able to achive it with getattr() function but that is not very elegant. I see that you suggest using overlay for this but that is very opinionated about how the config files look likes and it is difficult to read and maintain. Also it does not reflect that there might be multiple parameters to consider like stage + region.

**Comment by cari-lynn** [comment]
Hi @damzog 
Requiring the user to use `getattr()` it disambiguates the case when there is a variable and a data value key that share the same name. In [this example](https://get-ytt.io/#gist:https://gist.github.com/pivotal-dean/866d322af4e950c66e1bd86168596d0e) using  `data.values.foo` is different than using the `getattr(data.values, foo)`. `getattr()` makes it clear which value the user intended.

We're curious why overlays don't satisfy this need. If you are able to, could you provide a more detailed example with your templates, values, and expected output?

**Comment by cppforlife** [comment]
@damzog ive previously considered to extend data.values structs to allow [] access. e.g `data.values.dns[data.values.region]` which would be instead of `getattr(data.values.dns, data.values.region)`. would that make it more elegant in your opinion?

**Comment by damzog** [comment]
@cppforlife  Yes it definitely would. Looking at your example I think it should look more like `data.values.dns[region]` .  Keep in mind that region is actually a variable not a string. So if it is part of a path like data.values.region this becomes even less obvious.

The dns part could actually by used to determine the map if you allow multiple value documents as input (like beginning a values yaml with #@data/values/dns )

That construct would still not solve the case where you have multiple criteria to select, e.g. region=us and stage=dev.

In general as an explanation this is requirement is similar to what you have with bosh ops files for selectively addressing nodes in the yaml tree for example for a values yaml like

```
dns:
  - region: us
    ips: [1.2.3.4, 2.3.4.5]
  - region: eu
    ips: [5.6.7.8, 6.7.8.9]
```
the ips for the dns in region us can be addressed with the path /dns/region=us/ips.
```
- type: replace
  path: /dns/region=us/ips
  value: [7.2.3.4, 7.3.4.5]
```

Also to explain the motivation: I would like to use yml files as input for ytt that are not part of my component hence I do not have authority to change their layout in other words the format of those yamls is not optimized for my use case.

**Comment by cppforlife** [comment]
> Looking at your example I think it should look more like data.values.dns[region] . Keep in mind that region is actually a variable not a string.

yeah if it would be a string it would be quoted eg `data.values.dns["region"]`

> So if it is part of a path like data.values.region this becomes even less obvious.

not sure why? that's general regular programming imho, data.values.region just holds some value. you can use whatever variables you want that holds whatever value.

> That construct would still not solve the case where you have multiple criteria to select, e.g. region=us and stage=dev.

`x[y]` accessor isn't in any way special. its just a way to access field off of a struct. if you want to do filtering like you describe just write a function. eg

```
def filter(vals, region, stage):
  result = []
  for val in vals:
    if val.region == region and val.stage == stage:
      result.append(val)
    end
  end
  return result
end

#! and elswhere
filter(data.values.dns, "us", "st")
```

**Comment by cppforlife** [comment]
closing since we think question was answered. feel free to reopen or find us on slack.
