### ISSUE TITLE
[data/values] ytt should pass "-v mykey=true" as a Boolean instead of String

### ISSUE THREAD

**Issue by jessehu** [k14s/ytt#166]

**Comment by ewrenn8** [comment]
Hey @jessehu,

You can use the `--data-value-yaml` flag to interpret that value passed in as yaml instead of a string

**Comment by jessehu** [comment]
Thanks @ewrenn8. `--data-value-yaml mykey=true` works.
But `--data-value-yaml mykey="true"` will get boolean rather than string. Is this by design?

**Comment by ewrenn8** [comment]
Yes, this is because bash is interpreting the quotes first. To pass in true as a string you would need to use `--data-value-yaml mykey=\"true\"`

**Comment by jessehu** [comment]
Got it. Thanks very much! I'm wondering if we need to make `-v` as the alias for `--data-value-yaml` instead `--data-value`. I guess the users will use `-v` the most.

**Comment by cppforlife** [comment]
behaviour of -v would be improved once we have data value schemas defined. as of now we do not know what type of -v should be hence we default to string which is a bit "safer" than parsing all values as yaml.

**Comment by jessehu** [comment]
Thanks @cppforlife. If we expect '-v' as the default param that the users will use, I think '-v' as alias for --data-value-yaml instead of --data-value makes more sense. When specifying a boolean value 'true' or an int value '1' in the command line, the users obviously want them to be intepreted as boolean or int separately, rather than a string.

```
ytt-sample$ ytt -f my.yaml -f values.yaml --data-value bool=true --data-value int=1 --data-value str=abc
bool: "true"
int: "1"
string: abc

ytt-sample$ ytt -f my.yaml -f values.yaml --data-value-yaml bool=true --data-value-yaml int=1 --data-value-yaml str=abc
bool: true
int: 1
string: abc

ytt-sample$ ytt -f my.yaml -f values.yaml --data-value-yaml bool=\'true\' --data-value-yaml int=\'1\' --data-value-yaml str=abc
bool: "true"
int: "1"
string: abc
```

**Comment by pivotaljohn** [comment]
With Schema in place, we have the tools to be able to achieve this convenience without sacrificing "correctness"/safety. The additional work is covered by:
- #356

We'll track the progress of this feature in _that_ story: closing this one.
