### ISSUE TITLE
[data/values] Make '---' in values.yaml optional

### ISSUE THREAD

**Issue by jessehu** [k14s/ytt#167]
Is the '---' in values.yaml required? We hit an issue related to '---' and yq (see https://github.com/mikefarah/yq/issues/351).

```
#@data/values
---
key: value
```
Without '---', ytt gives this error. But '---' is optional per yaml spec.

`ytt: Error: Expected YAML document to be annotated with data/values but was *yamlmeta.MapItem`

**Comment by cppforlife** [comment]
> Is the '---' in values.yaml required?

it's required because `@data/values` annotation is associated with a document. if it was removed there would be no way to add @data/values to the document.

**Comment by jessehu** [comment]
So can ytt adds '---' implicitly for a values.yaml if it's not there?

**Comment by cppforlife** [comment]
ytt knows that yaml document is data values is by finding documents with that annotation. file name itself (values.yml) isnt indicative that it contains data values.

**Comment by jessehu** [comment]
Hi @cppforlife, I meant when ytt reads a file my-data-values.yaml and finds `#@data/values` at the beginning, can ytt implictly adds `---` if there is no such line `---` after `#@data/values`? yaml spec doesn't require `---` at the beginning of a file.  It's interesting that current ytt requires `---` exists in the data values yaml , but doesn't require `---` exists in other ytt templates yaml file.

**Comment by cppforlife** [comment]
> can ytt implictly adds --- if there is no such line --- after #@data/values

something like this?

```yaml
#@data/values
foo: blah
other: another
```

we _could_ make it wrong however from more of a purist ytt perspective this isnt "conceptually valid" since @data/values annotation is only apply to `foo: blah` instead of both of the kvs. this would be pretty significant step away from an understanding that a user might have about how annotations work.

**Comment by jessehu** [comment]
I see what you meant.  Does `foo: blah` with the annotation `#@data/values` make any sense to ytt ? If not, there is no ambiguity. Then why not ytt interprets the following valid yaml file
```
#@data/values
foo: blah
other: another
```
as 
```
#@data/values
---
foo: blah
other: another
```

**Comment by cppforlife** [comment]
> If not, there is no ambiguity. Then why not ytt interprets the following valid yaml file

there is no ambiguity in this case, but it goes against all other cases how annotations are set up in ytt (annotation never is applied to a parent node. only to self or children).

it also seems that this is driven by a deficiencies in other tools. https://github.com/mikefarah/yq/issues/351#issuecomment-646543022 seems to indicate that yq doesnt understand documents at all.

**Comment by jessehu** [comment]
We can put aside yq. One of the principle of ytt is that `Works directly with YAML structures, not text`, but it dosen't work with this valid yaml file:

```
#@data/values
foo: blah
other: another
```

**Comment by ewrenn8** [comment]
ytt assigns the annotations to the following yaml node, which in this case is the map entry foo. Your example above would be the same as saying:
```
---
#@data/values
foo:blah
other: another
```
To apply the annotation to the implied document start would not make much sense. For example, users would expect:
```
#@yaml/map-key-override
foo: bar
```
to translate to
```
---
#@yaml/map-key-override
foo: bar
```
not
```
#@yaml/map-key-override
---
foo: bar
```

**Comment by cppforlife** [comment]
given above explanation from eli, ill close this issue.
