### ISSUE TITLE
add regexp.replace 

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#169]
currently we have regexp.match (https://github.com/k14s/ytt/blob/develop/docs/lang-ref-ytt.md). jacob barrett (https://kubernetes.slack.com/archives/CH8KCCKA5/p1594261022023900) asked about ability to replace matched parts.

ytt's regexp is backed by Go's regexp (https://golang.org/pkg/regexp/). so we would want to "shim" it in some friendly way. so far i like https://golang.org/pkg/regexp/#Regexp.ReplaceAllStringFunc as a direction.

**Comment by aaronshurley** [comment]
Looks like this work was merged in as part of https://github.com/vmware-tanzu/carvel-ytt/pull/191. Closing.
