### ISSUE TITLE
For loop with index?

### ISSUE THREAD

**Issue by brightzheng100** [k14s/ytt#17]
How to get the index in the `for` loop?

For example:

```
#@ for product in data.values.products:
- #@ "product-{}-{}".format(#@i, product)
#@ end
```

**Comment by brightzheng100** [comment]
Ah, just checked out the Startlark repo and tried this in the playground.
Surprisingly, it works:

```
#@ load("@ytt:data", "data")

products:
#@ for product in data.values.products:
#@ idx=data.values.products.index(product)
- #@ "product-{}-{}".format(idx, product)
#@ end
```
So may check out that website to learn more syntax.

**Comment by cppforlife** [comment]
here is a more canonical way that properly works for duplicate elements:

array_with_data:
#@ arr = [1,5,{"key":"val"}]
#@ for i in range(len(arr)):
- item: #@ [i, arr[i]]
#@ end

ill add that to list example on interactive playground.

**Comment by cppforlife** [comment]
updated docs and example: https://github.com/k14s/ytt/commit/1d5d10a0ff8f4d5a6f1123ee736cf45783ee6141 and https://github.com/k14s/ytt/commit/d4686fab83cfee54093b318e0e92ec7e3388ebe1
