### ISSUE TITLE
Loading all functions in a library

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#171]
I was wondering, instead of doing `#@ load("config.lib.yml", "base", "base_ref")`, is there a way to do `#@ load("config.lib.yml", "config")` and use the functions as `config.base` and `config.base_ref`? I tried the above and it could not load `config.lib.yml`.

**Comment by ewrenn8** [comment]
Hey @peterfeifanchen,

You could add the functions to a struct and then load the struct from `config.lib.yml`. An example here: https://get-ytt.io/#gist:https://gist.github.com/ewrenn8/df0830f14e9724b82d10fae0442aa095

Eli

**Comment by peterfeifanchen** [comment]
Thanks!

**Comment by peterfeifanchen** [comment]
Oh I guess also, how do you do it for *.star files if they are just normal starlark functions?

**Comment by ewrenn8** [comment]
Yep, it can be done the same way. Example here: https://get-ytt.io/#gist:https://gist.github.com/ewrenn8/07f875e7fed11015c563921da75ed0a9

**Comment by cppforlife** [comment]
closing this per answer above. feel free to reopen or ping us on slack.
