### ISSUE TITLE
anchor evaluation is not compatible with ytt directives on the same node

### ISSUE THREAD

**Issue by jtarchie** [k14s/ytt#172]
When converting a YAML file that used ERB templating to `ytt` we experienced an issue with anchors.

We were able to replicate it in this simple case.

Given `output.ytt`:

```yaml
nullz: &nullz #@ "asdf"
asdf: *nullz
```

I expected the output to be:

```yaml
nullz: asdf
asdf: asdf
```

But what I got was:

```yaml
nullz: asdf
asdf: null
```

If this is a Works as Expected™, please document it clearly. Anchors are such a big part of YAML that this simple behaviour through us off in our concourse pipeline.

**Comment by cppforlife** [comment]
documented as known limitation here: https://github.com/k14s/ytt/blob/develop/docs/known-limitations.md. will close for now, and mark as "deferred".
