### ISSUE TITLE
how to merge two array yamlfragments?

### ISSUE THREAD

**Issue by fredwangwang** [k14s/ytt#180]
Example:

```yaml
---
#@ def array_a():
- 1
- 2
#@ end

#@ def array_b():
- 3
- 4
#@ end
---

modified: #@ array_a() + array_b()

#! would generate:

#! ytt: Error: 
#! - unknown binary op: yamlfragment + yamlfragment
#!     in <toplevel>
#!       a.yml:13 | modified: #@ array_a() + array_b()
```

The user should be able to merge two yaml arrays together trivially

**Comment by cari-lynn** [comment]
Hey @fredwangwang! 

The default merging behavior for arrays is to overwrite them, this is because there is no default criteria for matching items in the array (unlike map items, which can match by key). You can use overlays to merge items into an existing array. Overlays allow you to be specific about how merging should behave. For example, you can remove, replace, or append array items. 

To append to array_a you can define the array in your data values:

```
#@data/values
---
array_a:
- 1
- 2
```
To append to it, define an overlay with the additional items
```
#@data/values
#@ load("@ytt:overlay", "overlay")
---
array_a:
#@overlay/append
- 3
#@overlay/append
- 4
```

There is some additional information and examples on this in our [faq](https://github.com/k14s/ytt/blob/develop/docs/faq.md#how-do-i-add-items-to-an-existing-array). 

Please let us know if this is not what you are looking for.

**Comment by fredwangwang** [comment]
my bad, should've called it `append` instead of `merge` to avoid confusing. 

So my use case is that I have two function call that each returns a yaml array fragment, and I need to combine them into a single array and assign to a key:

```
---
#@ def square(nums):
#@ for i in nums:
#! only as an example, I have some complex yaml snippet
#! here that I don't want to rewrite as pure star functions
- #@ i * i
#@ end
#@ end
---
#@ def cubic(nums):
#@ for i in nums:
#! only as an example, I have some complex yaml snippet
#! here that I don't want to rewrite as pure star functions
- #@ i * i * i
#@ end
#@ end
---

#@ input = [1,2,3,4,5]

#! The output I am looking for is the concatenation of:
#! - output from square
#! - output from cubic
nums: #@ square(input) + cubic(input)
```

Can this use case be satisfied right now without any substantial pain to figure out the tricks?

**Comment by gcheadle-vmware** [comment]
One way to achieve what you want without adding data values and overlays would be to use templates with the 
```#@ template.replace()``` annotation. Templates are often used for editing items in maps, but can also be used in arrays. For your specific example, you can use templates to append the two lists onto the nums item.

```
---
#@ def square(nums):
#@ for i in nums:
- #@ i * i
#@ end
#@ end

#@ def cubic(nums):
#@ for i in nums:
- #@ i * i * i
#@ end
#@ end

---
#@ load("@ytt:template", "template")
#@ input = [1,2,3,4,5]

nums:
- #@ template.replace(square(input))
- #@ template.replace(cubic(input))
```

For further information on using templates, here is an [example from the ytt playground](https://get-ytt.io/#example:example-replace).

**Comment by cppforlife** [comment]
here is how to do it with overlays:

```yaml
#@ def first(nums):
- 1
- 2
- 3
#@ end

#@ def second(nums):
- 4
- 5
- 6
#@ end

#@ def appended(ary):
#@ for/end a in ary:
#@overlay/append
- #@ a
#@ end
---

#@ load("@ytt:overlay", "overlay")
#@ input = [1,2,3,4,5]
nums: #@ overlay.apply(first(input), appended(second(input)))
```

appended() effectively takes array and marks each item with overlay/append to indicate how item should be "merged".

**Comment by cppforlife** [comment]
closing per above responses.

**Comment by patricknelson** [comment]
@cppforlife's example was helpful, but it confused me initially since it didn't make use of the `input` arguments. I've simplified it just for readability, in case anyone else also got here trying to learn how to accomplish the same thing (merging arrays in `ytt`). 😄 

```yaml
#@ def first():
- 1
- 2
- 3
#@ end

#@ def second():
- 4
- 5
- 6
#@ end

#@ def appended(array):
#@ for/end item in array:
#@overlay/append
- #@ item
#@ end
---

#@ load("@ytt:overlay", "overlay")
nums: #@ overlay.apply(first(), appended(second()))
```
