### ISSUE TITLE
should we always output `---` for all YAML files

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#182]
currently we do not output first `---` since it's not required by YAML. some folks may appreciate to consistency of always adding that in.

**Comment by pivotaljohn** [comment]
And to be clear, we're talking about non-empty documents, yeah?

I ask because I know of a few cases where we rely on skipping empty documents to keep the output sane.

**Comment by cppforlife** [comment]
> And to be clear, we're talking about non-empty documents, yeah?

that's right.

**Comment by cari-lynn** [comment]
This is a duplicate of #477 , there's some discussion there, so I'm going to close this.
