### ISSUE TITLE
Peculiar handling of the map key "on"

### ISSUE THREAD

**Issue by HoloRin** [k14s/ytt#189]
The yaml file `test.yml`:
```yaml
on: foo
```
templated with `$ ytt -f test.yml` produces 
```
true: foo
```

Which is certainly unexpected, and I believe incorrect.

**Comment by jorgemoralespou** [comment]
Is this related? https://github.com/k14s/ytt/issues/146

**Comment by cppforlife** [comment]
@jorgemoralespou yes it is. ill close this as a dup, in favor of keeping #146. in yaml 1.1 "on" is a special identifier that represents a boolean value true.
