### ISSUE TITLE
Using --data-value-yaml to add a list

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#196]
Is there a way to do `ytt -f . --data-value-yaml branches= <yaml list somehow>` ?

**Comment by StevenLocke** [comment]
You're very close! Thanks for the question.

A quick caveat, when specifying a data-value (include a data-value-yaml) from the command line, "[they] must be defined in at least one @data/values YAML document." (See the [Overriding data values via command line flags](https://github.com/k14s/ytt/blob/develop/docs/ytt-data-values.md#overriding-data-values-via-command-line-flags) docs)

The way to specify a list is with quoted square brackets, eg:
```Shell
ytt -f base.yaml -f values.yaml --data-value-yaml branches="[my-string, 123]"
```
where values.yaml contains a `branches` key.

**Comment by peterfeifanchen** [comment]
Thanks!
