### ISSUE TITLE
Adding key/value pairs to attribute in YAML

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#197]
I couldn't get overlay to work If I want to overlay key/values onto an attribute say `annotations:` at the top level. I tried:

```
#@ def annotation(key, value):
annotations:
 #@overlay/append
 (@= key @): #@ value
#@ end
```

AND

```
#@ def annotation(key)_value):
annotations:
 #@overlay/append
 #@ key_value
#@ end
```

What is the correct way to do this? The first error I get was that 

```
Map item (key 'annotations') on line overlay.lib.yml:19: Expected map, but was <nil>
```
I think this is because in the left side, my `annotations: nil` initially but I would like to add to it as a map.

**Comment by peterfeifanchen** [comment]
Oh figured it out, you pass in a map and you don't even have to do the overlay.

**Comment by caniko** [comment]
> Oh figured it out, you pass in a map and you don't even have to do the overlay.

Can you paste your solution @peterfeifanchen?

**Comment by pivotaljohn** [comment]
@caniko , do you have a similar situation? Feel free to post an example here and we can help.
