### ISSUE TITLE
Overlaying maps with a different group of keys?

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#198]
Hi I was wondering since Append is only for lists, is there a way to merge maps together?

E.g.
```
annotations:
  some: value
```
and I would like to overlay `another: value` to create:
```
annotations:
 some: value
 another: value
```

**Comment by ewrenn8** [comment]
Hi @peterfeifanchen,

You will just need to add the `missing_ok=True` keyword arg to the key and ytt will know to add it if it doesn't exist, or override it if it does. Here is an example: https://get-ytt.io/#gist:https://gist.github.com/ewrenn8/fe60708eb3a7b35703c21d6155049131

Eli & Steven

**Comment by peterfeifanchen** [comment]
what would I do if the right map is a variable passed into the function?
```
#@ def annotation(key_value):
#@overlay/match missing_ok=True
annotations: 
  #@ for attribute in key_value:
  #@overlay/match missing_ok=True
  ???
  #@ end
#@ end
```

**Comment by cari-lynn** [comment]
Hey! You can use the template module for this. You will also need to set the `missing_ok=True` in the parent annotation, via `#@overlay/match-child-defaults`.

Here's an example: https://get-ytt.io/#gist:https://gist.github.com/pivotal-dean/109853fd6682bbe223c00935e03c9a31

**Comment by peterfeifanchen** [comment]
Yes that worked thanks!
