### ISSUE TITLE
Prettier way of loading data.values

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#199]
Right now in my starlark program I do:

```
load("@ytt:data", "data")

top = data.values
```

Is there a way to do this in load? Like:
```
load("@ytt:data", top = data.values)
```

**Comment by pivotaljohn** [comment]
If I _really_ want to keep it terse (in practice, less often than I originally thought), I'll sneak in a semi-colon and make the assignment:
```python
load("@ytt:data", "data"); d=data.values
```

The `load()` statement allows you to name values that are exported from the module and optionally manage the local identifier to bind to; but not whole expressions.

For more: https://github.com/google/starlark-go/blob/master/doc/spec.md#load-statements

**Comment by peterfeifanchen** [comment]
Thanks!
