### ISSUE TITLE
Conditional check on existence of a variable

### ISSUE THREAD

**Issue by m0un10** [k14s/ytt#202]
I've spend 3 hours googling, so it might be a good one for the docs.
I can't for the life of me work out how to check existence of a variable.

I thought this would work...
```
#@ if/end x.y != None:
foo: bar
```

But, I get something like
`struct has no .y field or method`

**Comment by ewrenn8** [comment]
Hey @m0un10,

You can use the hasattr() function. There is some more info in the [FAQ](https://github.com/k14s/ytt/blob/develop/docs/faq.md#how-do-i-check-if-a-key-is-set), but, I agree, a more observable spot in the docs would also help. We will get this added!

Eli

**Comment by m0un10** [comment]
Thank you so much for the prompt response! And nice to see it was actually in FAQ. My bad for missing that.
For what it is worth, the playground was amazingly helpful for getting started.
When I needed to loop across a map, that's when things got hard because it can't be done except for changing the data to be an array by moving the key into the object. The `hasattr()` function could be useful at the end of the `for` tutorial to highlight clearly that it exists for a common use case like this.

**Comment by ewrenn8** [comment]
@m0un10 

Thanks for the suggestion! I am unsure of your use case, but you may be able to use the [vals function](https://github.com/k14s/ytt/blob/develop/docs/lang-ref-yaml-fragment.md#yaml-map) to loop over a yamlfragment map.

Eli

**Comment by pivotaljohn** [comment]
Hey @m0un10!

FWIW, we also have a Slack channel in the Kubernetes slack: [#k14s](https://kubernetes.slack.com/archives/CH8KCCKA5). It's very welcoming and usually responsive.

+1 to the idea of turning up the volume on this bit of knowledge. 👍🏼
