### ISSUE TITLE
Ytt load files in parent directories

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#203]
My file structure is like this

common/rule.star
component/*.yml
component/branch/master/testplan.star

I tried to run `ytt -f component/branch/master -f component -f common` and `ytt -f testplan.star -f ../../ -f ../../../common/` but both gave me 

```
- cannot load rule.star: Expected to find file 'rule.star' (hint: only files included via -f flag are available)
    in <toplevel>
```

Is there not a way to do this? Or will it basically resort to symbolic links to deal with this?

**Comment by peterfeifanchen** [comment]
Ohhh, is it the order at which you feed in the directories that matters?

**Comment by StevenLocke** [comment]
Hi @peterfeifanchen 

ytt does allow this without needing to resort to symlinks :)

A key insight for the `load` command is that the first argument passed into it, the path for the file to load, is relative to where the caller is loaded.

We set up a similar example, with this directory structure:

```shell
$ tree
.
├── common
│   └── rule.star
└── component
    ├── branch
    │   └── master
    │       └── testplan.star
    ├── config.yml
    └── other.yml
```

where testplan.star is trying to load a function from rule.star:
```starlark
load("rule.star", "functionName")
```

You can take a look at the "virtual file system" that ytt operates over by passing the `--files-inspect` flag. For our example:
```shell
$ ytt -f component/branch/master -f component -f common --files-inspect
- testplan.star
- branch/master/testplan.star
- config.yml
- other.yml
- rule.star
```

Notice that `testplan.star` is loaded twice.  
The first time ytt runs `testplan.star`, its context is at the root level, which is the same location as `rule.star` and is therefore successful.
The error occurs in the second instance of the `testplan.star` file, i.e. `branch/master/testplan.star`. Note this context is not the root, but instead, two directories down. So, when the load call is made here, there is no sibling named `rule.star`. 

There are two ways to fix the issue:

1. Specify an absolute path in `testplan.star` (within that virtual filesystem). This means that both times the file gets run, the location of `rule.star` can be found.
```starlark
load("/rule.star", "functionName")
```
2. Avoid including the entirety of the `component` directory to prevent `testplan.star` from having that nested context. This may end up being pretty unwieldy, as you'd have to specify the entire contents of it manually, but would look something like:
```shell
$ ytt -f common -f component/branch/master -f component/config.yml -f component/other.yml
```

(If we run that above command with the `--files-inspect` flag, we see that `testplan.star` only gets loaded once, at the root level)

```
- rule.star
- testplan.star
- config.yml
- other.yml
```

**Comment by peterfeifanchen** [comment]
I see that explains it very well. Thank you!
