### ISSUE TITLE
ytt directives inside for/end loops

### ISSUE THREAD

**Issue by larsks** [k14s/ytt#207]
I wanted to do this:

```
#@ for/end host in hosts:
#@ short_host = host.split('.')[0]
- #@ short_host
```

But this fails with because I've got a ytt directive instead of a YAML node immediately following the `for/end`:

```
ytt: Error: Compiling YAML template 'kustomization.yml':
  Unexpected code at line kustomization.yml:9 after use of '*/end', expected YAML node
```

I can of course just rewrite it like this:

```
#@ for host in hosts:
#@ short_host = host.split('.')[0]
- #@ short_host
#@ end
```

But it would be nice if ytt directives in this situation didn't cause it to tail like that.

**Comment by cppforlife** [comment]
i believe the reason why we put that restriction was to avoid confusion for folks that thought /end applies to following line vs following YAML node.

**Comment by larsks** [comment]
That's fine. It's obviously not a big issue; I was mostly curious if this was expected (which I guess it is) or not. I'm going to go ahead and just close this issue. Thanks!
