### ISSUE TITLE
Calling ytt as a library in code

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#209]
Is it possible to create my own `TemplateOptions` (e.g., filling out RegularFilesSourceOpts and DataValuesFlags) and just call `func (o *TemplateOptions) Run() error` directly in code instead of executing ytt in bash?

https://github.com/k14s/ytt/blob/fc9b97d211e866adcb2b21a7cfa707784fc01b2c/pkg/cmd/template/cmd.go#L16

**Comment by cppforlife** [comment]
@peterfeifanchen we actually do something like that in our e2e tests here for example: https://github.com/k14s/ytt/blob/fc9b97d211e866adcb2b21a7cfa707784fc01b2c/pkg/cmd/template/cmd_overlays_test.go#L47-L59

generally i recommend to calling out to the binary (dont have to wrap it in bash though, just direct binary call) like ive done in github.com/k14s/kapp-controller and github..com/k14s/terraform-provider-k14s for the sake of simplicity, easier upgradability, more stable interface. if you describe your use case a bit more we might be able to provide more curated recommendation.

**Comment by peterfeifanchen** [comment]
Can you point me to how you did it in binary in kapp-controller and terraform? My use case is I have some files and some initial data values and rather than currently doing `os.Exec("ytt ...")` I would like to call the ytt code directly to compile the files. This way I can write test hermetically instead of relying on ytt being installed.

**Comment by cppforlife** [comment]
example above shows how to call ytt in code instead of calling the binary. 

kapp-controller and terraform both exec to the binary (similar to what you are doing): https://github.com/k14s/kapp-controller/blob/develop/pkg/template/ytt.go#L57-L60 (uses fs) and https://github.com/k14s/terraform-provider-k14s/blob/develop/pkg/ytt/ytt.go#L25-L28 (uses stdin to pass in additional config). 

ytt also has --bulk-in/--bulk-out flags to aid calling out to the binary without having to write out files to disk. e.g.

```bash
$ ytt --bulk-in '{"files":[{"name":"foo.yml", "data": "foo: true"}, {"name":"bar.yml", "data": "bar: #@ 123"}]}' --bulk-out
{"files":[{"name":"foo.yml","data":"foo: true\n"},{"name":"bar.yml","data":"bar: 123\n"}]}
```

**Comment by peterfeifanchen** [comment]
Is `data` in this case just unrestricted text? (e.g., it doesn't have to be yaml, l could write starlark functions in there also and pass in a x.star file as well)?

**Comment by pivotaljohn** [comment]
Yes, `data` is the contents of the file. So any file you're used to loading in to `ytt` on the command-line works equally well through the "bulk" interface.

**Comment by peterfeifanchen** [comment]
Is there a way to capture the output of ytt if I call it as a "library" instead of it going to a file in stdout?

**Comment by cari-lynn** [comment]
Yes, you can capture the output of ytt when calling it in code. We capture the output in this test as an example:

https://github.com/k14s/ytt/blob/fc9b97d211e866adcb2b21a7cfa707784fc01b2c/pkg/cmd/template/cmd_overlays_test.go#L56-L65

`RunWithFiles` returns a `TemplateOutput`, which contains `Files` that are the resulting templated output.

Does this capture the output you need?

**Comment by peterfeifanchen** [comment]
This worked for me thanks! Although I had to call `files.NewSortedFiles` on the files first!
