### ISSUE TITLE
Document the `template` module

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#215]
_edit: rewritten in Cohen-style User Story to be more precise_

**As a** Configuration Author
**I want** to learn of the behavior and intent of the `template` module
**So that** I can confidently include its functionality in my templates

---

### Scenario: Navigating for reference

**Given** I'm aware that there's this `template` module and want to learn more
**When** I step through the table of contents of the `ytt` docs
**Then** I quickly find a section clearly dedicated to specifying that module.

### Scenario: Searching from need

**Given** I'm trying to figure out how to insert a block of YAML in, say, the middle of a map
**Or** I'm trying to replace a single item with a collection of the same kind of item
**Or** I've seen use of this `template` module and wonder what it's all about
**When** I search in the `ytt` docs (using words like "template", "replace", "insert in")
**Then** I find a section clearly dedicated to specifying that module that answers my question.
**And** It's on the first page of search results

---
Suggestions:
- At the very least, it deserves a mention in the [ytt Library](https://github.com/k14s/ytt/blob/develop/docs/lang-ref-ytt.md) page, if not its own page.
- When documenting the function, consider [overlay.apply()](https://github.com/k14s/ytt/blob/develop/docs/lang-ref-ytt-overlay.md#overlayapply) exemplary.

**Comment by jcfj** [comment]
> (#212 being the latest example).

Isn't really. I saw the [example](https://get-ytt.io/#example:example-replace) with `template.replace` and deliberately removed it to find out what would break.

**Comment by pivotaljohn** [comment]
Apologies, @jcfj; didn't mean to mischaracterize your experience/experiment, there.

I over-indexed on having had prior conversations where the practitioner was unaware of the `template` module. I assumed that was true in your case.

This issue still stands as a need to be able to reference this module and make plain its intended use.
