### ISSUE TITLE
add assert.equals to @ytt:assert

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#218]
this would help folks write tests within ytt and not have implement equals themselves (like in cf-for-k8s: https://github.com/cloudfoundry/cf-for-k8s/blob/18b4f3f676a85e49e675120f5b720aab91ac3892/config/istio/gateway_test.star#L77-L81)

- [x] #555
- [x] document the `assert.equals()` function

**Comment by gcheadle-vmware** [comment]
Released in ytt v0.39.0
