### ISSUE TITLE
unit testing starlark code

### ISSUE THREAD

**Issue by peterfeifanchen** [k14s/ytt#224]
I have defined some starlark functions that output a list of yamlFragment tuples. I see that I can load starlark directly using the starlark-go compiler like ytt does and read its output:

https://github.com/k14s/ytt/blob/582ad9ca849559e5d75b680b1831105059a0e953/pkg/template/compiled_template_test.go

But, I was wondering where the yamlFragment starlark struct is defined? Is there a way to check the function name of the yamlFragment and its variables in an unit test?

**Comment by ewrenn8** [comment]
Hi @peterfeifanchen, could you explain your use case and what you are trying to achieve a bit more? Is it that you want to be able to make assertions about a yamlfragment returned from a function?

**Comment by peterfeifanchen** [comment]
So in my case I have a starlark function that erturns a list of yamlFragment tuples which come from an overlay file:

starlark file
```
def func1():
    changes += ( overlayfunc.DoSomething, )
    ...
    return -> [ (yamlfragment(*yamlmeta.Map),...), ....]
```

overlayfile
```
#@ DoSomething():
#! match something .... and edit
```

I would like to unit-test func1 (starlark). So far it seems I would have to call the starlark intepreter and feed the overlayfile and starlark file and then add a global like the case above to the starlark file:
```
def func1():
    changes += ( overlayfunc.DoSomething, )
    ...
    return -> [ (yamlfragment(*yamlmeta.Map),...), ....]
a = func1()
```
Get its output into Go and then assert that each yamlfragment is what I expect them to be. Is that correct? I am just not sure if there are examples on how to do this vs. me going into ytt to tease apart how the overlay #@ starlark files get combined with the starlark files and fed to the go-starlark interpreter.

**Comment by cppforlife** [comment]
@peterfeifanchen im not familiar with your setup and why/how you are using Go... have you considered to do your unit testing in ytt files e.g.

gateway_test.star

```
load("@ytt:assert", "assert")
load("gateway.lib.yml", "gateway")

def test_gateway_when_http_allowed():
  result = gateway("sys-domain.com", ["app-domain-1.com", "app-domain-2.com"], "sys-namespace", "work-namespace", False)
  http_servers = http_servers_in_gateway(result)
  assert_equals(1, len(http_servers))
  assert_equals(False, http_servers[0]["tls"]["httpsRedirect"])
end

def assert_equals(expected, actual):
  if actual != expected:
    assert.fail("Expected %s, but found %s" % (expected, actual))
  end
end
```

(related issue to add assert.equals as a first class method: https://github.com/k14s/ytt/issues/218)

**Comment by peterfeifanchen** [comment]
```
expected = overlay.func1(var1)
actual = overlay.func(var1)
assert_equals(expected, actual)
```
Is assert here a deep check where it only returns true if the function is the same and the parameters are the same? Or could you point me to how to deal with comparisons between yamlfragments and yamlfragment(*yamlMeta.Map)?

Also how does `test_gateway_when_http_allowed` get called? Is it that I would simply need to call `ytt -f gateway_test.star` and in the body of gateway_test.star I add:
```
...
test_gateway_when_http_allowed()
```

**Comment by peterfeifanchen** [comment]
I see here, yamlFragment comparisons are still yet to be implemented

https://github.com/k14s/ytt/blob/develop/pkg/yamltemplate/starlark_fragment.go#L52

And I am also unable to do a `dir(yamlFragment)` as that returns `[]`.  I see that there is a `Get` call implemented:

https://github.com/k14s/ytt/blob/develop/pkg/yamltemplate/starlark_fragment.go#L56

But I am not sure what the attribute keys are to look for to get the fragment's properties or how that is filled out given an overlay function

```
type Map struct {
  Metas []*Meta
  Items  []*MapItem
  Positions *filepos.Position

  annotations interface{}
```

This is an example of the toy one I am playing with:
rule_test.star
```
load("@ytt:assert", "assert")
load("overlay.lib.yml", "cron", "timeout")
load("rule.star", "singleton")

def assert_equals(expected, actual):
  if actual != expected:
    assert.fail("Expected {}, got {}".format(expected, actual))
  end 
end

def test_singleton():
  result = [ ( cron("a"), cron("b"), timeout("c") ) ] 
  got = singleton( cron("a"), cron("b"), timeout("c") )
  assert_equals(result, got)
end

test_singleton()
```
rule.star
```
def singleton( *params ):
    return [ tuple(params) ]
end
```
overlay.lib.yml
```
#@ def cron(str):
#@overlay/match missing_ok=True
cron: #@ str
#@ end


#@ def timeout(t):
#@overlay/match missing_ok=True
timeout: #@ t
#@ end
```

**Comment by cppforlife** [comment]
> Also how does test_gateway_when_http_allowed get called? Is it that I would simply need to call ytt -f gateway_test.star and in the body of gateway_test.star I add...

that's right you would call test_* function yourself.

> And I am also unable to do a dir(yamlFragment) as that returns []. I see that there is a Get call implemented:

yamlfrag doesnt implement any methods today. you can however call `yaml.encode(arg)` where arg is yamlfrag to get a string representation. do note that it will not retain annotations on the nodes when serializing it to YAML.

may be you can expand on why you are trying compare overlays?

**Comment by peterfeifanchen** [comment]
> yamlfrag doesnt implement any methods today. you can however call yaml.encode(arg) where arg is yamlfrag to get a string representation. do note that it will not retain annotations on the nodes when serializing it to YAML.

what is the library I load to use `yaml` in starlark?

So I am using ytt to template a base configuration file with the different combinations that it can have. Instead of doing this in a yml file where the user would have to write in #@ starlark (hard to read and have them do since you can't new line indent), I provide them with a starlark function that accumulates yamlFragments which a generator.yml file then reads over to template the base configuration in the way defined by a tuple of yamlFragments. This way they can write stuff like:

Starlark <- where user would express the cases
```
cases += starlark_func( crisscross( a, b, c, d ) )
```
YAML
```
#@ for case in cases:
#@    overlay.apply( base, *case)
```

Hence I kind of want to test `crisscross` and `starlark_func` individually (if I can...ideally but its not terrible if I can't)

**Comment by peterfeifanchen** [comment]
Oh never mind found the library!

**Comment by pivotaljohn** [comment]
How's all this going @peterfeifanchen ?!

**Comment by peterfeifanchen** [comment]
Ahh thanks! I think this is what I needed. Everything's resolved.

**Comment by pivotaljohn** [comment]
Terrific, @peterfeifanchen!

We'd love to hear about your adventures in unit testing. Many of the k14s maintainers have worked in shops where Test-Driven Development was table-steaks. We'd enjoy hearing what you are finding hard, easy, useful, etc.

**Comment by peterfeifanchen** [comment]
We are writing the tests now, but one thing that seems interesting is for the overlay.apply function, is there a way to create an empty yaml fragment? This would be useful to test each overlay specifically in the most minimal manner, but we get the error

`overlay.apply: Expected map, but was <nil>`

when we try

```
#@ def base():
#@ return
```

**Comment by cari-lynn** [comment]
Thanks for sharing how things are going! You may be running into [this issue](https://github.com/k14s/ytt/issues/108). If the map you are trying to overlay has a nil value, overlaying it results in a type mismatch.  A way around this is to add a value to it.

Does this fit with your implementation? If it doesn't solve your problem it would be helpful for debugging if you share more code on how you are overlaying in the test.

**Comment by peterfeifanchen** [comment]
Ahh yes that's the problem we are running into. We ended up just putting something in it. That's fine to do for us, but was just curious if we could have a nil or "" map object, but it seems that issue is still open. Thanks!

**Comment by peterfeifanchen** [comment]
@pivotaljohn I think having the equal operator on the yamlFragments would help make the testing easier. But for now we are doing yaml encode and comparing it to what we expect it would be instead. It's a bit less legible since starlark deletes yaml spaces and new lines, so to get the same structure we have to add a bunch of '\n'.

And to incorporate that into Go, we sort of wrap a go unit test around our `*_test.star` files.
