### ISSUE TITLE
Automatically detect when a YAML file is a template or plain YAML (obviating the `--ignore-unknown-comments` flag)

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#232]
_Context: https://github.com/k14s/ytt/issues/14#issuecomment-726409172_

**I want to** provide supply a combination of plain YAML and ytt YAML templates
and have `ytt` automatically figure out which are `yaml-plain` and which are `yaml-template`
**so that** I can — without doing any extra work — a) easily include YAML from 3rd party sources; and b) get the full benefits of `ytt` ensuring my templates execute well

__

## Scenario: Mixed types of YAML files are correctly interpreted
**Given** at least one file that is plain YAML (e.g. includes standard YAML comments, `# `) and at least one file that is a valid `ytt` template (i.e. contains at least one annotation `#@`)
**When** I invoke `ytt` specifying those files with no additional flags
**Then** the output contains both the properly evaluated template output _and_ the plain YAML.

## Scenario: Using (now) deprecated flag
**When** I invoke `ytt` with the `--help` flag
**Then** I see that the `--ignore-unknown-comments` flag is deprecated.

**When** I invoke `ytt` with the `--ignore-unknown-comments`
**Then** I see a warning (on standard error) that informs me that this flag is deprecated.

**When** I search the docs with keywords like "yaml-plain", "yaml-template", "detection", or "comments" 
**Or** I navigate to sections that describe the "file mark" feature or that describe how templates are processed
**Then** I learn that `ytt` differentiates between "plain YAML" and "YAML templates", and how this behavior can be overiden.

**Comment by jessehu** [comment]
Thanks @pivotaljohn. 
1) So if the yaml file doesn't contain '#@' or marked as "yaml-plain", ytt will treat it as a plain yaml file and will not throw error if there is '# ' in the yaml file, even if --ignore-unknown-comments is not specified (by default) for ytt?
2) `--ignore-unknown-comments is deprecated` means there will be no --ignore-unknown-comments option in future. So in future will ytt throw error if there is '# ' in the non-plain-yaml file?

**Comment by pivotaljohn** [comment]
> Thanks @pivotaljohn 

🖖🏼 

> 1. So if the yaml file doesn't contain '#@' or marked as "yaml-plain", ytt will treat it as a plain yaml file and will not throw error if there is '# ' in the yaml file, even if --ignore-unknown-comments is not specified (by default) for ytt?

Exactly. 👍🏼 

> 2. `--ignore-unknown-comments is deprecated` means there will be no --ignore-unknown-comments option in future. So in future will ytt throw error if there is '# ' in the non-plain-yaml file?

- `ytt` will continue to report an error if a YAML template contains a plain comment (the message specified in #226, or an improvement).
- the `--ignore-unknown-comments` flag will _eventually_ be removed. We can be quite patient about it given that we'll be giving a deprecation warning as part of this work. At the very least, it must be gone from any documentation of products that integrate/use `ytt`.

**Comment by jessehu** [comment]
Works perfect! 👍
