### ISSUE TITLE
"Full Screen" on Playground does not expand

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#272]
**What steps did you take:**
1. https://carvel.dev/ytt#playground
2. Click on the "Full Screen" button

**What happened:**
- 👍 other elements on the page went away
- 👎 the size of the content area did not change

**What did you expect:**
That the content area would expand to fill the document/window.

**Comment by StevenLocke** [comment]
Works for me! What's that? Your monitor is wider than 980px? Preposterous :D

Reproduced on my machine. Agreed, we should allow the content to grow.

Looks like we're limiting the width in the `.content .playground-wrapper` css. It's hopefully easy enough to add a more specific selector (with the `playground-expanded` class incorporated) to change the width.
