### ISSUE TITLE
Schemas v1 — Typing and Defaulting

### ISSUE THREAD

**Issue by gcheadle-vmware** [k14s/ytt#283]
# Why?
Configuration Authors want to:
- provide an enforced and documented API to _their_ users in the form of data values _so that they can focus the bulk of their attention at considering their needs rather than wrestling with the tool_.

In order to experience that, Configuration Consumers want to:
- when they make a mistake in providing values, they get error messages that precisely identify where and how to fix them;
- when common defaults would fit their needs, automatically receive those defaults in their configuration.

# Context
- Schema Design Document: https://hackmd.io/pODV3wzbT56MbQTxbQOOKQ
- [CF For K8s Schema Requirements](https://docs.google.com/document/d/1q4QyaElEX3KtIeGjwPmZpxsJpgsxin9sx7M0T4qBiW0/edit#heading=h.ir9gwkhzifm1)

# First Product Increment (MVP)

- **structure-checking** — when an entry in a data values file does not conform the the schema (e.g. names a `key` not defined in the schema), ytt reports an error
- **defaulting** — when when a data values input does not contain a key, the corresponding default value from the schema is substituted in.
- **type-checking** — when a leaf-level entry in a data values file has a type that does not match that specified in the schema, ytt reports an error.

**Comment by aaronshurley** [comment]
- [x] when we cut this release, ensure that we include docs changes from https://github.com/vmware-tanzu/carvel.dev/pull/49

**Comment by aaronshurley** [comment]
Closing this issue as this epic has been completed.
