### ISSUE TITLE
Document experimental Schema feature

### ISSUE THREAD

**Issue by gcheadle-vmware** [k14s/ytt#284]
## Story

**As a** Configuration Author, interested in learning how to kick the tires on the Schema feature
**I want** documentation that introduces me to the features, when I'd want to use them, and how.
**So that** I can very quickly assess how well it is tracking to my needs.

## Acceptance Criteria

**Given** I have an interest in trying out what schema features exist
**When** I review the `ytt` docs
**Then** I learn
- how to enable schemas (for now)
- how I can quickly see schemas in action
- how I can migrate from using Data Values for implicit schema to Schemas
- detailed syntax of each implemented feature
  - all docs describing annotations must have the same format (see [Overlay annotations](https://carvel.dev/ytt/docs/latest/lang-ref-ytt-overlay/#overlay-annotations) as a default)

## Notes

Documentation could include:

1. an introduction to the Schema feature that includes:
    -  the problem(s) it solves  (from the end-users' perspective)
    - _what_ a "schema" looks like in `ytt`
    - a simple example
1. a reference that:
    - define terms
    - enumerates all supported types
    - lists and details all implemented annotations
1. a guide showing:
    - how schema is declared (i.e. marking a doc as schema)
    - how schema is defined (i.e. how types are inferred)
    - how `ytt` uses schema in its workflow

Consider:
- find a wealth of documentation-like text in the [Schema Proposal/Spec](https://hackmd.io/pODV3wzbT56MbQTxbQOOKQ)
- indicate that when the `--enable-experiment-schema` flag is omitted, then they'll get a warning _and_ any Schema documents are removed from the run.
- Arrays/Array Items having special behaviors and tend to be a source of confusion; consider given these types special treatment (e.g. a separation section detailing all the aspects that are different).
- Make clear that overlaying schema needs to be additive only. If you change an existing data value in a schema, you risk breaking the API contract between the schema and the templates that rely on it.

**Comment by cppforlife** [comment]
given the size and impact of this feature, it's probably worth keeping this in a isolated area within docs until it's ready to be used by everyone.

**Comment by pivotaljohn** [comment]
Great work, @cari-lynn! and what timing: was requested today: https://kubernetes.slack.com/archives/CH8KCCKA5/p1622657376278100
