### ISSUE TITLE
[lang] Allow computed expressions as keys

### ISSUE THREAD

**Issue by rcls** [k14s/ytt#29]
It'd be nice to allow ytt expressions in the keys of a yaml dict. E.g., see the file below, the direct attempt fails miserably, to get the example to work I have to jump through hoops with functions and template.replace.
```
#! This doesn't work, but would be convenient

#@ for x in [1]:
? #@ "key" + str(x)
:
  - #@ x+1
  - #@ x+2
#@ end

---

#! This does work, but it's kinda clunky.

#@ load("@ytt:template", "template")

#@ def f(x):
- #@ x+1
- #@ x+2
#@ end

---

#@ for x in 1, 2, 3, 4:
_: #@ template.replace({ "key" + str(x) : f(x) })
#@ end

**Comment by cppforlife** [comment]
@rcls out of curiosity, is your use case mostly around keys that are strings?

**Comment by rcls** [comment]
> @rcls out of curiosity, is your use case mostly around keys that are strings?

Yes, I am only using strings as keys.

**Comment by cppforlife** [comment]
i could see us also adding following for common case of string keys:

```yaml
#@ for x in [1,2,3]:
(@= "key"+str(x) @): #@ x
#@ end
```

**Comment by laurentlb** [comment]
Another way to write your example: 
```
#@ data = 1, 2, 3, 4
--- #@ { "key" + str(x) : [x+1, x+2] for x in data }
```

But it gets clumsy if you want more things to the document.

**Comment by rcls** [comment]
(Thanks for working on this, it's a little thing that will make my life easier!)

**Comment by cppforlife** [comment]
fixed `@yaml/map-key-override` annotation for computed keys in 467c267

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/releases/tag/v0.17.0
