### ISSUE TITLE
`@schema/default` Annotation

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#295]
## @schema/default
**work is on ytt branch: schema-default**
Explicitly sets the default value of the annotated node.

```yaml
@schema/default value
```

- `value` (any except `function`) — the overriding default value.

Notes:
- `value` must be of the type of the annotated node.
- The type of a node is never inferred from the overriding default value.
- this annotation is the _only_ way to set a non-empty default value for arrays.

Narrative:
**As a** configuration author
**I want** to explicitly set a default value for a data value
**so that** I can specify default values for arrays

---

##  🍏  Set the default value 
**Given** a document, array item, or map item is annotated with `@schema/default <value>`
**And** the value is of the same type as the key below it
**When** I run `ytt` that includes that schema
**Then** that value shows up as the default for that array

## Scenario 1:  🍏  Set the default value of an int

```yaml
#! schema.yml
#@data/values-schema
---
#@schema/default 1
number: 0
```
```yaml
#! template.yml
#@ load("@ytt:data", "data")
---
output: #@ data.values.number
```

Then the result of `ytt -f schema.yml -f template.yml` is:
```yaml
---
output: 1
```

## Scenario 2: 🍏  Set the default value of an array

```yaml
#! schema.yml
#@data/values-schema
---
#@ def array_definition():
#@ return "this is the default value"
#@ end

#@schema/default [array_definition()]
the_array:
- this defines the type only
```
```yaml
#! template.yml
#@ load("@ytt:data", "data")
---
output: #@ data.values.the_array
```

Then the result of `ytt -f schema.yml -f template.yml` is:
```yaml
---
output: 
- this is the default value
```

## Scenario 3: 🟥 Keyword argument(s) of incorrect format
**Given** a document, array item, or map item is annotated with `@schema/default` with any other keyword argument (kwarg) except a value of the same type that is defined inline for arrays or maps
**When** I run `ytt` that includes that schema
**Then** I see an error message which includes line numbers to help point to where the error is, alongside a helpful message that describes the problem and how to fix it (unknown kwarg, fix by removing or using the only currently supported on, any)

More examples in the [original ytt schema doc](https://hackmd.io/pODV3wzbT56MbQTxbQOOKQ#schemadefault)

Notes: 
* Documentation should be included as part of this issue

**Comment by cari-lynn** [comment]
Available in [v0.38.0](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.38.0)
