### ISSUE TITLE
Library?

### ISSUE THREAD

**Issue by kenahoo** [k14s/ytt#304]
I'm having a little trouble getting started using YTT - is there a Python library that allows a developer to process a YAML file with YTT?  That's what I'd ultimately like to be able to do if possible.

I see that there's an executable binary at https://github.com/vmware-tanzu/carvel-ytt/releases that I can download for command-line processing, but the binary isn't signed so MacOS doesn't want to let it be launched.  I'm a little hesitant myself to launch a binary downloaded like that, so I also downloaded the source package, but I'm not finding any build instructions.

I tried joining https://kubernetes.slack.com/?redir=%2Farchives%2FCH8KCCKA5 as recommended at https://carvel.dev/community/ to ask this question, but it seems I need a `@get-an-invite-at.slack.kubernetes.io` email address to join?

**Comment by joaopapereira** [comment]
Hello @kenahoo sorry to hear that, 
Let me try to help you in steps.

Access slack, you should be able to create an account in Kubernetes Slack(where our channel is) by going https://slack.k8s.io/ and you will be asked for your email address that will be used to send you the invitation to register. From there you should be all set and can join the #carvel channel

MacOS signing, unfortunately at this point we do not have an Apple Developer ID so we are not signing our binaries. If you do not want to use the unsigned binary compiling `ytt` in your machine, for now, will be the way to go.

Building from the source code, you are right we do lack that information in this particular repository and we should definitely solve that. To create the binaries you can run `./hack/build.sh` and it will build you the `ytt` binary.

Now to your main question
> is there a Python library that allows a developer to process a YAML file with YTT?

`ytt` is an application that is meant to be used in the command line. This is a GO application and we do not have plans to provide it as a library in the short term. The best way to use `ytt` with python would be to call the binary externally using subprocess, or something similar.

Let us know if the above helped

**Comment by kenahoo** [comment]
Thanks @joaopapereira , very helpful.  For now I'll just do some exploration using my locally-built `ytt` binary and figure out the best ways to integrate it into the larger landscape if we choose to use it.

**Comment by joaopapereira** [comment]
I am happy it was helpful. 
Going to close the issue for now, but feel free to reopen it if you have more questions.
