### ISSUE TITLE
Better error message when @data/values is on non-documents

### ISSUE THREAD

**Issue by dprotaso** [k14s/ytt#325]
**Describe the problem/challenge you have**
ytt is spitting out the error:
```
ytt: Error: Expected YAML document to be annotated with data/values but was *yamlmeta.MapItem
```

But I have no idea what what file/line it is complaining about

**Comment by gcheadle-vmware** [comment]
Hey @dprotaso,

Thanks for reaching out! That error message could definitely use more information regarding the context of the error. 

We are curious what command and files you used, that way we could get a better understanding of how this error happened. We are guessing that you wanted to provide a data values file but did not annotate the top of the file with `#@data/values`.

cc @DennisDenuto

**Comment by dprotaso** [comment]
```
#@data/values
test: hello
```

`ytt -f` that file

**Comment by gcheadle-vmware** [comment]
Thank you for the additional context. We can certainly run a story to improve this error message. 

A Data Values file is a YAML document annotated with `#@data/values`. So you'll need to add a document start "`---`" under the `#@data/values` annotation.

Proposed Story:
### Problem
When files are annotated using `@data/values`, but no document start is provided, `ytt` errors with an unspecific error message:  `Expected YAML document to be annotated with data/values but was *yamlmeta.MapItem`. This error message can be confusing because it does not refer to a line number nor a file name. 

### Acceptance Criteria
given `values.yml`:
```
#@data/values 

some-val: val
```
when I run `ytt -f values.yml`, I should see a clear error message telling me:
1. What went wrong
2. Where it went wrong
3. hint on how to fix the problem (nice to have)

Feel free to add a ":+1:" reaction to this comment if this story looks good to you.

**Comment by pivotaljohn** [comment]
I agree with this diagnosis...

... and I'd even go further:
- direct the user's attention to _where_, first — mention the spot where error occurred at the beginning
- we're leaking details that are irrelevant to the user (they don't care and might be confused by mention of the Go package in which the struct lives); let's coalesce all our communication around a ubiquitous language
- omitting the `@` prefix misses an opportunity to improve visual parsing.

Something _like_,

```console
Found @data/values on Map Item (values.yml:3); only Documents can be annotated with @data/values
```

**Comment by aaronshurley** [comment]
This improvement makes sense. We're going to move this to the Unprioritized Backlog for right now so that we can group it with similar work. Contributions are welcome :)

**Comment by pivotaljohn** [comment]
Getting to actionable acceptance criteria:
- [x] identify all the places where this category of error occurs (i.e. anywhere an annotation is detected on a node type that doesn't support it).
- [x] establish a general format for such error messages that incorporate the insights shared in this issue.
- [ ] edit the description of this issue, turning it into a clear story to revise this class of error messages. (please preserve the original report a la #400).

**Comment by gcheadle-vmware** [comment]
## Story
There are certain annotations in ytt that are allowed only when placed on a specific type of the node. Currently, these annotations are:
- annotations that apply only to documents: `@data/values` and `@data/values-schema`
- annotations that apply only to array items:`@overlay/insert`

The goal of this story is to establish a consistent error scheme when one of these annotations is found on a node type that does not support that annotation.
The generalized error message to report this kind of error:
```
Found @<ANNOTATION> on <AST NODE> (<FILE NAME>:<LINE NUM>); <HINT>
```

### Scenario 1: Annotations that only work on docs (`---`)

**@data/values**
**Given**
```
#@data/values 

some-val: val
```
**Undesired Result**
```
$ ytt -f .
ytt: Error: Expected YAML document to be annotated with data/values but was *yamlmeta.MapItem
```
**Desired Result**
```
ytt: Error: Found @data/values on Map Item (values.yml:3); only Documents (---) can be annotated with @data/values
```
---
@**data**/values-schema
**Given**
```
#@data/values-schema

foo: 4
```
**Undesired** Result
```
$ ytt -f . --enable-experiment-schema
ytt: Error: Expected YAML document to be annotated with data/values but was *yamlmeta.MapItem
```
**Desired** Result
```
ytt: Error: Found @data/values-schema on Map Item (values.yml:3); only Documents (---) can be annotated with @data/values
```

### Scenario 2: Annotations that only work on Arrays
**@overlay/insert**
**Given**
```
#@ load("@ytt:overlay", "overlay")
---
metadata:
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: 2000
    nginx.ingress.kubernetes.io/enable-access-log: "true"

#@overlay/match by=overlay.all
---
metadata:
  annotations:
    #@overlay/insert
    ingress.kubernetes.io/rewrite-target: "wow"
```
**Undesired Result**
```
$ ytt -f .
ytt: Error: Overlaying (in following order: config.yml):
  Document on line config.yml:9: Map item (key 'metadata') on line config.yml:10:
    Map item (key 'annotations') on line config.yml:11:
      Map item (key 'ingress.kubernetes.io/rewrite-target') on line config.yml:13:
        Overlay op overlay/insert is not supported on map item
```
**Desired Result**
```
ytt: Error: Overlaying (in following order: config.yml):
  Document on line config.yml:9: Map item (key 'metadata') on line config.yml:10:
    Map item (key 'annotations') on line config.yml:11:
      Map item (key 'ingress.kubernetes.io/rewrite-target') on line config.yml:13:
        Found @overlay/insert on Map Item (config.yml:13); only Array items can be annotated with @overlay/insert
```

---
**Note:** We're not planning to address the below scenario in this story but we'll keep this information here as context to consider in the future.
**@overlay/append (depreciated)**
**Given**
```
#@ load("@ytt:overlay", "overlay")
---
metadata:
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: 2000
    nginx.ingress.kubernetes.io/enable-access-log: "true"

#@overlay/match by=overlay.all
---
metadata:
  annotations:
    #@overlay/append
    ingress.kubernetes.io/rewrite-target: "wow"
```
**Undesired Result**
```
$ ytt -f .
ytt: Error: Overlaying (in following order: config.yml):
  Document on line config.yml:9: Map item (key 'metadata') on line config.yml:10:
    Map item (key 'annotations') on line config.yml:11:
      Map item (key 'ingress.kubernetes.io/rewrite-target') on line config.yml:13:
        Overlay op overlay/append is not supported on map item
```
**Desired Result**
```
ytt: Error: Overlaying (in following order: config.yml):
  Document on line config.yml:9: Map item (key 'metadata') on line config.yml:10:
    Map item (key 'annotations') on line config.yml:11:
      Map item (key 'ingress.kubernetes.io/rewrite-target') on line config.yml:13:
        Found @overlay/append on Map Item (config.yml:13); only Array items can be annotated with @overlay/append
```

**Comment by pivotaljohn** [comment]
Thanks for the detailed acceptance criteria, @gcheadle-vmware. 👍🏻  ==> "ready for dev"

**Comment by pivotaljohn** [comment]
Reported again: https://kubernetes.slack.com/archives/CH8KCCKA5/p1634838859014100 .
