### ISSUE TITLE
❔ Generate (non-yaml) text file from yaml files examples ❔ 

### ISSUE THREAD

**Issue by adriens** [k14s/ytt#331]
# Context

On a current project, I have some `yaml ` files but I need to generate a text file for Jenkins tha may look like this : 

```
@Library('opt-shared-libraries') _

def towerEnvVar = '''{
                     "LOG_FILE": "/var/log/thelog.log",
                     "LOG_FILE_JSON" : "/var/log/log.json",
                     "MAX_HISTORY" : "2",
                     "MAX_FILE_SIZE" : "1GB",
                     "TOTAL_SIZE_CAP" : "100GB",
                     "ACTUATOR_OTRS_JIRA_URL": "https://any.url",
                     "JIRA_PAGE_SIZE": "5000"
                }'''.replace("\"", "\\\"").replace("\n", "")
```

I've run some samples but I could not achieve to generate a non `yaml` file : is it possible to use `ytt` to read multiple `yaml` files to get a (**non-yaml**) text file as ouput ? I would use `ytt` to load datas as parameters.

Thank you in advance for any help.

**Comment by adriens** [comment]
Is there a way we can force `ytt` not to check that output is `yaml` ?

`{"errors":"Unmarshaling YAML template 'values.yml': yaml: line 3: did not find expected \u003cdocument start\u003e"}`

**Comment by StevenLocke** [comment]
I think ytt may not be the right tool for this job. It's designed for structured content, YAML, JSON, etc. which gives ytt the ability to annotate, modify, and insert/replace nodes in a tree.

Can you provide an example of the files and command you'd hope would produce your desired output? What sort of constraints are you working under?

**Comment by adriens** [comment]
Hi @StevenLocke , first, thanks for your feedback.

I intend to produce a `JenkinsFile` as for now it's manually produced by colleagues and I'd like to automate its production based on input `yaml` files.... and I did not want to use `sed` command.

Please find below an output sample : 

```@Library('opt-shared-libraries') _

def towerEnvVar = '''{
                     "LOG_FILE": "/var/log/app01-actuator-otrs-jira/actuator-otrs-jira.log",
                     "LOG_FILE_JSON" : "/var/log/app01-actuator-otrs-jira/actuator-otrs-jira.json",
                     "MAX_HISTORY" : "2",
                     "MAX_FILE_SIZE" : "1GB",
                     "TOTAL_SIZE_CAP" : "100GB",
                     "ACTUATOR_OTRS_JIRA_URL": "https://actuator-otrs-jira-int",
                     "JIRA_PAGE_SIZE": "5000"
                }'''.replace("\"", "\\\"").replace("\n", "")


//Utilisation d'une closure pour résoudre warUrl au runtime
def towerValue = { warUrl -> """{
                              "extra_vars": {
                                "self_war_url": "${warUrl}",
                                "self_environment":  "",
                                "self_drop_indices": "Non",
                                "self_drop_database": "Non"
                              }
                            }""" }

optBackendAndBatchBuild ANSIBLE_ID: "672", GRADLE_TOOL: "gradle-5.6.2", towerVars : towerValue
```

My goal is to slowl automate this part and also to introduce `ytt` in our stack.

Hopefully my answer fits your question.

I was maye thinking of a "brute" mode where outputs are not checked.

Maybe shoud I rather use an `xsl` or any other automation tool I coud embed in any CI.

**Comment by adriens** [comment]
Should I rather use [gomplate](https://gomplate.ca/) or [mustache](http://mustache.github.io/) ?

**Comment by cppforlife** [comment]
> is it possible to use ytt to read multiple yaml files to get a (non-yaml) text file as ouput

@StevenLocke is right that ytt is really centered around data structure transformation in YAML; however, we do offer text templating as a feature that's occasionally needed. this example: https://carvel.dev/ytt/#example:example-k8s-helm-ish produces NOTES.txt for example via text templating (ytt interprets .txt extension in a special way). do note that ytt does not include text file result in stdout, so you would have to use --output-files flag to write it out to a file system.

**Comment by adriens** [comment]
Ok, thanks a lot @cppforlife , this answer my question.

I'm having a closer look at [gomplate](https://docs.gomplate.ca/usage/) to generate not-yaml content.

Thanks a lot guys for your kind feedbacks. 🙏
