### ISSUE TITLE
Type Check Command Line Data Values

### ISSUE THREAD

**Issue by gcheadle-vmware** [k14s/ytt#333]
**As a** Configuration Consumer using a [data values flag](https://carvel.dev/ytt/docs/latest/ytt-data-values/#overriding-data-values-via-command-line-flags)
**I want** the data values provided from the command line to be type checked against the schema,
**so that** when I provide a mistyped command line data value, I get specific, clear, and actionable feedback.

---

### Scenario 1: Schema-Conforming Command Line Data Value
Given ytt input with command line data value (always read in as string type) which conforms to the schema
And a schema file with the schema enabled flag turned on
When I invoke ytt 
Then those data values are reflected in the evaluation of the template
*Setup:*
```
#! template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```

```
#! schema.yml
#@schema/match data_values=True
---
foo: bar
```
*Command:*
```
$ ytt -f template.yml -f schema.yml --enable-experiment-schema --data-value=foo=myVal
foo: myVal
```

---

### Scenario 2: Schema-Non-Conforming Command Line Data Value
Given ytt input that has command line data value that is mistyped
And a schema file with the schema enable flag turned on
When I invoke ytt 
Then the type mismatch between the data value and schema is reflected in the error message
*Setup:*
```
#! template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```

```
#! schema.yml
#@schema/match data_values=True
---
foo: 7
```
*Command:*
```
$ ytt -f template.yml -f schema.yml --enable-experiment-schema --data-value=foo=42
Overlaying additional data values on top of "data values from files (marked as @data/values):
key 'foo' (kv arg) | foo: 42
                   |
                   | TYPE MISMATCH - the value of this item is not what schema expected:
                   |      found: string
                   |   expected: integer (by schema.yml:4)
```
Nice to have: error could point out that using `--data-value` flag parses value as string by default.

**However** when I invoke ytt using the `--data-value-yaml` flag
Then those data values are reflected in the evaluation of the template
*Command:*
```
$ ytt -f template.yml -f schema.yml --enable-experiment-schema --data-value-yaml=foo=42
foo: 42
```
---

### Scenario 3: Schema-Non-Existing Command Line Data Value
Given ytt input that has command line data value that is a new key
And a schema file with the schema enable flag turned on
When I invoke ytt 
Then the unexpected key not defined in the schema is reflected in the error message
*Setup:*
```
#! template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```

```
#! schema.yml
#@schema/match data_values=True
---
foo: hello
```
*Command:*
```
$ ytt -f template.yml -f schema.yml --enable-experiment-schema --data-value=key_doesnt_exist=myVal
key 'key_doesnt_exist' (kv arg) | key_doesnt_exist: 7
                  |
                  | UNEXPECTED KEY - the key of this item was not found in the schema's corresponding map:
                  |      found: key_doesnt_exist
                  |   expected: (a key defined in map) (by schema.yml:4)
                  |   (hint: declare data values in schema and override them in a data values document)`
```

---
### Scenario 4: Schema-Conforming Command Line Data Value in library
Given ytt input that includes a private library
And that private library contains schema
And a data values command line argument targeting the private library that conforms to schema
When I invoke ytt 
Then those data values are reflected in the evaluation of the private library
```
├── _ytt_lib
│   └── lib
│       ├── schema.yml
│       └── template.yml
├── root.yml
```
```
#! lib/schema.yml
#@schema/match data_values=True
---
foo: bar
```
```
#! lib/template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```
```
#! root.yml
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
--- #@ template.replace(library.get("lib").eval())
```
```
$ ytt -f . --enable-experiment-schema --data-value=@lib:foo=myVal
foo: myVal
````
---
### Scenario 5: Schema-Non-Conforming Command Line Data Value in library
Given ytt input that includes a private library
And that private library contains schema
And a data values command line argument targeting the private library that does not conform to schema
When I invoke ytt 
Then the type mismatch between the data value and schema is reflected in the error message
*Setup:*
```
├── _ytt_lib
│   └── lib
│       ├── schema.yml
│       └── template.yml
├── root.yml
```
```
#! lib/schema.yml
#@schema/match data_values=True
---
foo: 7
```
```
#! lib/template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```
```
#! root.yml
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
--- #@ template.replace(library.get("lib").eval())
```
*Command:*
```
$ ytt -f . --enable-experiment-schema --data-value=@lib:foo=42
ytt: Error:
- library.eval: Evaluating library 'lib':
    in <toplevel>
      root.yml:3 | --- #@ template.replace(library.get("lib").eval())
    reason:
Overlaying additional data values on top of "data values from files (marked as @data/values):
key 'foo' (kv arg) | foo: 42
                     |
                     | TYPE MISMATCH - the value of this item is not what schema expected:
                     |      found: string
                     |   expected: integer (by schema.yml:4)
```

Nice to have: error could point out that using `--data-value` flag parses value as string by default.

**However** when I invoke ytt using the `--data-value-yaml` flag
Then those data values are reflected in the evaluation of the template
*Command:*
```
$ ytt -f template.yml -f schema.yml --enable-experiment-schema --data-value-yaml=@lib:foo=42
foo: 42
```
---
### Scenario 6: Schema-Non-Existing Command Line Data Value in library
Given ytt input that includes a private library
And that private library contains schema
And a data values command line argument targeting the private library whose key does not exist in schema
When I invoke ytt 
Then the the unexpected key not defined in the library's schema is reflected in the error message
*Setup:*
```
├── _ytt_lib
│   └── fooy
│       ├── schema.yml
│       └── template.yml
├── root.yml
```
```
#! fooy/schema.yml
#@schema/match data_values=True
---
foo: hello
```
```
#! fooy/template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```
```
#! root.yml
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
--- #@ template.replace(library.get("fooy").eval())
```
*Command:*
```
$ ytt -f . --enable-experiment-schema --data-value=@fooy:key_doesnt_exist=7
ytt: Error:
- library.eval: Evaluating library 'fooy':
    in <toplevel>
      root.yml:3 | --- #@ template.replace(library.get("fooy").eval())
    reason:
key 'key_doesnt_exist' (kv arg) | key_doesnt_exist: 7
                  |
                  | UNEXPECTED KEY - the key of this item was not found in the schema's corresponding map:
                  |      found: key_doesnt_exist
                  |   expected: (a key defined in map) (by schema.yml:4)
                  |   (hint: declare data values in schema and override them in a data values document)`
```

**Comment by cppforlife** [comment]
> I want the data values provided from the command line to be type checked against the schema,

currently --data-value field reads values as strings. is this issue going to add behaviour so that --data-values is smart enough to pick "how to" read a value. (ie parse as int when field type is int, parse as float when field type is float, etc.)?

**Comment by cari-lynn** [comment]
I think we would want to type check based on whatever type was input so for `--data-values` it would be type checking the input as strings, and for other flags like `--data-values-env-yaml` or `--data-value-yaml` where the input is yaml encoded, we could type check based on those yaml types. So I think we should change the acceptance criteria above to use the other flags instead. We could also add scenarios for all the possible flags.

**Comment by gcheadle-vmware** [comment]
Scenarios 3 and 6 are now on hold due to #344. Since command line data values are only meant to override existing keys, adding a key will cause an overlay error. In the context of schemas, I would expect adding a key will cause a schema error after the completion of #344.

**Comment by pivotaljohn** [comment]
Released; closing.
