### ISSUE TITLE
Explore: Support exporting OpenAPI from `ytt` Schema

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#338]
Questions
- what exactly will the user do to get the OpenAPI schema export?
- can we translate everything we say in `ytt` schema to OpenAPI? Do we need any more information to do so?

Acceptance Criteria
- there's a proposal on how this is done
- a set of stories covering the MVP of enabling this feature

**Comment by joaopapereira** [comment]
After this exploration, we create epic #357.
Going to close this issue.
