### ISSUE TITLE
arm64 architecture support

### ISSUE THREAD

**Issue by jmcshane** [k14s/ytt#345]
**Describe the problem/challenge you have**
Want to install `ytt` on arm64 without needing to bridge using Rosetta

**Describe the solution you'd like**
Multi-architecture build for `ytt` to support arm64 architecture

**Anything else you would like to add:**
Would love to install via arm64 homebrew

**Comment by joaopapereira** [comment]
Sounds like a good thing to have. Accepting the issue

**Comment by gcheadle-vmware** [comment]
> Would love to install via arm64 homebrew

@jmcshane the ytt arm64 binaries should now be available through our homebrew tap.
