### ISSUE TITLE
Load yaml strictly as data without interpretation

### ISSUE THREAD

**Issue by scothis** [k14s/ytt#35]
I'd like to be able to use ytt to apply overlays to semi-trusted yaml files. These files should not be compiled by ytt, but be matched/transformed by other templates. If the file contains a ytt directive, it should be ignored.

**Comment by cppforlife** [comment]
you should be able to use `--file-mark` flag to let ytt know that file should be interpreted as plain yaml. example:

```
ytt t -f examples/istio-v1.0.2/istio.yml --file-mark istio.yml:type=yaml-plain -f examples/istio-v1.0.2/cluster-ip-ingressgw.yml
```

(from https://github.com/k14s/kapp/tree/355ab4c6e8bace302110c53a2b7eddaca139f357/examples/istio-v1.0.2)

**Comment by cppforlife** [comment]
also note that files paths used in file-mark are relative. e.g.

```
$ ytt -f examples/istio-v1.0.2/ --files-inspect
README.md
cluster-ip-ingressgw.yml
config.yml
istio.yml
patches.yml
```

**Comment by cppforlife** [comment]
it appears that --file-mark solution was not quite there for text templates in strings. fix added here: https://github.com/k14s/ytt/commit/26156e1b887feff7c2f4ca9624c11279c63628c3. will be publishing release shortly.

**Comment by cppforlife** [comment]
file-mark fixed in https://github.com/k14s/ytt/releases/tag/v0.14.0.
