### ISSUE TITLE
Schema checking data values panics on nested items against scalars

### ISSUE THREAD

**Issue by StevenLocke** [k14s/ytt#351]
**What steps did you take:**
```yaml
#! files/schema.yml

#@schema/match data_values=True
---
array: [true]
```

```yaml
#! files/dv.yml

#@data/values
---
array: [ [1] ]
```

```yaml
#! files/conf.yml

#@ load("@ytt:data", "data")

vals: #@ data.values
```

`$ ytt -f files/ --enable-experiment-schema`

(The important part is that array[0] in the schema is a scalar, and a map/array in the data values.)

**What happened:**
Panic! 

```
panic: Attempt to assign a type to a scalar. (scalars are not nodes in the AST) m=&schema.ScalarType{Value:false, Position:(*filepos.Position)(0xc0001c5cb0)} ; typeable=&yamlmeta.Array{Type:yamlmeta.Type(nil), Metas:[]*yamlmeta.Meta(nil), Items:[]*yamlmeta.ArrayItem{(*yamlmeta.ArrayItem)(0xc000227c20)}, Position:(*filepos.Position)(0xc000203500), annotations:interface {}(nil)}
```

**What did you expect:**
I expected a nice schema error message, something along the lines of:

```
data_values.yml:5 | array: [ [1] ]
                  |
                  | TYPE MISMATCH - the value of this item is not what schema expected:
                  |      found: array
                  |   expected: boolean (by schema.yml:5)
```

**Anything else you would like to add:**
The actual panic comes from `func (m *ScalarType) AssignTypeTo(...)`.

**Environment:**

- ytt version (use `ytt --version`): 0.31.0
- OS (e.g. from `/etc/os-release`): MacOS

**Comment by pivotaljohn** [comment]
Shipped with [v0.33.0](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.33.0).
