### ISSUE TITLE
OpenAPI Document Generation

### ISSUE THREAD

**Issue by joaopapereira** [k14s/ytt#357]
## Generate OpenAPI Document from `ytt` Data Values Schema

Proposal for this epic [here](https://github.com/vmware-tanzu/carvel/pull/198)

### Description

Enable `ytt` to generate an OpenAPI Document that can be processed by components that use [OpenAPI][1] to validate the correctness of data files for a particular library of template in `ytt`

### Why

The decision of enabling `ytt` to generate an OpenAPI compatible Document was based on [request from our users](https://github.com/vmware-tanzu/carvel-ytt/issues/103). [OpenAPI][1] is a standard widely adopted that is used to validate JSON and YAML files. Another usage for OpenAPI can be found in Kubernetes
where it is used to define the Schema that a particular Custom Resource need to follow, [check this page for more information][2]

##### As a User When I am editing a data file for `ytt` template I want the IDE to provide feedback about the correctness of my YAML

Some IDE's support validation of YAML files using OpenAPI Schemas, given that `ytt` can generate a OpenAPI Schema from a `ytt` Data Values Schema, this information can be provided to the IDE, which in turn would be able to validate the YAML that the user is creating.

##### As a `ytt` Library creator I want to be able to easily generate documentation on the data values my consumers can use

There are proven tools that can be used to autogenerate documentation from OpenAPI, check [here](http://openapi.tools). Given that `ytt` can generate OpenAPI for a particular library, it would be possible to provide these files to one of the mentioned tools and would generate the documentation automatically.

##### As a User When I provide data to my Package Custom Resource I want the data to be checked against the Schema

When the User is using [kapp-controller](https://carvel-dev/kapp-controller), if a Package is created with `ytt` templates, it would be interesting to allow Kubernetes or other tools check the values provided by the user when creating a Package for any potential problem with these values. Given that Kubernetes supports OpenAPI, if `ytt` is able to generate an OpenAPI Schema the user can have their data checked sooner, providing an error when applying the Custom Resource.

#### Why not use OpenAPI directly in `ytt`?

The main reasons to create a new `ytt` Data Values Schema are the following

1. Allow implicit schema discovery

   `ytt` is able to infer the schema from the current Data Values files provided

1. Enable complex validations

   JSONSchema allows the user to do validation against length, max and min values, required fields, and others.
   Nevertheless, in some cases, the `ytt` users want to use the underlying starlark language to create more complex validations, like check if a field is present if another has a specific value (Due to OpenAPI limitations we would not be able to export these conditionals, which will make validation with OpenAPI not 100% accurate).

We believe that these points out heighten the burden of creating a new definition for a schema.

🚧 TO BE UPDATED 🚧 
## Phase 0
See the [Implementation Breakdown](https://github.com/vmware-tanzu/carvel/pull/198/files) in the proposal for more info

1. Create a flag to generate an OpenAPI Document `ytt -f schema.yml --data-values-schema-inspect -o openapi`

   In this phase, these will be implemented
    1. Create `#@schema/default` annotation
    1. Disallow use of `--data-values-schema-inspect` without `-o` flag
    1. Export the type and default value of a key in a root library Data Values Schema (no library schemas)
    1. Export `@schema/nullable` annotations to the OpenAPI equivalent
    1. Export `@schema/any` annotations to the OpenAPI equivalent

## MVP-X

The assumption is that after getting to MVP-1 whenever a new validation is added to the `ytt` Schema, this would be
reflected in the OpenAPI generation

[1]: https://www.openapis.org/

[2]: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

**Comment by cari-lynn** [comment]
This epic has been completed, the follow-up epic is: https://github.com/vmware-tanzu/carvel-ytt/issues/512
