### ISSUE TITLE
Generate OpenAPI Schema for Maps

### ISSUE THREAD

**Issue by joaopapereira** [k14s/ytt#358]
**As a** Configuration Author
**I want** to generate OpenAPI Schema from my configuration
**so that** Configuration Consumers can know what configuration inputs are valid 

---

### :green_circle: Scenario 1: Convert Schema with Map and String to OpenAPI

**Given** the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
foo: some value
```

**When** I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
**Then** I should see on my screen
```yaml
---
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    type: object     # <- note maps have `type: object`
    additionalProperties: false # <- this indicates that no additional keys other than listed here are allowed 
    properties:
      foo:
        type: string
        default: some value
```
Note: The `type` is one of these [types](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#data-types) which also includes a subset of these [jsonschema types](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.4.2.1) 

#### ytt type to OpenAPI type conversion
| ytt | OpenAPI |
|--- |---|
| string | string |
| boolean | boolean |
| integer | integer |
| map | object |
| array | array (implemented in another story) |
| float | type: number, format: float |

---

### :green_circle: Scenario 2: Convert Schema with Map of Maps to OpenAPI Schema

**Given** the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
foo:
  int_key: 10
  bool_key: true
  false_key: false
  string_key: some text
  inner_map:
    float_key: 9.1
```

**When** I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
**Then** I should see on my screen
```yaml
---
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    type: object
    additionalProperties: false
    properties:
      foo:
        type: object 
        additionalProperties: false
        properties:
          int_key:
            type: integer
            default: 10
          bool_key:
            type: boolean
            default: true
          false_key:
            type: boolean
            default: false
          string_key:
            type: string
            default: some text
          inner_map:
            type: object
            additionalProperties: false
            properties:
              float_key:
                type: number
                format: float # note: floats have additional key for format
                default: 9.1
```

---

### :red_circle: Scenario 4: {} when no Schema file provided *Moved to other story (see comment)

**Given** the following file exists
```yaml
#! template.yml
---
foo: some value
```
and 
```yaml
#! values.yml
---
foo: val
```

**When** I execute `ytt -f . --data-values-schema-inspect -o openapi-v3`
**Then** I should see 

```
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas: {}
```

---

### :red_circle: Scenario 5: Fails when an Invalid Schema is provided

**Given** the following schema exists
```yaml
#@data/values-schema
---
vpc:
  subnet_ids: null
```

**When** I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
**Then** I should see on my screen
```
schema.yml:4 |   subnet_ids: null
             |
             | INVALID SCHEMA - null value is not allowed in schema (no type can be inferred from it)
             |   (hint: to default to null, specify a value of the desired type and annotate with @schema/nullable)
```

### :yellow_circle: Scenario 6: Help text for command

**Given** 
**When** I execute `ytt -f schema.yml --data-values-schema-inspect --help`
**Then** I should see on my screen
```
Generate a Schema from the provided files

Usage:
  ytt [flags]
  ytt [command]

Flags:
--data-values-schema-inspect  # prints ytt schema (as ytt schema with annotations) must be used with -o
```

---

### :green_circle: Scenario 6: Help text for command

**Given** 
**When** I execute `ytt -f schema.yml --data-values-schema-inspect  -o openapi-v3 --help`
**Then** I should see on my screen
```
Generate a Schema from the provided files

Usage:
  ytt [flags]
  ytt [command]

Flags:
-o openapi-v3[,yaml]   # prints data values schema as an OpenAPI Document (in YAML format; this is the default)
```

---

Notes:
- [Proposal](https://github.com/vmware-tanzu/carvel/pull/198)
- There is a following story that will support Arrays
- The `ytt` schema should be validated before generating the openapi schema
- [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#schemaObject)

**Comment by cari-lynn** [comment]
We decided to update the acceptance criteria to move scenario 4 to the story to add support for `@schema/type any=True` (when no data values schema, then you get an empty openapi doc).
