### ISSUE TITLE
Generate OpenAPI Schema for `any` type

### ISSUE THREAD

**Issue by joaopapereira** [k14s/ytt#365]
**As a** Configuration Author
**I want** to generate OpenAPI from my configuration
**so that** Configuration Consumers can use it.

---

### :green_circle: Scenario 1: Convert data values schema with any annotation on Document to OpenAPI schema

**Given** the following schema exists
```yaml
#! schema.yml
#@data/values-schema
#@schema/type any=True
---
foo:
  int_key: 10
```

**When** I execute `ytt -f . --data-values-schema-inspect -o openapi-v3`
**Then** I should see
```yaml
---
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    dataValues:
      default: 
        foo:
          int_key: 10
```

### :green_circle: Scenario 2: Convert data values schema with any annotation on Map to OpenAPI schema

**Given** the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
#@schema/type any=True
foo:
  int_key: 10
```

**When** I execute `ytt -f . --data-values-schema-inspect -o openapi-v3`
**Then** I should see
```yaml
---
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    dataValues:
      type: object
      properties:
        foo:
          default: 
            int_key: 10
```

### :green_circle: Scenario 3: Convert data values schema with any annotation on Array to OpenAPI schema

**Given** the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
#@schema/type any=True
foo:
- int_key: 10
```

**When** I execute `ytt -f . --data-values-schema-inspect -o openapi-v3`
**Then** I should see
```yaml
---
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    dataValues:
      type: object
      properties:
        foo:
          default: 
          - int_key: 10
```

### Key Notes from Resources

- [JSON Schema Validation §4.2: "Missing Keyword"](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-4.2)
  > Validation keywords that are missing never restrict validation.  In some cases, this no-op behavior is identical to a keyword that exists with certain values, and these values are noted where known.
- [kin/kin-openapi/schema_test.go](https://github.com/getkin/kin-openapi/blob/v0.80.0/openapi3/schema_test.go#L81-L88) (sourced from [openapi.tools](https://openapi.tools/)) illustrates how empty schema validate any value.

**Comment by pivotaljohn** [comment]
~Reviewing the kin source with @cari-lynn, we see that an empty OpenAPI schema does _not_ validate an input of "null".~

~Do we want to include "nullable: true" for these values?~

Upon closer reading of the OpenAPI Spec regarding the `nullable` property (https://swagger.io/specification/#schema-object):
> A true value adds "null" to the allowed type specified by the type keyword, **only if type is explicitly defined within the same Schema Object**.

_(emphasis added.)_

Along with the general consideration of missing keywords (noted in the description of this issue), this seems to indicate that `null` type is allowed along with all other types if there is no `type` property given.

...

However, all that said, it is not _invalid_ to include the `nullable` property. And we're aware of _at least_ one implementation that treats `null` as an invalid input to an "empty schema":
https://github.com/getkin/kin-openapi/blob/e9b36dac1a2890474ae44cfcf6446c00393527b5/openapi3/schema_test.go#L74-L92

So, including this property would ensure that this scenario — an empty schema — passes even a `null` input.

**Comment by cari-lynn** [comment]
I also researched the spec regarding what @jtigger stated above, and came to the same conclusion. By not specifying the `type` key, including `nullable: true`, and specifying a `default` value, that should be a valid OpenAPI way to convert ytt's `@schema/type any=True`.

**Comment by pivotaljohn** [comment]
> I also researched the spec regarding what @jtigger stated above, and came to the same conclusion. By not specifying the type key, including nullable: true, and specifying a default value, that should be a valid OpenAPI way to convert ytt's @schema/type any=True.

Thanks for the review, @cari-lynn. I'm more confident with this approach given it.
