### ISSUE TITLE
Enable support for local symlinks

### ISSUE THREAD

**Issue by mildred** [k14s/ytt#37]
When there is a symlink in a library evaluated by ytt, ytt errors out with an error similar to:

    Expected file 'pkg2/dir2' to be a regular file, but was not

Symlinks should be handled:

- if the symlink is internal to the directory tree that is initially loaded, the symlink should be followed
- if the symlink is external to the directory tree initially loaded:
    - if the symlink is not needed, it should be silently ignored
    - else, the symlink should trigger an error telling which target directory is missing

Additionally, ytt should allow from command-line to load additional directories. If a symlink points to this additional directory, the symlink should be followed.

Example:

```
$ ytt -f main.ytt/ -o main.out
Error: Evaluating main.ytt/symlink.yaml points to ../lib.ytt but this file is not loaded.
Use --load /home/user/Projects/lib.ytt to allow access
$ ytt -f main.ytt/ -o main.out --load lib.ytt
$
```

If we can agree on how this should be implemented, I can implement it

--------

Implementation notes:
- At load time, symlinks should be loaded as symlinks and their target should be stored in memory in the File object as well as the input directory that lead to the discovery of that symlink.
- in library.go NewRootLibrary() should add symlinks to the Library objects. Symlinks should be considered for both file access and child access (it will depend on the file type of the symlink target).
- Library objects should be created for extra loaded directories
- we need to be able to resolve `../` paths that can happen in symlinks, so the Library object must reference its parent.
- For each input directory (`-f` flag, `main.ytt` in the example), a relative path should be computed to go from the input directory to the extra loaded directories (`--load`, `lib.ytt`):
    ```go
    // Resolve symlinks
    uniqueLoadedDir, err := filepath.EvalSymlinks(loadedDir)
    uniqueInputDir, err := filepath.EvalSymlinks(inputDir)
    // Make the path absolute so there is no error in filepath.Rel()
    absLoadedDir, err := filepath.Abs(uniqueLoadedDir)
    absInputDir, err := filepath.Abs(uniqueInputDir)
    // Compute relative path
    InputToLoaded, err := filepath.Rel(absInputDir, absLoadedDir)
    ```
- Parent Library objects should be created as needed from these relative paths from the root Library.
- When following symlinks, the Library object should be used to navigate (and not the filesystem). When at the root library, there might be different parent depending on which input directory was used to discover the symlink. The proper parent Library should be used.

**Comment by cppforlife** [comment]
@nimakaviani and i are planning to chat about this a bit more this wed.

**Comment by cppforlife** [comment]
check out https://github.com/k14s/ytt/issues/18#issuecomment-511040240 which eliminates the need for supporting of symlinks.

**Comment by mildred** [comment]
The proposal in https://github.com/k14s/ytt/issues/18#issuecomment-511040240 makes it less necessary to support symlinks, but one thing remains. Symlinks might appear in the source tree for various reasons and ytt should not choke on them if they are not specifically loaded from another file. ytt should just ignore them.

**Comment by cppforlife** [comment]
> Symlinks might appear in the source tree for various reasons and ytt should not choke on them if they are not specifically loaded from another file. ytt should just ignore them.

i agree with ya, but im a bit reluctant to add at this point as this will complicate implementation without immediate need. much rather focus on your other work regarding library loading for now...

**Comment by mildred** [comment]
Yep, true, but an intermediate step before full symlink support would be to stop failing if project contains symlinks that are not needed by ytt.

**Comment by samschlegel** [comment]
Running into this when trying to use `ytt` with Bazel, as Bazel uses symlinks when sandboxing builds. It seems to me that an easy solution here would be to add support for symlinked files similar to how #12 was fixed.

**Comment by cppforlife** [comment]
@samschlegel we've disabled symlinks to avoid having to deal with situations where user is tricked into giving a symlink to ytt that points to non-intended location (for example, /etc/passwd). 

> as Bazel uses symlinks when sandboxing builds

could you paste some tree output that shows what a typical bazel build symlinking looks like?

**Comment by samschlegel** [comment]
Ah I had never considered that. Below is the BUILD file and the tree output

Build file:
```python
genrule(
    name = "manifest",
    srcs = ["k8s.yaml"],
    outs = ["k8s.yaml.built"],
    cmd = "./$(location //bazel/k14s:ytt) -f $< > $@",
    tools = ["//bazel/k14s:ytt"],
)
```
```
$ echo $(location //bazel/k14s:ytt)
external/ytt_linux_x86_64/file/ytt
$ echo $<
ytt_test/k8s.yaml
$ echo $@
bazel-out/k8-fastbuild/bin/ytt_test/k8s.yaml.built
$ tree
.
|-- bazel-out
|   `-- k8-fastbuild
|       `-- bin
|           `-- ytt_test
|-- ytt_test
|   `-- k8s.yaml -> /home/sam/.cache/bazel/_bazel_sam/d50f718107f06eb5b720bb473093cd22/execroot/discord/ytt_test/k8s.yaml
`-- external
    |-- bazel_tools
    |   `-- tools
    |       `-- genrule
    |           `-- genrule-setup.sh -> /home/sam/.cache/bazel/_bazel_sam/d50f718107f06eb5b720bb473093cd22/execroot/discord/external/bazel_tools/tools/genrule/genrule-setup.sh
    `-- ytt_linux_x86_64
        `-- file
            `-- ytt -> /home/sam/.cache/bazel/_bazel_sam/d50f718107f06eb5b720bb473093cd22/execroot/discord/external/ytt_linux_x86_64/file/ytt
```

**Comment by samschlegel** [comment]
I tried to get around this by doing `ytt -f <(cat $<)`, but it appears that the fix for #12 doesn't work on my machine.

**Comment by cppforlife** [comment]
> I tried to get around this by doing ytt -f <(cat $<), but it appears that the fix for #12 doesn't work on my machine.

@samschlegel seems like it was reading from location twice, which of course doesnt work. fixed in https://github.com/k14s/ytt/commit/1b22f0df9c9697ddee497758902a5ebcbcf4d2f5 to cache in memory. additionally you'll have to use `-f config.yml=<(...)` syntax to let ytt know that "this" file is a yaml file. will be included in the next release.

**Comment by cppforlife** [comment]
also, i think you should be able to use `-f-` to and pipe to stdin for now.

**Comment by samschlegel** [comment]
Piping to stdin and using `-f -` works fine for single files, but as far as I can tell `cat`ing together multiple files doesn't appear to work if some of those are `#@data/values` files. What I've ended up doing is `cp`ing them all into a directory and pointing ytt at that directory, but that won't work as easily if the input doesn't all live in the same directory.

How would you feel about adding support for symlinks only during resolution of `-f`?

**Comment by cppforlife** [comment]
https://github.com/k14s/ytt/releases/tag/v0.18.0 includes basic support for allowing symlinks via flags.

**Comment by cppforlife** [comment]
closing as symlink flags were added to 0.18.0.
