### ISSUE TITLE
[lang] add error message when both existing yaml node value and computed value are present?

### ISSUE THREAD

**Issue by laurentlb** [k14s/ytt#38]
Input:
```
x: #@ { "first": "is included"}
  second: is ignored
```
The second line is silently ignored.

Also here:

```
--- #@ { "first": "is included"}
this line: is ignored too
```

If this is not valid, I'd expect an error message instead of silently ignoring part of the input.

**Comment by cppforlife** [comment]
same situation as above,

```yaml
key: replaced-val #@ "computed-val"
```

@laurentlb yeah, we probably should error if we see that node has an existing value and also has a "computed" value. i cannot think of a case when it will be useful to allow above form. i can imagine if somehow computed value is conditional and we somehow indicate to keep the original node value, but im not sure that would be useful.
