### ISSUE TITLE
Report clearly which kind of document(s) were unused during an evaluation

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#390]
_(significantly edited from original as the code evolved since the issue was first created. However, the overall scope has not changed, just the details.)_

### 🟡  Scenario: Library Reference on Schema does not match any libraries

**given** I have a Schema document targeted to a specific library
**and** no library exists by that name
**when** I run `ytt`
**then** I expect to see an error message that makes clear that there were _Schema_ documents that weren't used by any libraries
**instead of** an error message that says there are "... library data values documents..."

### 🟡  Scenario: Library Reference on Data Values does not match any libraries

**given** I have a Data Value document targeted to a specific library
**and** no library exists by that name
**and** there weren't any "unused" Schema documents
**when** I run `ytt`
**then** I expect to see an error message that makes clear that there were Data Value _documents_ that weren't used by any libraries

**Comment by gcheadle-vmware** [comment]
Closing due to v0.36.0 release.
