### ISSUE TITLE
[lang] better error messaging for reserved keywords

### ISSUE THREAD

**Issue by nimakaviani** [k14s/ytt#4]
using a data field that is among the list of reserved keywrods, makes `ytt` fail with the following error:

```
- keyword pass is not supported
    demo.yml:32
     L   annotation: #@ data.values.pass
```

The error message should be improved and make it clear why the reserved keywords cannot be used.

**Comment by cppforlife** [comment]
changed err message to `use of reserved keyword 'pass' is not allowed` in https://github.com/k14s/ytt/commit/12333c307c9ef5da1980521b755389a204a58783

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/releases/tag/v0.17.0
