### ISSUE TITLE
Populate missing info during schema error messages

### ISSUE THREAD

**Issue by DennisDenuto** [k14s/ytt#417]
# Summary

Schema type checking errors that do *not* use a yaml file as a data value result in confusing error messages.

The confusion lies due to the error message 'missing' information (such as a file name, line number, and contents on the line number) to print within the 'diff' section of the error message.

This is a follow on story from https://github.com/vmware-tanzu/carvel-ytt/pull/411

# Description

This is a known issue in *at least* the following 2 scenarios.

## Using starlark to 'inject' a data value when rendering a template
e.g.

```
--- #@ template.replace(library.get("lib").with_data_values({'foo':'4'}).eval())`
```
results in
```
Schema Typecheck - Value is of wrong type
=========================================
     
     :
         |
       ? | 
         |
     
         = found: string
         = expected: integer (by _ytt_lib/lib/schema.yml:4)
``` 

Suggested improvement:
```
Schema Typecheck - Value is of wrong type
=========================================
     
    template.yml :
         |
       1 |  --- #@ template.replace(library.get("lib").with_data_values({'foo':'4'}).eval())
         |
     
         = found: string
         = expected: integer (by _ytt_lib/lib/schema.yml:4)
```
## Using ytt's `--data-value` flag 
e.g.
```
ytt --data-value foo=42 ...
```
results in
```
Schema Typecheck - Value is of wrong type
=========================================

key 'foo' (kv arg):
    |
  1 | 
    |

    = found: string
    = expected: integer (by schema.yml:3)
```

Suggested improvement:
```
Schema Typecheck - Value is of wrong type
=========================================

key 'foo' (kv arg):
    |
  1 | foo=42
    |

    = found: string
    = expected: integer (by schema.yml:3)
    = hint: update --data-value flag arg to comply with expected schema type
```

**Describe the solution you'd like**
Populate the missing information in the above 2 cases, and any other ways that a schema type check can fail and produce missing information in the diff.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
The current state of those error messages are very unhelpful. Most definitely something we want to address (and ideally right away) ==> "carvel accepted"

**Comment by pivotaljohn** [comment]
I see this work being handled in two parts:
1. where any values injected via a replace need to be fully converted to AST. 
    - I'm pretty sure that the `template.replace()` line is the closest we can get to attributing a line-of-source for the value... otherwise, we'd have to analyze the Starlark program AST and somehow determine where a given value was added to a collection (or something?)
    - any nodes that don't have a location within that AST sub-tree would be attributed to that `template.replace()`.
    - this is exactly what @DennisDenuto spec'ed out, above.
2. find a way to preserve the command-line arg input as a source line.

**Comment by cari-lynn** [comment]
There is one bit of work left as part of this: improving error messages for library functions. For example:

`library.get("lib").with_data_values({'foo':'4'}` still reports an error without line numbers. This was a much heavier lift than originally anticipating, so we're splitting it off into a separate story #455 .
