### ISSUE TITLE
Set the Data Values on a library a la `--data-values-file`

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#418]
**Describe the problem/challenge you have**
I want to be able to set the data values of a library with the same semantics as the `--data-values-file` flag from the command-line.

Specifically, I want the array values I pass in to _replace_ (not append) to the array values in the data values defined in the library.

**Describe the solution you'd like**
A function on the `@ytt:library` instance that accepts a `struct`, `dict`, `list`, or scalar that overlays those values in the same way they do with `--data-values-file`:

```yaml
--- #@ template.replace(library.get("libby").with_data_values_literals({"clients": [1,2,3]}).eval())
```

**Anything else you would like to add:**

To be explicit: there's significant value in being able to regard a `library.get()...eval()` as analogous to a separate invocation of `ytt`. One can envision "refactoring" what are literally multiple `ytt` invocations into a single invocation that folds together multiple `library.get()...eval()` calls. This remains a solution so long as the two APIs (i.e. `ytt`'s command-line and the `@ytt:library` are congruent).

_This_ request is in reaction to the introduction of the `--data-values-file` flag on the CLI (#381). It was further inspired by #563.

To Do:
- [x] #568
- [x] vmware-tanzu/carvel#323

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
some api alternatives:
- version library.get method (e.g. library.get_v2)
- version library module (e.g. @ytt:library2)
- add keyword argument to with_data_values(..., plain=True)

**Comment by pivotaljohn** [comment]
> some api alternatives:

Yes... better decisions through a greater diversity of options.

I had a visceral reaction to versioning. :) That's some serious interface complexity... would need to be worth it.

I'm fond of the additive `plain` keyword on _this_ version of `@ytt:library`. That said, I see how sweet it would be if `@ytt:library` mirrored the CLI. 🤔

**Comment by pivotaljohn** [comment]
Based on results of #429, recommending as a priority ==> recommended

**Comment by pivotaljohn** [comment]
@cppforlife: what about altering the behavior depending on the presence of schema?

1. if the library contains schema, then that's the way that data values will be validated ==> `@ytt:library.with_data_values()` automatically uses `--data-values-file` semantics.
2. if the library has no schema declared, then overlay validates ==>  `@ytt:library.with_data_values()` uses current (overlay) merge semantics.

I'm fairly certain this would be backwards compatible because it means being able to accept a _wider_ range of inputs: those that technically meet schema but — without help — don't make it through the overlay process.

In fact, I this also improves the overall user experience because the error messages provided by schema are more direct... so it's not just convenient, but _better_ to allow schema to catch such errors (rather than the overlay failing).

WDYT?
