### ISSUE TITLE
Include how Schema as part of "How It Works"

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#422]
**As a** new `ytt` user
**I want** to see where and how Schema are part of how `ytt` works
**so that** I know when and how I'd likely use that feature.

---

Including...
- add schemas in the top-level diagram as a separate group of "input file"s.
- add a new section to describe schema files.
- expand the work described in "Calculate Data Values" step to start with using the defaults from schema.
- in the "Further Reading" section, point users to appropriate pages about schema.

**Comment by aaronshurley** [comment]
Notes:
- [How it works](https://carvel.dev/ytt/docs/latest/how-it-works/)
- we already have the image (we don't need to recreate it)
