### ISSUE TITLE
Add example to illustrate using text templating to set key of a map item

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#432]
## Acceptance Criteria

**As a** ytt user looking at the playground
**I want** to see an example about data values as keys that uses text-templating, with a descriptive title. 

**As a** ytt user looking at the docs
**I want** to search the docs for "text templating", "Data Values as Keys", "Using Data Values in map", or "Using Data Values in dictionary", and see a result pointing to a FAQ response answering the question.

---

**Describe the problem/challenge you have**
> Hi Carvel friends. Quick question about ytt that I can’t find in the docs… can I use a data.values value as a key in my template? I’m trying to turn a key in an overlay into a user input, so they could specify as a value which key among a set of sibling keys that they would like to edit via the overlay.

https://kubernetes.slack.com/archives/CH8KCCKA5/p1623780048022400

**Describe the solution you'd like**
> If the Playground -> Basics had a section called “Keys as Values” or something like that, then I would have found it immediately. 

https://kubernetes.slack.com/archives/CH8KCCKA5/p1623784090033200?thread_ts=1623780048.022400&cid=CH8KCCKA5

**Anything else you would like to add:**
- ytt does have a `website` command to iterate on this locally (https://github.com/vmware-tanzu/carvel-ytt/blob/develop/docs/dev.md#website-changes)
- In order to redeploy the playground, we'll need to coordinate with Dmitriy (https://github.com/vmware-tanzu/carvel/issues/75)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
These additions make a lot of sense. Moving this to the Unprioritized Backlog for now since it might be best to tackle as a part of a larger docs effort. However, if anyone would like to contribute to these changes then we'd be open to them.
