### ISSUE TITLE
Explain Schema library function in documentation

### ISSUE THREAD

**Issue by gcheadle-vmware** [k14s/ytt#447]
## Acceptance Criteria

**As a** ytt user looking for information about using the schema feature in ytt private library
**I want** to nav to the [library module documentation](https://carvel.dev/ytt/docs/latest/lang-ref-ytt-library/#docs)
**and** see information and examples explaining the `with_data_values_schema()` function.

---
**Describe the problem/challenge you have**
When I nav to the [library module documentation](https://carvel.dev/ytt/docs/latest/lang-ref-ytt-library/#docs), I expect to see information and examples explaining the `with_data_values_schema()` function.

**Describe the solution you'd like**
Documentation explaining the `with_data_values_schema()` function. I should also be able to find these docs with search terms "with schema" and "with_data_values_schema".

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
With the realization for #449, pushed that rename through this story, too.
