### ISSUE TITLE
Rename `library.with_schema()` to `library.with_data_values_schema()`

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#449]
A subtle change wasn't scoped in #395: that it explicit was making room for other kinds of schema, later.

The `@ytt:library` module is a sort of mirroring API to `ytt` as a CLI: what one can specify on the command-line can often (perhaps not always) be useful within the programming environment.

To this end, we shoulda also renamed `library.with_schema()` to be `library.with_data_values_schema()` to _also_ leave room on _that_ API for other kinds of schema.

Note: this function is rather new/experimental, anyway, but take this time to sweep through docs and examples too.

**Comment by gcheadle-vmware** [comment]
I did not find any note of `with_schema` anywhere in the docs. `with_data_values_schema` will be added in #447.
