### ISSUE TITLE
Populate missing info during library schema error messages

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#455]
# Summary

Schema type checking errors that come from Starlark variables result in confusing error messages.

The confusion lies due to the error message 'missing' information (such as a file name, line number, and contents on the line number) to print within the 'diff' section of the error message.

This story was separated from https://github.com/vmware-tanzu/carvel-ytt/pull/417

# Description

## Using a library function to add data values to a library

```
#@ library.get("lib").with_data_values({'foo':'4'}).eval()
```
results in
```
Schema Typecheck - Value is of wrong type
=========================================
     
     :
         |
       ? | 
         |
     
         = found: string
         = expected: integer (by _ytt_lib/lib/schema.yml:4)
``` 

Suggested improvement:
```
Schema Typecheck - Value is of wrong type
=========================================
     
    template.yml :
         |
       1 |  #@ library.get("lib").with_data_values({'foo':'4'}).eval()
         |
     
         = found: string
         = expected: integer (by _ytt_lib/lib/schema.yml:4)
```

Note: Update all other functions that may trigger a schema error that results in a missing line number

**Describe the solution you'd like**
There was some investigation done as to how this may be accomplished. One possibility is that the `thread` variable that is available from the Starlark builtin that is called has the position the function was called from in the Starlark program. So we may be able to keep a map of source line in the template, to the line in the Starlark program and report that as the position in the error message.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
When estimating, it surfaced that a solution with the line number, file name, and function could be challenging:
- file name and function name: 2 points
- line number, file name, and function (with parameters): 3 points

@cari-lynn will sync up with @cppforlife to determine a suggested approach.

**Comment by gcheadle-vmware** [comment]
After syncing up with @cppforlife we concluded about a few things:
- in library evaluations, there is a [starlark eval error](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/template/compiled_template_error.go#L55) that is being returned, which contains a stack trace, starlark knows how to report these errors using the stack after they occur
- in oct 2019 there was a [starlark release that adds an "cause" field](https://github.com/google/starlark-go/commit/58de16fb0ee76530b35384f2854db6b4e0004ea0) that might allow us to have the schema error and inject information before calling the .Error() function on the schema error
- trying to "guess" on filename and function could be problematic, let's never report incorrect information in our errors, and grabbing file name or line number from the `thread` or `args` variables is not guaranteed to be correct - we can always create an example that would show this.
- helpful information to include in the schema error is the failing key. So, I'm going to investigate providing that information.
- as a continuation of this story, we should see if the starlark update would actually provide us with the ability to fill the error with correct information.

**Comment by gcheadle-vmware** [comment]
Closing due to v0.36.0 release.
