### ISSUE TITLE
Schemas Lightweight Demo at the Community Meeting

### ISSUE THREAD

**Issue by aaronshurley** [k14s/ytt#464]
We recently completed the *major milestone* of delivering schemas, let's show it to folks!

The intention of this demo is to spread awareness by doing a visual walkthrough. Things to consider:
- What are schemas?
- Why should I care?
- How does it work?
- How does this affect my current ytt usage?

**Describe the solution you'd like**
A demo at an [upcoming community meeting](https://hackmd.io/F7g3RT2hR3OcIh-Iznk2hw).

**Anything else you would like to add:**
Notes:
- I believe that we have all of this content in our documentation so this could just be a hands-on walkthrough.
- Consider timeboxing this to ~2 hours.
- For "How does this affect my current ytt usage?", considering just calling out the [migration guide](https://carvel.dev/ytt/docs/latest/data-values-schema-migration-guide/)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to work on this issue.

**Comment by gcheadle-vmware** [comment]
Demo given in the July 22nd community meeting: https://www.youtube.com/watch?v=EhA2oF7EAJY&list=PL7bmigfV0EqS1ZxRR1cRd8eqdwQij9Lsa&index=34
