### ISSUE TITLE
Document/Expose "completion" command in ytt

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#478]
Cobra 1.2.0 introduced a feature by which the library automatically includes a shell completion command (for bash, fish, powershell, and z-shell). [docs](https://github.com/spf13/cobra/blob/v1.2.0/shell_completions.md)

Dependabot generated a PR for the upgrade: #451

When that PR is merged, the feature is available: this new command (i.e. `completion`) is automatically added:

```
$ ./ytt --help
ytt performs YAML templating.

Docs: https://carvel.dev/ytt/docs/latest/
Docs for data values: https://carvel.dev/ytt/docs/latest/ytt-data-values/

Usage:
  ytt [flags]
  ytt [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  fmt         Format YAML templates
  help        Help about any command
...
```

👍🏻 

To maximize the value the feature provides, we need to do a little work to let users know it is there:

- [x] include this new feature in _our own_ release notes.
- [x] where we describe how to install `ytt`, mention this feature (point users to the help text: `ytt completion help`)

**Comment by pivotaljohn** [comment]
Removed "carvel triage"; we're definitely doing this work.

**Comment by aaronshurley** [comment]
Categorizing this as `important-soon` since we think that has a high ROI (little effort, high return).

**Comment by cari-lynn** [comment]
One suggestion for the docs is to include that `ytt completion zsh --help` tell you the exact command to run. It was a bit  confusing to me at first where to send the output of the command.

**Comment by pivotaljohn** [comment]
Completed by:
- vmware-tanzu/carvel#279
