### ISSUE TITLE
Documentation on the behavior of load statement

### ISSUE THREAD

**Issue by guludo** [k14s/ytt#49]
Hi there!

According to Starlak's spec on the [`load` statement](https://github.com/google/starlark-go/blob/master/doc/spec.md#load-statements), the first "argument" is left to be interpreted by the application (`ytt` itself in our case). I think it might be a good idea to add a note in the [docs](https://github.com/k14s/ytt/tree/master/docs) explaining how `ytt` interprets that.

I'm raising this issue because I couldn't find in the documentation and examples information regarding a problem I faced while using `load`. My use case requires passing yml files individually via `ytt -f`, and it took me a while to figure that I have to pass the included file via `-f` as well.

For example, if I go to [`example-load`](https://github.com/k14s/ytt/tree/master/examples/playground/example-load) and run the following command, it would fail:

```
$ ytt -f config.yml
Error: 
- cannot load funcs.lib.yml: Expected to find file funcs.lib.yml
    config.yml:5 in <toplevel>
     L #@ load("funcs.lib.yml", "func1", "func2")
```

Now, if I include the files to the list, it works properly:

```
$ ytt -f config.yml -f funcs.star  -f funcs.lib.yml 
func1_key:
  name: max
  cities:
  - SF
  - LA
func2_key:
  name: joanna
  cities:
  - SF
func3_key:
- 1
- 2
- key: value
```

It would be nice if there was documentation on the `load` function (and maybe on `ytt` CLI as well :smiley:).

Note: it seems that #9 is a related issue, but it talks about improving the error message but not about the project's documentation.

Best regards,
Gustavo Sousa

**Comment by guludo** [comment]
By the way, thank you for this project! I find it awesome! :smile:

**Comment by cppforlife** [comment]
@guludo thanks for using the project. i've added https://github.com/k14s/ytt/blob/develop/docs/lang-ref-load.md. let me know if more info needed.

**Comment by guludo** [comment]
Hi @cppforlife , sorry for the late answer... I've just got time to look at it today.

Thanks for adding the documentation. And yes, it has enough information. I just have one comment though:

I'm not sure if the documentation defines a clear distinction between a `library` and a `package`. For example, if I go to https://get-ytt.io/#example:example-load-custom-library and use `#@ load("@github.com/k14s:test-lib/funcs.star", "testfunc")` instead of `#@ load("@github.com/k14s/test-lib:funcs.star", "testfunc")`, things continue working.

Is a library a directory that is supposed (or might contain) a `_ytt_lib` directory?

**Comment by cppforlife** [comment]
> I'm not sure if the documentation defines a clear distinction between a library and a package

dont think we currently mention it as we have yet to implement what's proposed here: https://github.com/k14s/ytt/issues/18#issuecomment-511040240. 

we have come to conclusion that unless we require everyone to somehow annotate where the root of the library is, caller (writer of load statement) has to decide where the library begins. this mostly affects how one would be able to load files relative to library root (not currently possible since all loads are relative to current directory and do not allow use of `..`)

**Comment by cppforlife** [comment]
i added additional info in here https://github.com/k14s/ytt/commit/47d6cb7d948ab514d91c1fd6685c5e9f50583ab9.

**Comment by guludo** [comment]
Thanks! :slightly_smiling_face:
