### ISSUE TITLE
Basic YAML tutorial for ytt users

### ISSUE THREAD

**Issue by iamhsk** [k14s/ytt#492]
### Why
So that new ytt users who are not familiar with YAML syntax can better understand ytt syntax 

Examples: 

- [IBM's YAML basics & usage in k8s](https://developer.ibm.com/tutorials/yaml-basics-and-usage-in-kubernetes/)  
- [YAML Tutorial: Everything You Need to Get Started in Minutes](https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started)

**Comment by pivotaljohn** [comment]
@iamhsk, how does https://carvel.dev/ytt/docs/latest/yaml-primer/ size up in your mind?

**Comment by iamhsk** [comment]
Oh gosh, yes! Didn't realized it already happened.
