### ISSUE TITLE
Bump go version to latest

### ISSUE THREAD

**Issue by aaronshurley** [k14s/ytt#493]
**Describe the problem/challenge you have**
#484 drew attention to the fact that we are not on the latest go version. We want to ensure that the code remains compatible with the latest versions so that we do not risk falling behind and on an unsupported version (note: go supports n-1 versions).

**Describe the solution you'd like**
The code runs on the latest version of go.

**Anything else you would like to add:**
- Please close #484 once this issue is resolved.
- Once 1.18 is released then 1.16 would no longer be supported.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Marking this issue as `important-soon` as we don't want to lapse on go versions.

**Comment by DennisDenuto** [comment]
when bumping golang, the goreleaser version used in the release GH action will also need to be bumped.

This is because ytt generates an arm binary. and goreleaser 0.162.0 has a bug where if using go 1.17 the darwin/arm binary is skipped.
