### ISSUE TITLE
Need package documentation on the workspace concept

### ISSUE THREAD

**Issue by jayunit100** [k14s/ytt#494]
Hi YTT friends... 

Whats the definition of a ytt workspace  ? 

For example, i see: https://github.com/vmware-tanzu/carvel-ytt/tree/develop/pkg/workspace, and theres a generic concept of a Library which, seems to be a recursive datastructure that references other libraries… 

If I had to guess, I'd say
- a "workspace" references the "file root" of the place where your "doing stuff"
- YTT generally expects that, for any given command, the "root" of your current working directory is a "workspace" which may have multiple children (libraries) in it
```
type Library struct {
	name     string
	private  bool // in _ytt_lib
	children []*Library
	files    []*files.File
}
```

but then again, im just totally guessing, so I guess my ask would be here, that maybe we add package level docs/README or something to the `pkg/workspace` :)

---
_(associated conversation: https://kubernetes.slack.com/archives/CH8KCCKA5/p1632838181464500)_

**Comment by pivotaljohn** [comment]
In our conversation on Slack (noted, above), it appears that you're looking at various ways to integrate with `ytt`.
Seems like this might be most fruitful as a synchronous conversation.

As noted in that thread, we are in the midst of a campaign of including Godoc as we make modifications to the code: package and exported type documentation is forth-coming.

I'm going to close this issue, for now... and we can continue our chat at least in the Slack thread (if not more synchronously). If you think this is a mistake, feel free to say so here, and we'll review.
