### ISSUE TITLE
Include files

### ISSUE THREAD

**Issue by fbritoferreira** [k14s/ytt#495]
I have the following file structure

```
tasks/task1.yml
tasks/task2.yml
main-file.yml
```
I want to be able to load my task files in my main file, i tried using `load` to load the files it doesnt seem to work, what is the best option to combine these files together. 

Also is possible to pass variables to these tasks from the main file would be a bonus

**Comment by pivotaljohn** [comment]
Sounds like you want to capture `tasks/task1.yml` and `tasks/task2.yml` as YAML Fragments and then reference them the the location of your choosing within `main-file.yml`.

1. turn your templates that contain the fragments into "loadable modules" by adding the `.lib.` extension
    ```bash
    $ mv tasks/task1{,.lib}.yml
    $ mv tasks/task2{,.lib}.yml
    ```
    Doing so changes two things:
    a. the contents of these files are no longer included in the output.
    b. it marks them as a "loadable module" which means you can `load()` them from a template.

2. for each of those task files, wrap their content in a function declaration.

    `task1.lib.yml`
    ```yaml
    #@ def task1():
    foo: bar
    #@ end
    ```
    This captures that YAML fragment (here, `foo: bar`) within the function. Invoke the function and its return value is this fragment.

3. now load those custom modules you've just created in the actual template and invoke their functions to set the value of some part of the main template:

    `main-file.yml`
    ```yaml
    #@ load("tasks/task1.lib.yml", "task1")
    #@ load("tasks/task2.lib.yml", "task2")
    ---
    tasks:
    - #@ task1()
    - #@ task2()
    ```

[[Playground](https://carvel.dev/ytt/#gist:https://gist.github.com/pivotaljohn/601215b0095a95c30652b7cc5ef60fc0)]

Does that help?

**Comment by pivotaljohn** [comment]
@iTsFILIPOficial ^^^

**Comment by pivotaljohn** [comment]
We'll close this for now.

@iTsFILIPOficial, if you would like more assistance, feel free to comment here; we'll see it and re-open it.

Hopefully, we're not hearing from you because you've figured it out. 🤞🏻

**Comment by CJKay** [comment]
Is there any way to do this today? Creating functions for each YAML fragment works, but I've got files with tonnes of `#@ def` / `#@ end` and it's close to unreadable. It'd be really nice to be able to load YAML fragments directly from a file.
