### ISSUE TITLE
 cannot load lib/helpers.star: Evaluating starlark template:

### ISSUE THREAD

**Issue by anibal-aguila** [k14s/ytt#499]
Hi, we have the following issue trying to setup a new cluster.

**What steps did you take:**
tanzu cluster create tkgs-shared-base --file /root/downloads/tanzu-bundle-1.4/tkg-shared-base.yaml --tkr=v1.20.9---vmware.1-tkg.1.a4cee5b -v 6

**What happened:**
Validating configuration...
Error: failed to create Tanzu Kubernetes Cluster service for vSphere workload cluster:
- cannot load lib/helpers.star: Evaluating starlark template:
    in <toplevel>
      overlay.yaml:3 | #@ load("lib/helpers.star", "get_bom_data_for_tkr_name", "get_default_tkg_bom_data", "kubeadm_image_repo", "get_image_repo_for_component", "get_vsphere_thumbprint")

    reason:
     - NoneType has no .split field or method
         in get_tkr_version_from_tkr_name
           15 |    strs = tkr_name.split("---")
         in get_bom_data_for_tkr_name
           42 |         tkr_version = get_tkr_version_from_tkr_name(data.values.KUBERNETES_RELEASE)
         in <toplevel>

**What did you expect:**
Cluster up and running

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- ytt version (use `ytt --version`):   0.34.0
- OS (e.g. from `/etc/os-release`): Photon 4.0

thanks in advance,

**Comment by pivotaljohn** [comment]
Hey @anibal-aguila.

So, the symptom appears to be that `tkr_name` is `None` (the Python/Starlark equivalent to `nil` or `null`).

Just based of the name of the function, it looks like `tkr_name` is getting its value from `data.values.KUBERNETES_RELEASE`.

Are you able to verify that _that_ data value is being set?

- One clue is that the data value is written in ALL CAPS. I often see that when the data value is being set via an environment variable.
- that said, I also notice that the command line arg `--tkr=v1.20.9---vmware.1-tkg.1.a4cee5b` contains that triple-dash... perhaps the Tanzu CLI expects to place the value set for `tkr` to this `KUBERNETES_RELEASE` data value?

I see that you're using Tanzu. I suspect that you'd get additional help in the Kubernetes slack: https://kubernetes.slack.com/archives/C02GY94A8KT.  Visit http://slack.k8s.io/ to join the Kubernetes Slack workspace if you are not already there.

**Comment by pivotaljohn** [comment]
We'll close this issue for now. @anibal-aguila, if you would like more assistance, please feel free to comment here; we'll see it and re-open this issue. Hopefully we haven't heard from you because the issue is resolved. 🤞🏻
