### ISSUE TITLE
🐦 Please tweet about v0.37.0 release 🐦 

### ISSUE THREAD

**Issue by adriens** [k14s/ytt#504]
Hi guys,

🙏 could you please tweet about [`v0.37.0`](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.37.0) ?

Thanks in advance 💋 

Kind regards,
Adrien

**Comment by adriens** [comment]
`choco` on its way cf https://github.com/adriens/chocolatey-ytt/issues/12

**Comment by aaronshurley** [comment]
Thanks for the reminder, @adriens :)

Tweet: https://twitter.com/carvel_dev/status/1447588933899100167?s=20

**Comment by adriens** [comment]
👌

**Comment by adriens** [comment]
RT done 🚀
