### ISSUE TITLE
Exporting OpenAPI doc reports error when `@schema/default` value is incorrect type

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#506]
This is a follow-up from #490:

If we validate the type of a default value either _while_ constructing the schema, itself, or _en masse_ immediately after the schema is built (but before Data Value Preprocessing occurs),
then we could provide an audience-specific error message.

Right now:
- the message to **Configuration Authors** when their `@schema/default` values are mistyped (especially given that we don’t show the annotation in the error) points to the annotated node
- we settled for a hint within the PR ([example](https://github.com/vmware-tanzu/carvel-ytt/pull/490/files#diff-2ab902ad23ffe96207ff6466403834df5538e509639024bfc503aed26a377cb8R317)) but this muddies the waters for **Configuration Consumers**.

Benefits: 
- provide a "annotation error" when a user provides a value in their annotation that is incompatible with their schema.
- if a schema has an incorrect default value provide a error when exporting openapi schema

**Comment by cari-lynn** [comment]
This story was regarding displaying the appropriate error message for the user (config consumer or author) and currently the error messages do display a hint for `@schema/default` when you are a config author which is correct. 

Closing this since no more work needs to be done
