### ISSUE TITLE
improve hinting and docs for boolean and/or

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#509]
**Describe the problem/challenge you have**

for new users it might be hard to know what symbols/keywords to use for boolean and/or. starlark does not use &&, ||. it uses `and`, `or`.

**Describe the solution you'd like**
- hint at `and`, `or` here: https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/template/compiled_template_error.go#L190
- augment docs with more examples of if conditinal usage (specifically here: https://carvel.dev/ytt/docs/latest/lang-ref-if/)

**Anything else you would like to add:**
example errors received:

```
unknown binary op: bool | bool - when ((iterator.property == "some-value") | (iterator.property == "another-value"))

== does not associate with == (use parens) - when iterator.property == "some-value" | iterator.property == "another-value"
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Great suggestions that will help improve the usability of ytt. Marking this as `important-longterm` and will throw it into the backlog. For anyone that comes across this issue, we're open to contributions. Let us know if you'd like to give it a shot.

**Comment by vmunishwar** [comment]
![image](https://user-images.githubusercontent.com/89049433/145637569-eb8ccbb6-437b-4dc8-84f7-79711ccf46e8.png)

**Comment by vmunishwar** [comment]
![image](https://user-images.githubusercontent.com/89049433/145639099-6aafb360-34af-4f76-b39d-f5c7c43d7c10.png)
