### ISSUE TITLE
support "deprecated" field in OpenAPISchema

### ISSUE THREAD

**Issue by joe-kimmel-vmw** [k14s/ytt#514]
- When a data value is annotated with @schema/deprecated, and the user inspects the schema openapi-v3 format, that property has deprecated: true
- @schema/deprecated requires a string argument that provides information about the deprecated field or can be left ""

#### 🟢 Scenario 1: `@schema/deprecated` annotation generates a `deprecated` key for scalars
Given the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
foo:
  #@schema/deprecated
  int_key: 10
  #@schema/deprecated
  bool_key: true
  #@schema/deprecated
  false_key: false
  #@schema/deprecated
  string_key: some text
  present_int: 9
```
When I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
Then I should see on my screen
```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    dataValues:
      type: object
      additionalProperties: false
      properties:
        foo:
          type: object
          additionalProperties: false
          properties:
            int_key:
              type: integer
              deprecated: true     # <-
              default:10
            bool_key:
              type: boolean
              deprecated: true     # <-
              default: true
            false_key:
              type: boolean
              deprecated: true     # <-
              default: false
            string_key:
              type: string
              deprecated: true     # <-
              default: some text
            present_int:
              type: integer
              default: 9 
```
#### 🟢 Scenario 2: `@schema/deprecated` annotation generates a `deprecated` key for an array
Given the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
foo:
  #@schema/deprecated
  arr:
    - int_key: 10
      string_key: some text
```
When I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
Then I should see on my screen
```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    dataValues:
      type: object
      additionalProperties: false
      properties:
        foo:
          type: object
          additionalProperties: false
          properties:
            arr:
             type: array
             deprecated: true    # <- 
             items: 
                type: object
                additionalProperties: false
                properties:
                  int_key:
                    type: integer
                    default: 10
                  string_key:
                    type: string
                    default: some text
```
#### 🟢 Scenario 3: `@schema/deprecated` annotation generates a `deprecated` key for a map
Given the following schema exists
```yaml
#! schema.yml
#@data/values-schema
---
foo:
  #@schema/deprecated
  inner_map:
    string_key: some text
  required_map:
    some: text
```
When I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
Then I should see on my screen
```yaml
openapi: 3.0.0
info:
  version: 0.1.0
  title: Openapi schema generated from ytt Data Values Schema
paths: {}
components: 
  schemas:
    dataValues:
      type: object
      additionalProperties: false
      properties:
        foo:
          type: object
          additionalProperties: false
          properties:
            inner_map:
              type: object
              additionalProperties: false
              deprecated: true     # <-
              properties: 
                string_key:
                  type: string
                  default: some text
            required_map:
              type: object
              additionalProperties: false
              properties:
                some:
                  type: string
                  default: text
```

#### 🔴  Scenario 4: When value is any type other than a string
Given the following schema exists
```yaml
#! schema.yml
#@data/values-schema
#@schema/deprecated 12  #<-
---
key: value
```
When I execute `ytt -f schema.yml --data-values-schema-inspect -o openapi-v3`
Then I see an error that the value must be a string
```
Invalid schema
==============

syntax error in @schema/deprecated annotation
schema.yml:
    |
  3 | #@schema/deprecated 12
  4 | ---
    |

    = found: Non-string value (in @schema/deprecated (by schema.yml:3)
    = expected: string
```

#### 🟢 Scenario 5: 📚 Documentation
**Given** I want to learn how to include a deprecated in my OpenAPI v3 export
**When** I navigate through `ytt` documentation
**Then** I intuitively find the reference that describes how I can add a deprecated field so that it populates the corresponding property with deprecated:true in my OpenAPI v3-formatted Data Values Schema inspect.

---
This is the original request - 
**Describe the problem/challenge you have**
during the evolution of software it is often the case that the first name for a thing is not the last name for a thing. Thus, a package author might release versions along the lines of:
v1
[...]
     aConfusingAndLousyName: string
[...]
```

```
v4
[...]
    OneCrispConcept: boolean
    aSeparateCrispEntity: integer
[...]
```

in the above example we split a poorly named and confusing string param into two separate params, a boolean and an integer.

In order to make the upgrade path clean we would generally mark the `confusingAndLousyName` as deprecated in v2 and v3, and ship code to shim from that representation into our new one, but not remove the support for that param until v4 (or later).
     

**Describe the solution you'd like**
It seems me (and I could be wrong) that Open API Schema supports marking fields deprecated,  per the docs at https://swagger.io/specification/ . 


**Anything else you would like to add:**
From my ("our"?) perspective this will be an essential feature for the packaging "dependencies and upgrade" stories our team is working on.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
Would require two parts/stories:

1. in `--data-values-schema-inspect -o openapi-v3`, detect the `@schema/deprecated` annotation and include this "property" in the OpenAPI document output.
2. (independently) implement [`@schema/deprecated`](https://hackmd.io/pODV3wzbT56MbQTxbQOOKQ#schemadeprecated): #554 

cc: @cari-lynn (looks like another story... not sure where.)

_(edit: created the corresponding story to "enforce" this annotation in ytt schema _separately_ from including it in OpenAPI output.)_

**Comment by pivotaljohn** [comment]
Would require two parts/stories:

1. Implement [`@schema/deprecated`](https://hackmd.io/pODV3wzbT56MbQTxbQOOKQ#schemadeprecated)
2. in `--data-values-schema-inspect -o openapi-v3`, detect and include this "attribute"

**Comment by pivotaljohn** [comment]
@aaronshurley — thoughts on prioritization?

**Comment by aaronshurley** [comment]
@pivotaljohn I'd love for the initial issue triagers to give a first pass at determining the priority of an issue. This way, we can scale out decision-making effectively. Since I'm about to head out for a few days, I'll share my thoughts. This feature seems like it will be useful but we may not have an immediate need since schema features are still pretty new and the dependencies and upgrade features execution hasn't started, yet. I'd suggest `priority/important-longterm` and consider placing it after the current set of OpenAPI features. Happy to hear other thoughts on this!

**Comment by pivotaljohn** [comment]
> This feature seems like it will be useful but we may not have an immediate need since schema features are still pretty new and the dependencies and upgrade features execution hasn't started, yet.

Relevant context. 👍🏻 

I agree.

@joe-kimmel-vmw — it's generally on the roadmap to do exactly this work. If "long term" is not soon enough, let's talk.

cc: @cari-lynn (leading the OpenAPI Schema track)

**Comment by joe-kimmel-vmw** [comment]
> "long term" is not soon enough
Is that the next James Bond movie???  

I think a single-digit number of weeks will be fine,  but we'd like to plan as though this will be available by the time we're smoothing out the last little wrinkles and preparing to fully release the dependency management stories.   Which I'd hesitate to put a timeline on, but "early 2022" seems like a helpful landmark for this discussion.  Is "early 2022" within or beyond your "long term" scope?

**Comment by aaronshurley** [comment]
My current mental model for "long term" is one or more quarters out. Given the above estimate on the dependency management work, I'd be happy to consider this as "important soon". I think that we could still wait to implement this feature until after our initial set of OpenAPI features since it seems purely additive but please let me know if you think otherwise.

**Comment by cari-lynn** [comment]
We had a conversation in [k8s slack ](https://kubernetes.slack.com/archives/CH8KCCKA5/p1643226033163800) about whether a schema document should be annotated as `@schema/deprecated`. The outcome of that discussion was that we don't have a use case for it right now. Given that annotating a document adds an OpenAPI key to the top level schema, we should disallow this annotation on a document for now.

The recommendation is to annotate keys individually as deprecated. If you have a use case for annotating a schema document as deprecated, please share it.

**Comment by vmunishwar** [comment]
Thanks Cari! I have updated the acceptance criteria accordingly.
