### ISSUE TITLE
Within schema, fragments annotated with `@schema/type any=True` are erroneously validated as schema (rather than as a default value)

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#523]
_(Inspired by #515)_

**What steps did you take:**

```yaml
#@data/values-schema
---
spec:
  #@schema/type any=True
  additionalConfig:
    args:
    - "cmd"
    - "arg1"

```

**What happened:**

Got this error:
```
ytt: Error:
Invalid schema
==============

Invalid schema - wrong number of items in array definition
==========================================================

schema.yml:
    |
  6 |     args:
    |

    = found: 2 array items
    = expected: exactly 1 array item, of the desired type
    = hint: in schema, the one item of the array implies the type of its elements.
    = hint: in schema, the default value for an array is always an empty list.
    = hint: default values can be overridden via a data values overlay.
```

**What did you expect:**
That anything within a YAML fragment that's annotated with `@schema/type any=True`:
- can contain _any_ valid YAML
- _is_ the default value for the annotated node.

**Anything else you would like to add:**
This expectation was implied, but made explicit with #516.

From an implementation perspective, this might well be "simply" to:
1. stop processing this subtree of the schema AST for types ;
2. consider this subtree as the default for the annotated node.

**Environment:**

- ytt version (use `ytt --version`): v0.37.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cari-lynn** [comment]
Available in [v0.38.0](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.38.0)
