### ISSUE TITLE
Yaml list to comma delimited string

### ISSUE THREAD

**Issue by ploef** [k14s/ytt#527]
Hi,

At the moment I'm investigating if ytt could be the tool to use for yaml templates. Most of the template s working now but I'm struggling with one thing. Does anybody know how to turn a list into a comma delimited string:

e.g.
mylist:
  - 123
  - 456
  - 789

should be converted to:

123, 456, 789

**Comment by pivotaljohn** [comment]
Hey @ploef; welcome!

Glad to hear you're making traction in using `ytt`. And that you thought to ask for help on this one.

I need to make some guesses as to what you're doing to be helpful. If I'm making an invalid assumptions, please correct me.

I assume
- that the input list is coming in as a [Data Value](https://carvel.dev/ytt/docs/latest/how-to-use-data-values/).
- that you want the output to be a string, where each input value is included, separated by a comma and a space.

If all that is true, here's a way that I would do that in `ytt`: https://carvel.dev/ytt/#gist:https://gist.github.com/pivotaljohn/904ca7c7b497549886deff297dcc850d

...

Please also note: you can get _responsive_ support via our Slack channel: Kubernetes#carvel https://kubernetes.slack.com/archives/CH8KCCKA5

If you're not already in the Kubernetes workspace, signup here: https://slack.k8s.io/

**Comment by ploef** [comment]
Hi @pivotaljohn,

That's exactly what I was looking for! Thanks a lot for the quick response!
