### ISSUE TITLE
Generate OpenAPI `info` from annotation

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#539]
Why: to allow a configuration author to programmatically set the contents in the `info` section of an OpenAPI Doc that is generated from a ytt data values schema.

Specifically, the [`info` object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#info-object) looks like this (title and version are required): 
```yaml
info:
  version: 0.1.0  #! version of this document 
  title: Openapi schema generated from ytt Data Values Schema
  #! optional
  description: The description
  termsOfService: url.com
  contact: {}
  license: {}
```

### Option A (my preference)
We could use one annotation that accepts an object to set all the `info` fields (@pivotaljohn):
```yaml
#@data/values-schema
#@schema/info { {"version": "0.11.0"}, {"description": "Schema for data values allowed for this package"}, {"title": "Schema for Beverage choices"} })
---
beverage: juice
```

Considerations: 
- annotations must be on one line, so this line could become very long if nested objects (`license` or `contact` are required
- However, I assume that most authors will only need to update `title`, `version`, and `description`
- Can be set in a `yamlFragment` to make more readable

### Option B
One annotation per key:
```yaml
#@data/values-schema
#@schema/info  {"title", "Schema for Beverage choices"}
#@schema/info {"description", "Schema for data values allowed for this package"}
#@schema/info {"version", "0.11.0"}
---
beverage: juice
```

Considerations: 
- Deviation from how annotations currently work - now if multiple of the same annotation is on a node, we only use the first one.
- verbose and occupies a lot of vertical real estate
- easier to read inline when sentences are long

**Comment by cari-lynn** [comment]
I want to consider the differences between a **`info`** object (from above) and a **`components.schemas`** object, we should think about why they are different to determine if we want to treat them differently. 

We currently are thinking about doing something like Option B for 'metadata' on a specific key for the **`components.schemas`** object: 
```yaml
#@data/values-schema
---
#@schema/title "Beverage Choice"
#@schema/desc "A liquid substance that can be drank"
beverage: juice
```
We could combine the annotations in the same way as Option A:
```yaml
#@data/values-schema
---
#@schema/info { "title": "Beverage Choice", "description": "A liquid substance that can be drank" }
beverage: juice
```
Considerations: 
- There are not many 'metadata' fields in a schema object, so these two plus maybe `externalDocs` would be considered 'info'. So we are really only saving one line of space by combining them this is unlike the `info` object, where there are many 'metadata' keys.
- other annotations would still be separate (for example: `@schema/deprecated` or `@schema/validate`)

Please share your thoughts and opinions

**Comment by pivotaljohn** [comment]
re: Option A
> annotations must be on one line, so this line could become very long if nested objects (license or contact are required

We _could_ suggest that folks can declare a Starlark dictionary:

```
#@ info = {
#@   "version": "0.11.0",
#@   "description": "Schema for data values allowed for this package",
#@   "title": "Schema for Beverage choices"
#@ }
#@schema/info info
```

That helps ameliorate the constraint that annotations must reside on a single line...

**Comment by cari-lynn** [comment]
@pivotaljohn and I discussed this more and we landed on this additional context:

When a data values schema is annotated at the document level for example:
```
#@schema/desc ""
---               #<-- this is the important part 
```

then it applies to the section immediately following the component.schemas.dataValues section:
```
components: 
  schemas:
    dataValues:
      type: object
      additionalProperties: false
      description: Beverage of choice    # <---------------------------------------- !! 
      properties:
```

With that information, we arrived at the place where option B would not work to set the `info` object. Next steps we need to find a way to set the `info` object using either option A, or another way, potentially a separate namespace `@schema-set/title` or `@schema/set title="value"`, etc..

**Comment by aaronshurley** [comment]
Some questions we'd like to answer before picking up this story:
- could we choose between the two presented options so that we can then firm up on the UX?
- is the `info` annotation required? or any of the attributes?

**Comment by cari-lynn** [comment]
I updated Option B, please let me know if you have any thoughts on preference between A or B. 

Some things to consider:
* `@schema-set/title`
  * This would be introducing a new namespace just for setting the info. Since it is still related to schema, then I think it should stay in the same `@schema` namespace
* `@schema/set title="value"` could work if this allows multiple key value arguments in a single annotation. If it needs to be specified multiple times then it will suffer from 
    > Deviation from how annotations currently work - now if multiple of the same annotation is on a node, we only use the first one
* `@schema/set-title` ?

**Comment by pivotaljohn** [comment]
Returning to the OpenAPI spec for additional inspiration, [the description for these fields](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#infoObject) are:

Field Name | Type | Description
-- | -- | --
title | string | REQUIRED. The title of the **application.**
description | string | A short description of the **application.** CommonMark syntax MAY be used for rich text representation.
version | string | REQUIRED. The version of the OpenAPI document (which is distinct from the OpenAPI Specification version or the API implementation version).

In the context of the OpenAPI spec, the collection is referred to as an "application".

When we re-contextualize into the `ytt` world, the closest entity I see is the "Library" ... as in a schema over the total set of files that are being evaluated.

Given that perspective, perhaps:

```
#@data/values-schema

#@schema/library-title "Telemetry Installation Config"
#@schema/library-desc "Configuration values for installing the Telemetry package. Refer to https://docs.platform.com/installation/telemetry for details."
#@schema/library-version "1.1.0"
---
```

Rationale:
- as @cari-lynn mentioned, having one namespace for schema annotations is ideal.
- using a prefix like this as the difference between this group of annotations and their within-schema counter-parts (i.e. `@schema/title`, `@schema/desc`, ...) makes the "API" more guessable/discoverable.
- the word "library" (as overloaded as it is), is apt both for the root library and any private libraries. It claims coverage in the way (I think) we intend: to one day be a collection of schema that are used within the evaluation of _this_ library.

**Comment by cppforlife** [comment]
> the word "library" (as overloaded as it is), is apt both for the root library and any private libraries. It claims coverage in the way (I think) we intend: to one day be a collection of schema that are used within the evaluation of this library.

seems to couple schemas concept to libraries which isn't necessarily the case (at least the desire).

additionally if ever introduce concepts of actual library version, it's a little weird for schema/library-version to be there.

**Comment by pivotaljohn** [comment]
> additionally if ever introduce concepts of actual library version, it's a little weird for schema/library-version to be there.

That's a fine point. While changes to the API _will_ result in a version bump (when such a thing exists), changes to behavior within the library would do the same. So, the aggregate _is_ the library, itself: that's where _the_ version should live. 👍🏻 

Have you put any thought, to date, in to how one would supply metadata (like name, version, authors, etc) for a library?

**Comment by cari-lynn** [comment]
Supplying the fields required for OpenAPI info (`version` and `title`) is going to overlap with those same concepts of the entire library. In other words if the version of the schema metadata changes, then the version of the entire "library metadata" would likely be bumped as well. 

While we don't have a known use case for a library metadata now, it makes sense to plan to be able to modify the OpenAPI metadata and library metadata in the same way. 

Closing this in favor of solving this in harmony with library metadata. The consequence is that exported OpenAPI `info` will continue to have default values until the other story is played. (if this is important to you vote on the issue below ⬇️ )
