### ISSUE TITLE
Playground sample doc issue

### ISSUE THREAD

**Issue by rashedkvm** [k14s/ytt#541]
**What steps did you take:**

Playground sample documentation error. 
**What happened:**

In the playground example "Getting-Started=>Externalize-Data-Value" the `_cmd_line.yaml` has incorrect file name in cmd `$ ytt -f config.yml -f values.yml`. File `values.yml` does not exist.

https://github.com/vmware-tanzu/carvel-ytt/blob/cdb721091345c9fcbab95d0df10608d6165b58af/examples/playground/getting-started/example-externalize-data-values/_cmd_line.yaml#L4
**What did you expect:**

The command should be `$ ytt -f config.yml -f schema.yml`

**Anything else you would like to add:**

**Environment:**

- ytt version (use `ytt --version`):0.36.0
- OS (e.g. from `/etc/os-release`):

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cari-lynn** [comment]
@rashedkvm Thank you for finding this! Its an oversight that should be fixed. We would be happy to accept a PR for it.
