### ISSUE TITLE
🙏 Please tweet about v0.38.0 release 🐦 

### ISSUE THREAD

**Issue by adriens** [k14s/ytt#549]
Hi, the chocolatey release is ready (cf https://github.com/adriens/chocolatey-ytt/issues/13) : could you please drop a tweet so I can RT it ?

Thanks again.

Have a nice week-end
🏖️ 🍸

**Comment by cari-lynn** [comment]
Hey @adriens ! Apologies for the delay, we have a US Thanksgiving holiday so some people are out of office this week. The tweets will likely be delayed for a short time. Thanks for your understanding.

**Comment by adriens** [comment]
Hey, you're right !!! Happy thanksgiving to you and the team 🍰

**Comment by aaronshurley** [comment]
[The tweet is live!](https://twitter.com/carvel_dev/status/1462910494512230403) Appreciate your patience, @adriens.

**Comment by adriens** [comment]
AH AH @aaronshurley you couldn't resist to the call of the release 🎆
