### ISSUE TITLE
Improve documentation about data/values and output directory flag

### ISSUE THREAD

**Issue by suzuki-takayuki** [k14s/ytt#55]
I happened to find this tool and tried it, but stumbled upon some unexpected behavior.
Hope the following improvements would help new users.
* Document that at least one YAML document with `@data/values` annotation should be included in the input when `--data-value` option is given.
* Document that `--output-directory` option will empty the target directory.

**Comment by cppforlife** [comment]
> Document that --output-directory option will empty the target directory.

any ideas where to place this note in the docs?

**Comment by nimakaviani** [comment]
maybe a separate section on outputs?

Under the top level documentation here: https://github.com/k14s/ytt/blob/develop/docs/README.md#documentation

**Comment by cppforlife** [comment]
updated https://github.com/k14s/ytt/blob/develop/docs/ytt-data-values.md and added https://github.com/k14s/ytt/blob/develop/docs/outputs.md. thanks for letting us know!
