### ISSUE TITLE
error when checking non-existent data.values attribute via hasattr

### ISSUE THREAD

**Issue by davewalter** [k14s/ytt#56]
Hi,

We (CF Release Integration) use the `hasattr` helper function as part of our tooling to generate a Concourse pipeline from a template and an input file. One of the things we do is add debug jobs if the "debug" attribute is set for a release in the input file for the pipeline. For example, given this template snippet (greatly simplified):
```
#@ load("@ytt:data", "data")
---
groups:
- name: #@ r.name
  jobs:
  #@ for r in data.values.releases:
  - #@ "update-" + r.name
  #@ if hasattr(r, "debug"):
  - #@ "destroy-" + r.name + "-debug-env"
  #@ end
  #@ end
```
and this input file:
```
#@data/values
---
releases:
- name: binary-buildpack
  repository: cloudfoundry/binary-buildpack-release
  debug: true
```
running `ytt -f .` generates the following pipeline yml:
```
groups:
- name: binary-buildpack
  jobs:
  - update-binary-buildpack
  - destroy-binary-buildpack-debug-env
```
During normal operation, we do not need to run in "debug" mode, so we simply remove the `debug` attribute from the release in the input file and those jobs are not rendered in the pipeline manifest:
```
groups:
- name: binary-buildpack
  jobs:
  - update-binary-buildpack
```
However, since v0.19.0 of `ytt` was released, we started receiving the following error instead of the expected generated pipeline yml:
```
Error:
- interface conversion: interface is nil, not starlark.Value
```
If I add the `debug: x` attribute to the input file, then everything works as expected with the latest version of `ytt` (v0.20.0 as of the time of writing), but we were hoping to not have to do this.

Please let me know if you have any questions about this issue.

Thanks,
Dave

**Comment by cppforlife** [comment]
@davewalter will take a look...

**Comment by cppforlife** [comment]
simpler version:

```
#@ load("@ytt:data", "data")

#@ if/end data.values.something:
---
```

```
#@data/values
--- {}
```

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/commit/57b3af6a9bbafb45da3ad60a979a9acd48cffb9a. will be included in upcoming release.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.21.0. thanks for reporting!
