### ISSUE TITLE
Schema check should consider all layers of data values together

### ISSUE THREAD

**Issue by blc1996** [k14s/ytt#581]
**What steps did you take:**

We have usecases for values that are required, but has null default.

1. Define a field in `schema.yaml` which is not nullable
2. The default `values.yaml` has a null value for this field
3. Add an additional data value overlay which sets the value of this field
4. YTT still thows error saying field is null

**What happened:**
config/values.yaml
```
#@data/values
#@overlay/match-child-defaults missing_ok=True

---
key: null
```

config/schema.yaml
```
#! schema.yaml

#@data/values-schema
#@schema/desc "OpenAPIv3 Schema"
---
#@schema/desc "test key"
key: ""
```

values_overlay.yaml
```
#@data/values
#@overlay/match-child-defaults missing_ok=True

---
key: "test"
```

Running command
```
$ ytt -f config -f values_overlay.yaml 
ytt: Error: Overlaying data values (in following order: values.yaml, values_overlay.yaml): 
One or more data values were invalid
====================================

values.yaml:
    |
  5 | key: null
    |

    = found: null
    = expected: string (by schema.yaml:7)
    = hint: is the default value set using @schema/default?
```

Looks like the schema is checked against all data values files one by one.

**What did you expect:**
Schema check should consider all layers of data values together, so this case should work

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- ytt version (use `ytt --version`): ytt version 0.38.0
- OS (e.g. from `/etc/os-release`): MacOS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by blc1996** [comment]
Stop using `null`, instead use empty string as default value will solve the issue.

**Comment by pivotaljohn** [comment]
As you alluded to, empty values in Python/Starlark are falsey. And these are the preferred way to express "unset".

Further, given that the values given in the schema are your library's defaults, no need to supply a separate data values file.

The working version looks something like this:

```
#! schema.yaml

#@data/values-schema
#@schema/desc "OpenAPIv3 Schema"
---
#@schema/desc "test key"
key: ""
```

```
#! values_overlay.yaml

#@data/values
---
key: "test"
```
