### ISSUE TITLE
[lang] allow load() to accept non-literal strings

### ISSUE THREAD

**Issue by guludo** [k14s/ytt#59]
Hi!

It would be nice to be able to pass expressions (that use variables) to the `load()` statement. Currently only string literals are allowed. Is that a limitation of `starlark` or was it a design choice of `ytt`?

**My case**
I have a project where I'll be using functions for creating parts of the configuration and those functions have a different implementation depending on the "configuration variant" I'm using. In order to import the correct version of the function I wanted to use something `load(variant + '.star', 'my_function')`, where `variant` is a variable storing the name of my configuration variant.

**Comment by nimakaviani** [comment]
Having string literals as the arguments for `load()` is constrained by starlark:

starlark docs: https://github.com/bazelbuild/starlark/blob/develop/spec.md#load-statements
> A load statement requires at least two "arguments". The first must be a literal string; it identifies the module to load.

**Comment by cppforlife** [comment]
^ filed issue above against starlark-go

**Comment by cppforlife** [comment]
@guludo starlark team provided an explanation of why they do not support this feature (https://github.com/google/starlark-go/issues/246#issuecomment-543308537). even though it's a little bit surprising to receive that error message, i tend to agree with their reasoning on this issue.

given your use case i could see some alternative solutions that may work for you. for example, something like this:

config.yml
```yaml
#@ load("funcs.star", "funcs")
#@ load("@ytt:data", "data")
key: #@ funcs["func1"]()
``` 
funcs.star
```python
def func1(): return 123
def func2(): return 456
funcs = {"func1": func1, "func2": func2}
```

**Comment by guludo** [comment]
Hi @cppforlife 

Yep, their explanation makes sense.

Thank you for going through the trouble of raising an issue there!

I'm closing this now.
