### ISSUE TITLE
How to compose many flavors of many components? (aka carvelizing my Kustomize)

### ISSUE THREAD

**Issue by btheado** [k14s/ytt#603]
I have a k8s project with a large number of components currently defined using kustomize. The directory structure is something like this:

* component1
    * kustomization.yaml
    * deployment.yaml
    * configmap.yaml
    * etc.
* component2
    * kustomization.yaml
    * etc.
* ...
* componentN
* base
    * kustomization.yaml - compose together many of the components by referencing ../component1, ../component2, ..., ../componentN in the bases section
* clusters
    * dc1/namespace1
        * kustomization.yaml - includes ../../../base in the bases section and includes per-cluster strategic merge patches
        * patch-file1.yaml
        * patch-file2.yaml
    * dc2/namespace2
        * kustomization.yaml - includes ../../../base in the bases section and includes per-cluster strategic merge patches
        * patch-file1.yaml
        * patch-file2.yaml
    * ...
    * dcN

The base directory groups many components together so the per-cluster `kustomization.yaml` files do not have to reference every individual component. But individual components can be left out of the base and referenced directly from per-cluster if needed. Many of the components need per-cluster patch files.

One nice feature I like about this setup is when it comes time to run `kubectl diff` or `kubectl apply`, I only need to pass one input to `kubectl kustomize`.  That input is the directory corresponding to the cluster I'm deploying to. For example `kubectl kustomize clusters/dc1/namespace1 | kubectl --context dc1 diff -f -`. The yaml output of the kustomize command contains all the yaml for the entire namespace.

With this approach, I don't have to think about which components are being deployed or any other details. All details are captured and encapsulated within the kustomization.yaml files. I only need to make sure the directory given on the kustomize command-line matches the `--context` argument in kubectl.

Is there a way to have this kind of large-scale composition using ytt? Such that I can have a single ytt command encapsulate all the complexities (i.e. `ytt -f clusters/dc1/namespace1`)?

Maybe all the directories can be placed inside of `_ytt_lib` and `library.get` can be used with a path starting with `/` in order to access directories relative to the `_ytt_lib` root? If so, then I'm having trouble piecing together exactly how to do it. Any tips?

**Comment by pivotaljohn** [comment]
Yeah. Sounds like you're headed in a useful direction.

One approach looks like this:

```
├── clusters
│   ├── dc1
│   │   └── namespace1
│   │       ├── ns-config.yml
│   │       └── overlay.yml
│   └── dc2
│       └── namespace2
│           ├── ns-config.yml
│           └── overlay.yml
└── components
    ├── _ytt_lib
    │   ├── component1
    │   │   └── deployment.yml
    │   ├── component2
    │   │   └── deployment.yml
    │   └── component3
    │       └── deployment.yml
    └── components.lib.yml
```
and you'd include both the set of component libraries and the cluster config:
```
$ ytt -f components -f clusters/dc1/namespace1
```

where:
- each cluster config loads in the components it wants:
    ```
    #! ./clusters/dc1/namespace1/ns-config.yml
    #@ load("@ytt:template", "template")
    #@ load("components.lib.yml", "base", "component3")

    --- #@ template.replace(base())
    --- #@ template.replace(component3())
    ```
    ```
    #! ./clusters/dc2/namespace2/ns-config.yml
    #@ load("@ytt:template", "template")
    #@ load("components.lib.yml", "base")

    --- #@ template.replace(base())
    ```
    and their patches/overlays will naturally apply. \
    For example:
    ```
    #! ./clusters/dc1/namespace1/overlay.yml

    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.all, expects="1+"
    ---
    #@overlay/match missing_ok=True
    namespace: namespace1
    ```
- each component is a [library](https://carvel.dev/ytt/docs/v0.39.0/lang-ref-ytt-library/), all of which are enumerated in `./components/components.lib.yml`:
    ```
    #@ load("@ytt:library", "library")
    #@ load("@ytt:template", "template")

    #@ def base():
    --- #@ template.replace(library.get("component1").eval())
    --- #@ template.replace(library.get("component2").eval())
    #@ end

    #@ def component3():
    --- #@ template.replace(library.get("component3").eval())
    #@ end
    ```
- you do just a smidge of composition on the command-line, loading both _both_ the collection of component libraries and the desired cluster config:
    ```
    $ ytt -f components -f clusters/dc1/namespace1
    kind: Deployment
    metadata:
      name: component1
    namespace: namespace1
    ---
    kind: Deployment
    metadata:
      name: component2
    namespace: namespace1
    ---
    kind: Deployment
    metadata:
      name: component3
    namespace: namespace1
    ```
    ```
    $ ytt -f components -f clusters/dc2/namespace2
    kind: Deployment
    metadata:
      name: component1
    namespace: namespace2
    ---
    kind: Deployment
    metadata:
      name: component2
    namespace: namespace2
    ```

What do you think? 🤔 

---
Pro-Tip: think of each `-f` argument is kinda like a mount point to an internal filesystem. You can get a peek into how it all lays out by looking at the first section of output from the `--debug` flag (writes to stderr):

```
$ ytt -f components -f clusters/dc1/namespace1 --debug 2>&1 | head -n 25
-  (private false)
  files:
  - components.lib.yml
  - ns-config.yml
  - overlay.yml
  libraries:
  - _ytt_lib (private true)
    files:
      <none>
    libraries:
    - component1 (private false)
      files:
      - _ytt_lib/component1/deployment.yml
      libraries:
        <none>
    - component2 (private false)
      files:
      - _ytt_lib/component2/deployment.yml
      libraries:
        <none>
    - component3 (private false)
      files:
      - _ytt_lib/component3/deployment.yml
      libraries:
        <none>
```

Paths in `load()` calls traverse _this_ structure.

**Comment by btheado** [comment]
> What do you think?

Outstanding. Thanks for the excellent response. I find it very enlightening.

> you do just a smidge of composition on the command-line, loading both both the collection of component libraries and the desired cluster config

Seems like a very small price to pay.  After your explanation It occurs to me it would probably also be possible to move the clusters directory in order to eliminate even that small command-line composition. Something like this (probably the top-level dir would have a better name than `components` since now it has everything):

```
└── components
    ├── _ytt_lib
    │   ├── dc1
    │   │   └── namespace1
    │   │       ├── ns-config.yml
    │   │       └── overlay.yml
    │   └── dc2
    │       └── namespace2
    │           ├── ns-config.yml
    │           └── overlay.yml
    │   ├── component1
    │   │   └── deployment.yml
    │   ├── component2
    │   │   └── deployment.yml
    │   └── component3
    │       └── deployment.yml
    ├── dc1-namespace1.yml
    ├── dc2-namespace2.yml
    └── components.lib.yml
```

With the right contents, `ytt -f components/dc1-namespace1.yml` should be able do what I want. I plan to play with all these ideas and see how they work out.

> looking at the first section of output from the `--debug` flag 

This is gold. I hadn't noticed that option. The output looks very useful.

One thing I'm not sure about is if the data values for the various components need to be namespaced in order to avoid name collisions. Is it good practice to include a `component1` prefix for any data values used by component1? I haven't gotten far enough into using data values to know for sure whether there is a "global" namespace for their names.

**Comment by pivotaljohn** [comment]
> Outstanding. Thanks for the excellent response. I find it very enlightening.

woohoo! 🎉 

> Something like this (probably the top-level dir would have a better name than components since now it has everything):

When we took a run at this kind of structure, we got stuck in the part where `ytt` (by design) isolates private libraries from their parents (here, that `./components/_ytt_lib/dc1/namespace1/ns-config.yml` does _not_ have visibility into its sibling libraries like `./components/_ytt_lib/component1`. Each private library can be thought of as a separate instance of a [`ytt` pipeline](https://carvel.dev/ytt/docs/v0.39.0/how-it-works/#the-ytt-pipeline), in isolation.

We're eager to hear about what you learn as you poke, nudge, and pull at this.

---

> One thing I'm not sure about is if the data values for the various components need to be namespaced in order to avoid name collisions.

No need. Each private library has its own data values, both in name and value. 👍🏻  
Here's a nice "[index](https://carvel.dev/ytt/docs/v0.39.0/ytt-data-values/#library-data-values-merge-order)" of all the ways that one can set data values on a library.

It seems to really come down to what kind of "API" you want to present those who are using your ytt Library:
- Do you want them to be aware of the details of how components are shaped/configured? \
  Encouraging [library references](https://carvel.dev/ytt/docs/v0.39.0/lang-ref-ytt-library/#libraryref) are a great way to allow them to opt-in to "advanced configuration".
- Would you rather they have a simplified interface that is more intuitive from the problem space? \
  You might define a section of data values for a component in the root library's schema and then [set those on the component library](https://carvel.dev/ytt/docs/v0.39.0/lang-ref-ytt-library/#instancewith_data_values) (perhaps after transforming them, if need be) just before you `.eval()` it.
- and these options aren't mutually exclusive. If you can solve 80% of the configuration cases without too much obfuscation with the second option and allow the other 20% to be for those who have the need/motivation to dig in deeper to get more familiar with the actual underlying Kubernetes manifests (an energized view of DevOps is exactly this — that those who build and those who deploy _take care_ of those details, so we encourage it).

**Comment by btheado** [comment]
> here, that ./components/_ytt_lib/dc1/namespace1/ns-config.yml does not have visibility into its sibling libraries like ./components/_ytt_lib/component1

Yes and I was thinking the top-level `dc1-namespace1.yml` file would compose the two together since the siblings can't see each other. I also mistakenly thought the `ytt -f components/dc1-namespace1.yml` command would be enough. But by giving a single file as input, the subdirs become invisible. A second cli arg would need to be re-introduced: `ytt -f components/dc1-namespace1.yml -f components/_ytt_lib`. Your proposal is better than that, IMO.

> Pro-Tip: think of each -f argument is kinda like a mount point to an internal filesystem

Even with your tip, it took me a bit to fully understand when I tried something that didn't work. I'm not sure I would have figured it out without the aid of the `--debug` output. I naively thought that `ytt -f components -f clusters` would be able to output the yaml for both clusters. But running it that way changed the mount location of `ns-config.yml` and resulted in `cannot load components.lib.yaml`. Now I think I really understand it (fingers crossed :-)).

Thanks for the help.
