### ISSUE TITLE
Annotate a Data Value with validation

### ISSUE THREAD

**Issue by pivotaljohn** [k14s/ytt#604]
**Given** a Data Values document (and only a Data Values document), annotated with a validation rule:

```yaml
#! values.yml

@data/values
---
#@assert/validate ("a non-empty string", lambda v: assert.fail("length = {}", len(v)) if len(v) > 0 else None)
username: ""
```

### Scenario: Invalid Data Value

**Given** the final Data Value's value does not satisfies the rule:
**When** `ytt` runs
**Then** reports a Data Values violation error message:

```
$ ytt -f values.yml --data-values-inspect
ytt: Error: One or more data values were invalid:
- "adminPort" requires a valid value: a non-empty string; length = 0 (validated by values.yml:6).
```

### Scenario: Valid Data Value

**Given** the final Data Value's value satisfies the rule:
**Then** no error message is displayed.

```
$ ytt -f values.yml -v username=alice --data-values-inspect
username: alice
```
Note: validations are checked _after all_ overlays have been applied.

---
Notes:
- we show evaluating just one rule on one data value. We'll ultimately support evaluating multiple rules per Data Value, and evaluate validity of as many data values as possible.
- one has to use the feature to opt-in. In a near-future story, we'll implement a feature flag.
- while assertions _work well with_ schema, a current design goal is to implement them orthogonally: this story establishes the core feature of validation; a subsequent story (#611) covers declaring a validation within schema.
- we anticipate users seeing "violation messages" more often and in larger volume; hence the more compact error message format being highlighted. Feel free to play with the format and verbiage — what's given in the story is a "thoughtful suggestion" not the final word.
- https://github.com/vmware-tanzu/carvel/blob/004-schema-validation/proposals/ytt/004-schema-validation/README.md#assertvalidate

**Comment by gcheadle-vmware** [comment]
Should the `#@assert/validate` annotation work on data values contained in a data values file? 
```
#@ load("@ytt:assert", "assert")
@data/values
---
#@assert/validate ("a non-empty string", lambda v: assert.fail("length = {}", len(v)) if len(v) > 0 else None)
username: "andrew"
```

**Comment by pivotaljohn** [comment]
> Should the #@assert/validate annotation work on data values contained in a data values file?

Insightful question. And I think you intuition is right: that an `@assert/validate` should mean the same thing everywhere (just like an `@overlay/match` does).

This points to a need to be able to _declare the need for_ an `@assert/validate` (specifically in a document containing schema).

Folding this into the overall proposal.

🙌🏻

**Comment by pivotaljohn** [comment]
Split this story into two:
- _this_ story covers the `@assert/validate` annotation (and required plumbing)
- #611 is scoped to emitting `@assert/validate` annotations, given a schema declaring validations.

**Comment by gcheadle-vmware** [comment]
Closing since follow up PR was merged.
