### ISSUE TITLE
🐦 Please tweet about v0.40.0 release 🚀 

### ISSUE THREAD

**Issue by adriens** [k14s/ytt#607]
Hi folks, could you please tweet about [v0.40.0](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.40.0) ❔ So I'll can RT it 🙏

**Comment by cari-lynn** [comment]
Hey! It should be tweeted after the weekend, when our social media person is back 🙂

**Comment by adriens** [comment]
🙆‍♂️ i'm waiting for you.
Have a nice week-end 🍸 🏖️ ☺️

**Comment by microwavables** [comment]
Here ya go! https://twitter.com/carvel_dev/status/1496184927007694849?s=20&t=mOF4eQhI0OZPclY1YclECg

THank you @adriens !
