### ISSUE TITLE
🐦 Please tweet about v0.37.1 release 🎆 

### ISSUE THREAD

**Issue by adriens** [k14s/ytt#616]
... so I can RT it to announce chocolatey release cf https://github.com/adriens/chocolatey-ytt/issues/16

**Comment by pivotaljohn** [comment]
Hey @adriens!  So, every once in a great while, we'll do one of these patch releases. They are intended for our Long Term Support efforts. They will always contain backports of fixes that are already available in a later version of the tool.

No need to bundle up this release. 👍🏻

**Comment by adriens** [comment]
:+1:
