### ISSUE TITLE
The video "Discover ytt in [video](https://youtu.be/KbB5tI_g3bo)" is private 

### ISSUE THREAD

**Issue by ameena007** [k14s/ytt#618]
The video "Discover ytt in [video](https://youtu.be/KbB5tI_g3bo)" is private.

Can it be made public,  So that people can learn more about ytt via the video?

**Comment by cari-lynn** [comment]
Hey, thanks for submitting this! There is an open [PR](https://github.com/vmware-tanzu/carvel-ytt/pull/614) to fix this. Meanwhile, here's the [link](https://youtu.be/WJw1MDFMVuk) directly.

**Comment by pivotaljohn** [comment]
That PR was merged. 👍🏻

**Comment by ameena007** [comment]
Wow !!! thank a lot!
