### ISSUE TITLE
Provide api call to exclude files from output.

### ISSUE THREAD

**Issue by GrahamDumpleton** [k14s/ytt#626]
**Describe the problem/challenge you have**

One can conditionally exclude a single YAML file from being output by using:

```
#@ load("@ytt:data", "data")

#@ if data.values.include_file:
---
xxx: 1
#@ end
```

This even works when you use ``--output-files`` and not even an empty file is created.

When you have a whole directory of files, possibly of multiple levels, it is inconvenient to modify every single file to add into a conditional check.

There may well be a convoluted way of using overlays to effectively remove whole files by path (not sure if can be done by path), but even then that still only helps for YAML files.

**Describe the solution you'd like**

What would be nice to be able to do is dynamically exclude whole files, whether they be marked as yaml-template, text-plain, text-template, from output using an API call in Starlark code.

This would be useful when using `ytt` as a template engine to reconstruct a directory of files using ``--output-files`` as you could exclude sets of files you didn't want in generated output based on a data value.

The API call would be akin to applying a file mark of `exclude-from-output`, from within Starlark code.

Worth noting is that because of ordering, this probably couldn't preclude files under the paths you want to exclude being processed and so would just mean, whatever the output from the files was, just don't pass it through in the output or write to disk if using `--output-files`. I can't see a way of being able to avoid the processing as by time API call is made, you may have already processed the files you want to exclude.

For the API call, would want the argument to be treated as `path` is when setting file marks. So if the new API call were `exclude_from_output()`, would be possible to do:

```
exclude_from_output("file.ext")
exclude_from_output("dir/file.ext")
exclude_from_output("*.ext")
exclude_from_output("dir/*.ext")
exclude_from_output("**/*.ext")
exclude_from_output("dir/*")
exclude_from_output("dir/**") # Not sure if this would be different to dir/*.
```

**Anything else you would like to add:**

Nope.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
We're gonna have to chew on this one for a bit, @GrahamDumpleton.

At first blush, it has the potential to bring along a non-trivial chunk of complexity:
- it's a poor UX for a user to attempt to exclude a file from output but receive an error message if the template fails;
- we've deliberately pruned this scenario in our `for-output` file-mark (i.e. one can only _include_ a file for output; but not _exclude_ a file from output).

But we see/hear your need and pondering approaches that could meet it. 🤔

**Comment by GrahamDumpleton** [comment]
This one was definitely a little bit pie in the sky at this point. Just seemed like an interesting idea for more complicated template usage when using ``--output-files``. If only given some thought at this point, that is still fine.

**Comment by pivotaljohn** [comment]
I'm not seeing an approach, here, that wouldn't introduce disproportionate interface and implementation complexity (especially the latter).

One might also say that this aspect of templating: deciding which files are to be included for output is an aspect of the task that sits _juuuuust_ in front of the templating tool.

Either way, closing, for now.
