### ISSUE TITLE
Error when handling files which use multiple levels of symlinks.

### ISSUE THREAD

**Issue by GrahamDumpleton** [k14s/ytt#643]
**What steps did you take:**

In Kubernetes mount a configmap or secret into a container. In the container run `ytt` on a file in the projected volume.

**What happened:**

You get an error:

```
$ ytt -f /opt/xxx/config/workshop.yaml
ytt: Error: Checking symlink file '/opt/xxx/config/workshop.yaml':
  Expected symlink file '/opt/xxx/config/workshop.yaml' -> '/opt/xxx/config/..2022_04_09_00_13_38.3873050756/workshop.yaml' to be allowed, but was not
```

It appears to be due to two levels of symlinks.

```
$ ls -las /opt/xxx/config/workshop.yaml
0 lrwxrwxrwx 1 root root 20 Apr  9 00:13 /opt/xxx/config/workshop.yaml -> ..data/workshop.yaml
$ ls -las /opt/xxx/config/..data
0 lrwxrwxrwx 1 root root 32 Apr  9 00:13 /opt/xxx/config/..data -> ..2022_04_09_00_13_38.3873050756
$ ls -las /opt/xxx/config/..data/workshop.yaml 
4 -rw-r--r-- 1 root root 1474 Apr  9 00:13 /opt/xxx/config/..data/workshop.yaml
```

If you run:

```
 ytt -f /opt/xxx/config/..data/workshop.yaml
```

it works fine.

**What did you expect:**

Expect it to not break on multiple levels of symlinks.

**Anything else you would like to add:**

This is quite annoying when want to use `ytt` on files mounted into a Kubernetes container from a configmap or secret.

One is forced to copy the files out of the project volume into the container file system before processing them through `ytt`. Alternatively, you have to rely on the implementation artifact in Kubernetes that files are accessible through the `..data` subdirectory of the projected volume, thus resulting in only a single level of symlinks.

**Environment:**

```
$ ytt version
ytt version 0.40.0
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

cc @jorgemoralespou

**Comment by GrahamDumpleton** [comment]
In a Slack discussion the options `--allow-symlink-destination` and `--dangerous-allow-all-symlink-destinations` were pointed out. The overall way that symlinks are handled, including these options is rather hostile to a user though and suggests that a user doesn't know what they are doing with the suggestion that it is dangerous to use symlinks. These options are only mentioned in the help strings for `ytt` and there seems to be no mention at all in the documentation about how symlinks are handled and why they would be a problem.

Looking at the bigger problem, the only reason I can see why symlinks are dealt with like this is because of the problem of cycles in symlinks. That is, a symlink in a child directory pointing at a parent directory. There are better ways to deal with that problem though which means the command would work for typical use cases with symlinks without the user being confronted with confusing error messages and a need to search for these options.

I would suggest that the better way to handle this would be that instead of `--allow-symlink-destination` and `--dangerous-allow-all-symlink-destinations` there is an inbuilt default for a maximum depth of symlinks that would be traversed before an error is given. This could be as little as 5 and should be enough to cover all typical use cases for where a user may use symlinks themselves, or situations like projected volumes in Kubernetes. So unless that maximum depth were hit, `ytt` would always traverse symlinks and if the limit were reached it could give a clear error message pointing at an option such as `--maximum-symlink-depth` so it could be overridden.

Making such a change would be better and more user friendly. The current options come across as being a stop gap measure to avoid problems with symlink loops but do not provide a good experience for the user.

If the reason this behaviour was implemented this way was not symlink loops can someone explain what the problem with symlinks is?

**Comment by cari-lynn** [comment]
Hey @GrahamDumpleton , thanks for creating this. We want to avoid causing frustration around this and want ytt to work well with Kubernetes. 

The background behind disallowing symlinks by default is for security. The security docs [here](https://carvel.dev/ytt/docs/v0.40.0/security/) give a overview:

> * malicious template code
code tries to load file contents from sensitive locations
A: templating is constrained to seeing only files explicitly specified by the user via -f flag. unless user is tricked to provide sensitive file as input, template code is not able to access it. in other words, template runtime does not have facilities to access arbitrary filesystem locations.

An example of this risk is consuming a 3rd party ytt library and executing templates written by someone else, ytt doesn't allow it to symlink to some sensitive file and have it accessed in templates. 

This approach has come from being the most secure by default, and then providing overrides (like the `--allow-symlink-destination`) to intentionally expand the security surface of the tool as the need arises. 

Given that this is causing you frustration, can you describe what would have made this a less irritable experience? Would describing the security aspect or suggesting the flag to use in the error have helped?

Also, considering this in the context of Kubernetes is important. Kubernetes does mount files as symlinks, there may be a way around this, but I am not sure. Are you able to use the flags (`--allow-symlink-destination`) to simply solve this problem?

**Comment by GrahamDumpleton** [comment]
In the context of that I can then understand. The problems are then:

* There is no good hint in the error message as to what to do, be that references to command line options or keywords to search in documentation.
* There is no where in the documentation that mentions the term `symlink`, which is pretty well the first thing one is going to search for if you realise the issue is related to symlinks.
* There is no where in the documentation which mentions those specific command line options, and the rational for them existing and why things behave this way.
* More specifically, that section of the security page doesn't mention the term `symlink` nor those options so would never be found when searching the docs for anything related to this issue.

So for now a better error message with reference to options or something to understand what to do. And better use of terms like `symlink` in docs where appropriate along with online documentation on the options.

And no `--allow-symlink-destination` doesn't work in this case because of multiple levels of symlinks.

```
$ ytt -f /opt/xxx/config/workshop.yaml 
ytt: Error: Checking symlink file '/opt/xxx/config/workshop.yaml':
  Expected symlink file '/opt/xxx/config/workshop.yaml' -> '/opt/xxx/config/..2022_04_11_22_54_42.4157872851/workshop.yaml' to be allowed, but was not
[~/exercises] $ ytt -f /opt/xxx/config/workshop.yaml  --allow-symlink-destination=true
ytt: Error: Checking symlink file '/opt/xxx/config/workshop.yaml':
  Expected symlink file '/opt/xxx/config/workshop.yaml' -> '/opt/xxx/config/..2022_04_11_22_54_42.4157872851/workshop.yaml' to be allowed, but was not
```

You have to use use `--dangerous-allow-all-symlink-destinations=true` and then it works.

**Comment by cari-lynn** [comment]
Thanks for these suggestions, we can definitely improve the documentation to be searchable and the error message here. 👍 

As for the solution you mentioned, `--allow-symlink-destination` takes the filename you want to allow a symlink to, so it would look like: `--allow-symlink-destination /opt/xxx/config/..2022_04_11_22_54_42.4157872851/workshop.yaml` and you can repeat the flag for nested symlink destinations.

**Comment by GrahamDumpleton** [comment]
Ahhh, I saw `--allow` and assumed it was a boolean option like `--dangerous-allow-all-symlink-destinations` is. Was confused why it still asked for an argument. :-)

So yes, it seems I can do:

```
ytt -f /opt/xxx/config/workshop.yaml --allow-symlink-destination /opt/xxx/config
```

In other words you can specify any parent directory and doesn't have to be the specific file which is the target.

So is things like this which would be helpful in the docs, ie., that can specify a parent directory. Where using `--dangerous-allow-all-symlink-destinations` is the same as having run:

```
ytt -f /opt/xxx/config/workshop.yaml --allow-symlink-destination /
```

So knowing that `--allow-symlink-destination` can be given a parent directory, and where I know the provenance of everything under that parent directory, am more than happy now. Thanks.

**Comment by cari-lynn** [comment]
Great! I'm glad that worked. We definitely need documentation on this 😄 . I made a PR to make it clear in the documentation FAQ and security page. Let me know if there's anything missing. https://github.com/vmware-tanzu/carvel/pull/413

I'll create a separate issue for updating the error text to hint at how to use symlinks and close this issue if that's alright with you.

**Comment by GrahamDumpleton** [comment]
Looks good. I hope the search feature will still find `symlink` when except for the option name is always plural. :-)

Feel free to close.
