### ISSUE TITLE
data-values-file should accept an entire directory

### ISSUE THREAD

**Issue by voor** [k14s/ytt#657]
**Describe the problem/challenge you have**
I keep my values files in a directory, which I'm very sure contains only values files.  I don't have a lot of control over the naming of the files in that folder.

**Describe the solution you'd like**
I understand that currently 
`ytt --data-value-file /values`
does not work, because it expects:
`ytt --data-value-file /values/file.yaml --data-value-file /values/file2.yaml --data-value-file /values/file3.yaml`
It would be nice if it did accept the directory, and just implicitly applied a filemark to everything in that directory to then be a data value file.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

Request originated in this [#carvel thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1651167583289939).

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
Yeah, this is a particularly handy feature for when `ytt` is in a sandwich of automation and it's hard/infeasible to enumerate the filenames. 👍🏻 

As a guiding principle, let's aim for `--data-values-file` to enumerate and sort the files from the filesystem identically to `--file`:
- it's not just the named directory, but all sub-directories, recursively;
- the sort order is alphabetical of the _entire paths_.

On the nose: `--data-values-file dir-with-plain-values-files/` should produce the exact same results as `--file dir-with-values-overlays-annotated-for-plain-merge/`.

The point being to keep the story about how directories as inputs are handled as consistent as possible.

**Comment by voor** [comment]
Hurray!
