### ISSUE TITLE
#@ load(...) is not working

### ISSUE THREAD

**Issue by lionelvillard** [k14s/ytt#7]
`example-load-custom-library` does not seem to be working. I renamed the directory as instructed but I still get this error:

```
Error: 
- cannot load @github.com/k14s/test-lib:funcs.star: Could not find private library (directory '_ytt_lib' missing?)
    config.yml:11 in <toplevel>
     L #@ load("@github.com/k14s/test-lib:funcs.star", "testfunc")
```

tree . :

```
.
├── _ytt_lib
│   └── github.com
│       └── k14s
│           └── test-lib
│               └── funcs.star
└── config.yml
```

Is it possible to also load a file in the same directory, eg: 

```
#@ load("funcs.lib.yml", "source")
```

tree .: 

```
.
├── config.yml
└── funcs.lib.yml
```

ytt version: 0.3.0

**Comment by cppforlife** [comment]
hey,

i just cloned the repo and ran 
```bash
pivotals-iMac-2:ytt pivotal$ mv examples/playground/example-load-custom-library/_ytt_lib{1,}
pivotals-iMac-2:ytt pivotal$ ytt t -R -f examples/playground/example-load-custom-library/
result: 123
```

im guessing you are running different combination of `-R` and `-f` flags?

> Is it possible to also load a file in the same directory, eg:

absolutely, see this example here: https://get-ytt.io/#example:example-load, or run 
```bash
pivotals-iMac-2:ytt pivotal$ ytt t -R -f examples/playground/example-load
func1_key:
  name: max
  cities:
  - SF
...
```

**Comment by lionelvillard** [comment]
I'm running `ytt t -R -f config.yml`. I would expect to get the same result.

**Comment by cppforlife** [comment]
i see. yup, you will have to change your invocation to include files that are allowed to be loaded. ytt template command limits access to directories and files that are specified via -f flag, to make execution "self-contained" and disallow templates reaching for random files.

**Comment by cppforlife** [comment]
ytt should probably improve error message though...

**Comment by cppforlife** [comment]
closing this issue. filed a separate issue to improve error msg (https://github.com/k14s/ytt/issues/9)
