### ISSUE TITLE
Document overlay/replace's or_add kwarg

### ISSUE THREAD

**Issue by mamachanko** [k14s/ytt#740]
**Describe the problem/challenge you have**

I am reading ytt's code and browsing its issues. There's [a mention of](https://github.com/vmware-tanzu/carvel-ytt/issues/575) and [code for](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/yttlibrary/overlay/replace_annotation.go#L17) `#@overlay/replace or_add=bool`, but it's not mentioned by [its docs](https://carvel.dev/ytt/docs/v0.42.0/lang-ref-ytt-overlay/#overlayreplace):
![image](https://user-images.githubusercontent.com/1182927/189354885-94307ad6-3a16-4c09-9176-c28b86a859b3.jpeg)

**Describe the solution you'd like**

Documentation for `or_add` would be great, or a notice within the code base that it is an internal API.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
Thank you for capturing this, @mamachanko.

@cppforlife fixed this in https://github.com/vmware-tanzu/carvel/commit/48fbdb1c6df514ae8c0e073630e0716ed97eb758
