### ISSUE TITLE
`ytt` provides a `semver` library

### ISSUE THREAD

**Issue by mstergianis** [k14s/ytt#760]
**Describe the problem/challenge you have**
I use `ytt` to package up software to be shipped and run by other people. That means that the people that run the software run it in a variety of environments and for some feature flags it's intuitive to have the operator declare a version of software that they're using, in order to tune the installation to the versions they use. For example, running on different versions of kubernetes (`1.23.x` vs `1.24.x`) might lead you to change the kubernetes resources you create, or the parameters you provide to those kubernetes resources.

**Describe the solution you'd like**
A `semver` library as part of the standard library for ytt. It could even probably be a thin wrapper over something like [Masterminds/semver](https://github.com/Masterminds/semver)

**Anything else you would like to add:**
I thought about writing this library in starlark directly, but I find it difficult to distribute ytt libraries (without inventing something like NPM...)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by mamachanko** [comment]
@mstergianis there's a proposal for `@ytt:semver`: https://github.com/vmware-tanzu/carvel/pull/539

**Comment by mstergianis** [comment]
Lovely! I'll close this out if that's already being tracked there. I only checked for existing issues in this project :joy:
