### ISSUE TITLE
Marking file as type "starlark" fails to allow it to be treated as a Starlark file.

### ISSUE THREAD

**Issue by jtigger** [k14s/ytt#786]
Reported by @Zebradil in [#carvel](https://kubernetes.slack.com/archives/CH8KCCKA5/p1672256429943339). Thank you. 🙏 

**Steps to Reproduce**

1. create the file `star.test1`:
    ```python
    print(42)
    ```
2. by default, `ytt` regards this file a "unknown type" or "data" and so it is not evaluated (expected):
    ```
    $ ytt -f test.star1
    ```
3. rename the file to `.star`, and  `ytt` regards this file a "starlark" file and evaluates it (expected):
    ```
    $ ytt -f test.star
    42
    ```
4. mark the file directly as type `starlark`, and `ytt` _should_ regard this file a "starlark" file and evaluate it:
    ```
    $ ytt -f test.star1 --file-mark='test.star1:type=starlark'
    ```
    _(but it does not 🛑)_

**Anything else you would like to add:**

Key symptom is the way in which a file is determined to be a "library file":

https://github.com/vmware-tanzu/carvel-ytt/blob/92f7de5ca3a11dfa5f341134f15cbc0a6b0fb31f/pkg/files/file.go#L242-L251

which only regards the extension of a file.

- what can be done to respect the file mark for `starlark` type files?
- should there be a file mark for YAML files that are _also_ "library file"s (e.g. `type=yaml-library`)?

**Environment:**

- ytt version (use `ytt --version`): 0.44.0 (likely introduced some versions back)
- OS (e.g. from `/etc/os-release`): (all)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by Zebradil** [comment]
Thank you for creating the issue.

I have noticed that the code on the step 3 is incorrect. It should be something with the following:

```
ytt -f test.star
```

**Comment by jtigger** [comment]
Whops! Thanks, @Zebradil. I updated the description.
