### ISSUE TITLE
ytt version displays wrong version

### ISSUE THREAD

**Issue by alchimere** [k14s/ytt#787]
**What steps did you take:**

```
go install github.com/vmware-tanzu/carvel-ytt/cmd/ytt@v0.44.0
ytt version
ytt --version
```

**What happened:**

Displays the following version:

```
ytt version develop
```

**What did you expect:**

```
ytt version v0.44.0
```

**Anything else you would like to add:**

This behavior prevents us to verify in scripts we are running the expected version of the binary with something like that:

```
test $(ytt --version | cut -d\  -f3) == v0.44.0
```

**Environment:**

- ytt version (use `ytt --version`): last versions (but according this command: `develop` :D )

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by mamachanko** [comment]
I see:
```shell
❯ uname -a
Darwin ***redacted*** 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64

❯ ytt --version
ytt version 0.44.1
```

How did you install `ytt` @alchimere ?

**Comment by alchimere** [comment]
@mamachanko Sorry I wrote the wrong installation command, with the wget it works correctly.

The command it doesn't work with is installation with `go install`:

```
go install  github.com/vmware-tanzu/carvel-ytt/cmd/ytt@v0.44.0
```

I understand why it produces this result but it feels unexpected that the version prints "develop" when installed with a version tag.

Feel free to close this issue if this behavior is intended.

**Comment by mamachanko** [comment]
> I understand why it produces this result but it feels unexpected that the version prints "develop" when installed with a version tag.

I tend to agree with you on this.

**Comment by mamachanko** [comment]
For reference, the version string is kept here: https://github.com/vmware-tanzu/carvel-ytt/blob/v0.44.1/pkg/version/version.go#L6

**Comment by jtigger** [comment]
Yeah... given what we know, right now, this seems to be the behavior that we expect.

Going to mark this as "closed"; looks like we've reached resolution.

That said, we're open to other perspectives! Feel free to comment on this issue if you see it differently.
