### ISSUE TITLE
Missing documentation on file marks

### ISSUE THREAD

**Issue by guludo** [k14s/ytt#80]
Hi there.

I looked through the documentation and could not find information about the available marks I can add to a file via the `--file-mark`. Is there any?

I found the possible marks by looking at the source code (method applyFileMarks in https://github.com/k14s/ytt/blob/master/pkg/cmd/template/regular_input.go).

**Comment by cppforlife** [comment]
@guludo yup, will add. im curious which ones you are using?

**Comment by guludo** [comment]
In particular, I used `--file-mark foo.yml:type=data` to tell `ytt` not to consider `foo.yml` a template to be processed. I was loading that file via in another template `data.read()`.

**Comment by cppforlife** [comment]
documented here: https://github.com/k14s/ytt/blob/develop/docs/file-marks.md
