### ISSUE TITLE
Clear all files from output directory when using --output-directory

### ISSUE THREAD

**Issue by strophy** [k14s/ytt#84]
ytt currently only deletes .yml files from `--output-directory` when it runs. Files of other types specified using `--file-mark` are not deleted but instead overwritten line by line, and if the previous content of the file was longer than the current output, then those lines remain at the bottom of the file.

Can we delete all files from the output directory instead, or at least delete files with names matching the files we are about to output?

[Slack discussion](https://kubernetes.slack.com/archives/CH8KCCKA5/p1580174166256800)

**Comment by cppforlife** [comment]
fixed in https://github.com/k14s/ytt/commit/c3e0f44983b998c7f6c7740e066e6f1c1e880653. will be available in upcoming release.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.26.0
