### ISSUE TITLE
Can we mutate yaml files with ytt ?

### ISSUE THREAD

**Issue by AbirHamzi** [k14s/ytt#89]
I need to load yaml files as they are into a template , how can I do this with ytt ?

**Comment by cppforlife** [comment]
i'm not sure i understood your question correctly but here is what i got:

config.yml
```yaml
#@ load("@ytt:data", "data")
config: #@ data.read("stuff.yml")
```

stuff.yml
```yaml
service:
  enabled: true
```

`ytt -f config.yml -f stuff.yml` would show you the result.

**Comment by AbirHamzi** [comment]
Actually it doesn't give the output that i want. The output that i want is the given by the following example :

config.yaml
```
#@ load("@ytt:data", "data")
config: #@ data.values
```

stuff.yaml
```
#@data/values
---
service:
  enabled: true
```

ytt -f config.yml -f stuff.yml gives me exactly the output i want , however in my use case I can't add `#@data/values` to the yaml file I just need to integrate it as it is , is it possible ?

**Comment by cppforlife** [comment]
can you not do something like this:

```
ytt -f config.yml -f <(echo -e "#@data/values\n---\n"; cat stuff.yml)
```

**Comment by AbirHamzi** [comment]
Yes nice workaround thank you for your help.

**Comment by cppforlife** [comment]
related: https://github.com/k14s/ytt/issues/51
