### ISSUE TITLE
Docs site is unavailable 

### ISSUE THREAD

**Issue by amimas** [k14s/ytt#902]
Hello, The documentation site seems to be down/unavailable. Not sure when that started but I've been trying at access the docs for couple days now.

**Comment by praveenrewar** [comment]
Hi @amimas, I just tried opening the website and it's working for me. Could you confirm that you are trying to open https://carvel.dev/ytt/ only?

**Comment by amimas** [comment]
Thanks for checking. Yeah that's the url I was trying. Seems to be working now.
