### ISSUE TITLE
add vs-code syntax highlighting for ytt

### ISSUE THREAD

**Issue by rnandi** [k14s/ytt#96]

**Comment by cppforlife** [comment]
similar to https://github.com/k14s/ytt/issues/97#issuecomment-590501954 ?

**Comment by ewrenn8** [comment]
A first pass at this can be found here: https://marketplace.visualstudio.com/items?itemName=ewrenn.vscode-ytt

Gonna close this issue. Any further discussions can be had on the [extension repo](https://github.com/ewrenn8/vscode-ytt)
