### ISSUE TITLE
provide a way for configuration to require minimum ytt version

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#98]
when using new features of ytt, it may be useful for authors to be able to specify minimum version of ytt, so that user can see decent looking error message telling them to update ytt.

- how dynamic should this be? (can this be used within conditional)
- what is the scope of this flag: module level, library level?
- should this be allowed within .star and .yaml files?

**Comment by cppforlife** [comment]
example: use older verison of ytt with github.com/cloudfoundry/cf-for-k8s, and see hard to guess error message.

**Comment by ewrenn8** [comment]
Added a new ytt library `version` which provides a function `require_at_least("Semver string")` to fail templating if the binary version is less than the string. Added in da51d804499823b1a4ddb8dddd3a8c51ccdc4db3

**Comment by cppforlife** [comment]
included in https://github.com/k14s/ytt/releases/tag/v0.26.0
